using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ACCostObjects
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACCostObjectsController
    //Created Date:21 June 2012
    //-----------------------------------------------------------

    public class ACCostObjectsController : BaseBusinessController
    {
        public ACCostObjectsController()
        {
            dal = new DALBaseProvider("ACCostObjects", typeof(ACCostObjectsInfo));
        }

        /// <summary>
        /// Get cost objects for transferring
        /// </summary>
        /// <returns>List of transferred cost objects</returns>
        public List<ACCostObjectsInfo> GetCostObjectsForTransferring()
        {
            DataSet ds = dal.GetDataSet("ACCostObjects_GetCostObjectsForTransferring");
            return (List<ACCostObjectsInfo>)GetListFromDataSet(ds);
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<ACCostObjectsInfo> costObjects = new List<ACCostObjectsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ACCostObjectsInfo costObject = (ACCostObjectsInfo)GetObjectFromDataRow(row);
                    costObjects.Add(costObject);
                }
            }
            return costObjects;
        }
        public DataSet GetCostObjectList(
                                   string costObjectNo,
                                   string costObjectName,
                                   int? branchID)
        {
            DataSet ds = dal.GetDataSet("ACCostObjects_GetCostObjectList", costObjectNo, costObjectName, branchID);
            return ds;
        }
        public DataSet GetCostObjectListByListOfBranchID(
                                                string costObjectNo,
                                                string costObjectName,
                                                List<BRBranchsInfo> branchList)
        {
            DataSet rtn = new DataSet();
            foreach (BRBranchsInfo ojbBranchsInfo in branchList)
            {
                DataSet ds = GetCostObjectList(costObjectNo, costObjectName, ojbBranchsInfo.BRBranchID);
                rtn.Merge(ds);
            }

            return rtn;
        }
    }
    #endregion
}