//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonLocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonLocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BOSERP.Localization.CommonLocalizedResources", typeof(CommonLocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        public static string ACAccountName {
            get {
                return ResourceManager.GetString("ACAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản.
        /// </summary>
        public static string ACAccountNo {
            get {
                return ResourceManager.GetString("ACAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chấp nhận thanh toán.
        /// </summary>
        public static string AcceptPayment {
            get {
                return ResourceManager.GetString("AcceptPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán bằng tín dụng đã vượt quá hạn mức của khách hàng.
        /// </summary>
        public static string AccountPaymentExceedsCreditLimitMessage {
            get {
                return ResourceManager.GetString("AccountPaymentExceedsCreditLimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản có.
        /// </summary>
        public static string ACDocumentCreditAccount {
            get {
                return ResourceManager.GetString("ACDocumentCreditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản nợ.
        /// </summary>
        public static string ACDocumentDebitAccount {
            get {
                return ResourceManager.GetString("ACDocumentDebitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ.
        /// </summary>
        public static string ACDocumentTypeDesc {
            get {
                return ResourceManager.GetString("ACDocumentTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại chứng từ.
        /// </summary>
        public static string ACDocumentTypeName {
            get {
                return ResourceManager.GetString("ACDocumentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ liên lạc.
        /// </summary>
        public static string ACObjectContactAddress {
            get {
                return ResourceManager.GetString("ACObjectContactAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string ACObjectContactPhone {
            get {
                return ResourceManager.GetString("ACObjectContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đối tượng.
        /// </summary>
        public static string ACObjectName {
            get {
                return ResourceManager.GetString("ACObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đối tượng.
        /// </summary>
        public static string ACObjectNo {
            get {
                return ResourceManager.GetString("ACObjectNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 4.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string APSupplierContactAddressLine1 {
            get {
                return ResourceManager.GetString("APSupplierContactAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string APSupplierContactPhone {
            get {
                return ResourceManager.GetString("APSupplierContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NCC.
        /// </summary>
        public static string APSupplierName {
            get {
                return ResourceManager.GetString("APSupplierName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã NCC.
        /// </summary>
        public static string APSupplierNo {
            get {
                return ResourceManager.GetString("APSupplierNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string APSupplierTaxNumber {
            get {
                return ResourceManager.GetString("APSupplierTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ liên lạc.
        /// </summary>
        public static string ARCustomerContactAddressLine3 {
            get {
                return ResourceManager.GetString("ARCustomerContactAddressLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string ARCustomerContactPhone {
            get {
                return ResourceManager.GetString("ARCustomerContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khách hàng.
        /// </summary>
        public static string ARCustomerName {
            get {
                return ResourceManager.GetString("ARCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng.
        /// </summary>
        public static string ARCustomerNo {
            get {
                return ResourceManager.GetString("ARCustomerNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string ARCustomerTaxNumber {
            get {
                return ResourceManager.GetString("ARCustomerTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn hàng.
        /// </summary>
        public static string ARSaleOrderNo {
            get {
                return ResourceManager.GetString("ARSaleOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 8.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể hạch toán vào tài khoản cha..
        /// </summary>
        public static string CannotMakeEntryWithParentAccountMessage {
            get {
                return ResourceManager.GetString("CannotMakeEntryWithParentAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không thể thanh toán bằng nhiều loại tiền tệ.
        /// </summary>
        public static string CannotPayWithMultipleCurrencyMessage {
            get {
                return ResourceManager.GetString("CannotPayWithMultipleCurrencyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thực hiện đa thanh toán.
        /// </summary>
        public static string CannotTakeMultiplePayment {
            get {
                return ResourceManager.GetString("CannotTakeMultiplePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi mật khẩu thành công.
        /// </summary>
        public static string ChangePasswordSuccessfullyMessage {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá trị các kích thước không đúng, vui lòng kiểm tra lại!.
        /// </summary>
        public static string CheckValueResizedMessage {
            get {
                return ResourceManager.GetString("CheckValueResizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn phiếu cọc.
        /// </summary>
        public static string ChooseDepositMessage {
            get {
                return ResourceManager.GetString("ChooseDepositMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CollapsibleGroupBox {
            get {
                object obj = ResourceManager.GetObject("CollapsibleGroupBox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cột phải là số nguyên.
        /// </summary>
        public static string ColumnErrorMessage {
            get {
                return ResourceManager.GetString("ColumnErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn cần chắc chắn những dữ liệu liên quan đã được xử lý đúng trước khi thay đổi trạng thái của chứng từ. Bạn có muốn tiếp tục?.
        /// </summary>
        public static string ConfirmChangeDocumentStatusMessage {
            get {
                return ResourceManager.GetString("ConfirmChangeDocumentStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu xác nhận không khớp.
        /// </summary>
        public static string ConfirmedPasswordNotMatchMessage {
            get {
                return ResourceManager.GetString("ConfirmedPasswordNotMatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này có mức giá khác so với mức giá hiện tại. Bạn có muốn áp dụng?.
        /// </summary>
        public static string ConfirmPriceLevelMessage {
            get {
                return ResourceManager.GetString("ConfirmPriceLevelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu ghi có không tồn tại.
        /// </summary>
        public static string CreditNoteDoesNotExistMessage {
            get {
                return ResourceManager.GetString("CreditNoteDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu ghi có đã hết hạn vào ngày {0}.
        /// </summary>
        public static string CreditNoteHasExpiredMessage {
            get {
                return ResourceManager.GetString("CreditNoteHasExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán bằng phiếu ghi có vượt quá giá trị còn lại {0}.
        /// </summary>
        public static string CreditNotePaymentExceedsRemainingAmountMessage {
            get {
                return ResourceManager.GetString("CreditNotePaymentExceedsRemainingAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 12.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu đặt cọc {0} không tồn tại.
        /// </summary>
        public static string DepositDoesNotExistMessage {
            get {
                return ResourceManager.GetString("DepositDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đính kèm không được bỏ trống..
        /// </summary>
        public static string DepositIsRequiredMessage {
            get {
                return ResourceManager.GetString("DepositIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán phải nhỏ hơn tổng tiền trong phiếu chuyển cọc.
        /// </summary>
        public static string DepositMustBeLessThanTotalDepositTransferMessage {
            get {
                return ResourceManager.GetString("DepositMustBeLessThanTotalDepositTransferMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy bỏ thanh toán.
        /// </summary>
        public static string DiscardPayment {
            get {
                return ResourceManager.GetString("DiscardPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string EditPicture {
            get {
                return ResourceManager.GetString("EditPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số điện thoại để tiến hành tìm kiếm bệnh nhân trên hệ thống Bacsi24x7.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 2.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 6.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số tiền..
        /// </summary>
        public static string GiftVoucherAmountRequiredMessage {
            get {
                return ResourceManager.GetString("GiftVoucherAmountRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu quà tặng {0} không tồn tại.
        /// </summary>
        public static string GiftVoucherDoesNotExistMessage {
            get {
                return ResourceManager.GetString("GiftVoucherDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phiếu quà tặng {0} đã hết hạn vào ngày {1}.
        /// </summary>
        public static string GiftVoucherHasExpiredMessage {
            get {
                return ResourceManager.GetString("GiftVoucherHasExpiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán bằng phiếu quà tặng vượt quá giá trị còn lại.
        /// </summary>
        public static string GiftVoucherPaymentExceedsRemainingAmountMessage {
            get {
                return ResourceManager.GetString("GiftVoucherPaymentExceedsRemainingAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chấm công.
        /// </summary>
        public static string HREmployeeCardNumber {
            get {
                return ResourceManager.GetString("HREmployeeCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string HREmployeeName {
            get {
                return ResourceManager.GetString("HREmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string HREmployeeName2 {
            get {
                return ResourceManager.GetString("HREmployeeName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string HREmployeeNo {
            get {
                return ResourceManager.GetString("HREmployeeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string ICMeasureUnitName {
            get {
                return ResourceManager.GetString("ICMeasureUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng hiện có.
        /// </summary>
        public static string ICPackageProductOnHandQty {
            get {
                return ResourceManager.GetString("ICPackageProductOnHandQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng.
        /// </summary>
        public static string ICPackageProductQty {
            get {
                return ResourceManager.GetString("ICPackageProductQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string ICProductName {
            get {
                return ResourceManager.GetString("ICProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sản phẩm.
        /// </summary>
        public static string ICProductNo {
            get {
                return ResourceManager.GetString("ICProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã lô.
        /// </summary>
        public static string ICProductSerieNo {
            get {
                return ResourceManager.GetString("ICProductSerieNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm ảnh vì có lỗi xảy ra.
        /// </summary>
        public static string InsertImageFailedMessage {
            get {
                return ResourceManager.GetString("InsertImageFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng tập tin đính kèm được lớn hơn 1MB.
        /// </summary>
        public static string InvalidAttachedFileSizeMessage {
            get {
                return ResourceManager.GetString("InvalidAttachedFileSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cỡ chữ không đúng, vui lòng chọn cỡ chữ.
        /// </summary>
        public static string InvalidFontSizeMessage {
            get {
                return ResourceManager.GetString("InvalidFontSizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có font này, vui lòng chọn font.
        /// </summary>
        public static string InvalidFontStyleMessage {
            get {
                return ResourceManager.GetString("InvalidFontStyleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn {0} không tồn tại.
        /// </summary>
        public static string InvoiceDoesNotExistMessage {
            get {
                return ResourceManager.GetString("InvoiceDoesNotExistMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn {0} không có nợ âm để cấn trừ.
        /// </summary>
        public static string InvoiceHasNoNegativeOwingMessage {
            get {
                return ResourceManager.GetString("InvoiceHasNoNegativeOwingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 1.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 7.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 6.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số cột phải lớn hơn hoặc bằng một và nhỏ hơn hoặc bằng sáu mươi ba.
        /// </summary>
        public static string LimitColumnMessage {
            get {
                return ResourceManager.GetString("LimitColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng phải lớn hơn hoặc bằng một và nhỏ hơn hoặc bằng sáu mươi ba.
        /// </summary>
        public static string LimitRowMessage {
            get {
                return ResourceManager.GetString("LimitRowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu báo cáo lỗi.
        /// </summary>
        public static string LogOnDataBaseErrorMessage {
            get {
                return ResourceManager.GetString("LogOnDataBaseErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ mail không hợp lệ.
        /// </summary>
        public static string MailAddressErrorMessage {
            get {
                return ResourceManager.GetString("MailAddressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ nhiều mail cách nhau bởi dấu ;.
        /// </summary>
        public static string MailErrorMessage {
            get {
                return ResourceManager.GetString("MailErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được gửi thành công.
        /// </summary>
        public static string MailSentMessage {
            get {
                return ResourceManager.GetString("MailSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 3.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 5.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên thuốc/ DCYT.
        /// </summary>
        public static string MedicineAndEquipmentName {
            get {
                return ResourceManager.GetString("MedicineAndEquipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thuốc / DCYT.
        /// </summary>
        public static string MedicineAndEquipmentNo {
            get {
                return ResourceManager.GetString("MedicineAndEquipmentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sao chép.
        /// </summary>
        public static string MenuCopy {
            get {
                return ResourceManager.GetString("MenuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to.
        /// </summary>
        public static string MenuCopyTo {
            get {
                return ResourceManager.GetString("MenuCopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cắt.
        /// </summary>
        public static string MenuCut {
            get {
                return ResourceManager.GetString("MenuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa vùng được chọn.
        /// </summary>
        public static string MenuDeleteSelection {
            get {
                return ResourceManager.GetString("MenuDeleteSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hồ sơ.
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh.
        /// </summary>
        public static string MenuImage {
            get {
                return ResourceManager.GetString("MenuImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới.
        /// </summary>
        public static string MenuNew {
            get {
                return ResourceManager.GetString("MenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở tập tin.
        /// </summary>
        public static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dán.
        /// </summary>
        public static string MenuPaste {
            get {
                return ResourceManager.GetString("MenuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đi tới.
        /// </summary>
        public static string MenuRedo {
            get {
                return ResourceManager.GetString("MenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh lại kích thước.
        /// </summary>
        public static string MenuResize {
            get {
                return ResourceManager.GetString("MenuResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoay.
        /// </summary>
        public static string MenuRotate {
            get {
                return ResourceManager.GetString("MenuRotate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoay 180 độ.
        /// </summary>
        public static string MenuRotate180 {
            get {
                return ResourceManager.GetString("MenuRotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lật ngang.
        /// </summary>
        public static string MenuRotateFlipH {
            get {
                return ResourceManager.GetString("MenuRotateFlipH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lật dọc.
        /// </summary>
        public static string MenuRotateFlipV {
            get {
                return ResourceManager.GetString("MenuRotateFlipV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoay trái 90 độ.
        /// </summary>
        public static string MenuRotateLeft90 {
            get {
                return ResourceManager.GetString("MenuRotateLeft90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoay phải 90 độ.
        /// </summary>
        public static string MenuRotateRight90 {
            get {
                return ResourceManager.GetString("MenuRotateRight90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu mới.
        /// </summary>
        public static string MenuSaveAs {
            get {
                return ResourceManager.GetString("MenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn tất cả.
        /// </summary>
        public static string MenuSelectAll {
            get {
                return ResourceManager.GetString("MenuSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show grid.
        /// </summary>
        public static string MenuShowGrid {
            get {
                return ResourceManager.GetString("MenuShowGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show thumbnails.
        /// </summary>
        public static string MenuShowThumbnails {
            get {
                return ResourceManager.GetString("MenuShowThumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        public static string MenuUndo {
            get {
                return ResourceManager.GetString("MenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật hình ảnh.
        /// </summary>
        public static string MenuUpdateImage {
            get {
                return ResourceManager.GetString("MenuUpdateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tầm nhìn.
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem toàn màn hình.
        /// </summary>
        public static string MenuViewFullScreen {
            get {
                return ResourceManager.GetString("MenuViewFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị tình trạng.
        /// </summary>
        public static string MenuViewStatus {
            get {
                return ResourceManager.GetString("MenuViewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị thanh công cụ.
        /// </summary>
        public static string MenuViewToolbar {
            get {
                return ResourceManager.GetString("MenuViewToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phóng to / Thu nhỏ.
        /// </summary>
        public static string MenuZoom {
            get {
                return ResourceManager.GetString("MenuZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bệnh nhân.
        /// </summary>
        public static string MEPatientName {
            get {
                return ResourceManager.GetString("MEPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string MessageBoxDefaultCaption {
            get {
                return ResourceManager.GetString("MessageBoxDefaultCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 2.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình ảnh mới.
        /// </summary>
        public static string NewImageMessage {
            get {
                return ResourceManager.GetString("NewImageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập số cột.
        /// </summary>
        public static string NotNullOrEmptyColumnMessage {
            get {
                return ResourceManager.GetString("NotNullOrEmptyColumnMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập chuỗi cần tìm.
        /// </summary>
        public static string NotNullOrEmptyFindThisMessage {
            get {
                return ResourceManager.GetString("NotNullOrEmptyFindThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 11.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 10.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán bằng cấn trừ nợ vượt quá số tiền còn lại của hóa đơn.
        /// </summary>
        public static string OwingExchangePaymentExceedsRemainedAmountMessage {
            get {
                return ResourceManager.GetString("OwingExchangePaymentExceedsRemainedAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gói khám.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện hàng đã được chọn trước đó.
        /// </summary>
        public static string PackageAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiện không còn đủ hàng.
        /// </summary>
        public static string PackageIsNotEnoughQtyMessage {
            get {
                return ResourceManager.GetString("PackageIsNotEnoughQtyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không thể để trống.
        /// </summary>
        public static string PasswordIsRequiredMessage {
            get {
                return ResourceManager.GetString("PasswordIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán không được để trống.
        /// </summary>
        public static string PaymentAmountIsRequiredMessage {
            get {
                return ResourceManager.GetString("PaymentAmountIsRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thanh toán phải bằng hoặc lớn hơn tiền cọc tối thiểu.
        /// </summary>
        public static string PaymentAmountMustBeGreaterThanMinimumDepositMessage {
            get {
                return ResourceManager.GetString("PaymentAmountMustBeGreaterThanMinimumDepositMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi sổ.
        /// </summary>
        public static string PostedCaption {
            get {
                return ResourceManager.GetString("PostedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi sổ thành công.
        /// </summary>
        public static string PostedSuccessfullMessage {
            get {
                return ResourceManager.GetString("PostedSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể in vì có lỗi xảy ra.
        /// </summary>
        public static string PrintFailedMessage {
            get {
                return ResourceManager.GetString("PrintFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền nhận phải lớn hơn tiền thanh toán.
        /// </summary>
        public static string ReceivingAmountMustBeGreaterThanPaymentAmountMessage {
            get {
                return ResourceManager.GetString("ReceivingAmountMustBeGreaterThanPaymentAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số dòng phải là số nguyên.
        /// </summary>
        public static string RowErrorMessage {
            get {
                return ResourceManager.GetString("RowErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 7.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu không thành công.
        /// </summary>
        public static string SaveFailedMessage {
            get {
                return ResourceManager.GetString("SaveFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công.
        /// </summary>
        public static string SaveSuccessful {
            get {
                return ResourceManager.GetString("SaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có camera nào hoạt động, vui lòng kiểm tra và chọn camera..
        /// </summary>
        public static string SelectCameraMessage {
            get {
                return ResourceManager.GetString("SelectCameraMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 9.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string ServiceDate {
            get {
                return ResourceManager.GetString("ServiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string ServiceDesc {
            get {
                return ResourceManager.GetString("ServiceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên dịch vụ.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người chỉ định.
        /// </summary>
        public static string ServiceOrderBy {
            get {
                return ResourceManager.GetString("ServiceOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh lí.
        /// </summary>
        public static string ServicePathological {
            get {
                return ResourceManager.GetString("ServicePathological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết quả.
        /// </summary>
        public static string ServiceResult {
            get {
                return ResourceManager.GetString("ServiceResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trả kết quả cho.
        /// </summary>
        public static string ServiceReturnTo {
            get {
                return ResourceManager.GetString("ServiceReturnTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng.
        /// </summary>
        public static string ServiceStatus {
            get {
                return ResourceManager.GetString("ServiceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mức độ.
        /// </summary>
        public static string ServiceUrgency {
            get {
                return ResourceManager.GetString("ServiceUrgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhật.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm không thuộc kiện hàng này.
        /// </summary>
        public static string SynPackageAndProductMessage {
            get {
                return ResourceManager.GetString("SynPackageAndProductMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu của {0} {1}.
        /// </summary>
        public static string TakeDepositDefaultDesc {
            get {
                return ResourceManager.GetString("TakeDepositDefaultDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 5.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền không được lớn hơn tiền thanh toán.
        /// </summary>
        public static string TotalAmountCannotBeGreaterThanPaymentAmountMessage {
            get {
                return ResourceManager.GetString("TotalAmountCannotBeGreaterThanPaymentAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng tiền không được nhỏ hơn tiền thanh toán.
        /// </summary>
        public static string TotalAmountCannotBeLessThanPaymentAmountMessage {
            get {
                return ResourceManager.GetString("TotalAmountCannotBeLessThanPaymentAmountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giao dịch đã bị khóa. Bạn không thể chỉnh sửa..
        /// </summary>
        public static string TransactionHasBeenLocked {
            get {
                return ResourceManager.GetString("TransactionHasBeenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 3.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ ghi.
        /// </summary>
        public static string UnPostedCaption {
            get {
                return ResourceManager.GetString("UnPostedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bỏ ghi thành công.
        /// </summary>
        public static string UnPostedSuccessfullMessage {
            get {
                return ResourceManager.GetString("UnPostedSuccessfullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đang sử dụng phiên bản cũ. Vui lòng liên hệ người quản trị hệ thống để cập nhật!.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ 4.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
    }
}
