using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ICProductOrigins
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICProductOriginsController
    //Created Date:Tuesday, July 16, 2013
    //-----------------------------------------------------------

    public class ICProductOriginsController : BaseBusinessController
    {
        public ICProductOriginsController()
        {
            dal = new DALBaseProvider("ICProductOrigins", typeof(ICProductOriginsInfo));
        }
    }
    #endregion
}