using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ARProposalItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARProposalItemsController
    //Created Date:Friday, August 20, 2010
    //-----------------------------------------------------------

    public class ARProposalItemsController : BaseBusinessController
    {
        public ARProposalItemsController()
        {
            dal = new DALBaseProvider("ARProposalItems", typeof(ARProposalItemsInfo));
        }
    }
    #endregion
}