using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region HRMailAttachments
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRMailAttachmentsInfo
    //Created Date:Tuesday, May 10, 2011
    //-----------------------------------------------------------

    public class HRMailAttachmentsInfo : BusinessObject
    {
        public HRMailAttachmentsInfo()
        {
        }
        #region Variables
        protected int _hRMailAttachmentID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HRMailID;
        protected String _hRMailAttachmentName = String.Empty;
        protected String _hRMailAttachmentFileType = String.Empty;
        protected String _hRMailAttachmentFileSize = String.Empty;
        #endregion

        #region Public properties
        public int HRMailAttachmentID
        {
            get { return _hRMailAttachmentID; }
            set
            {
                if (value != this._hRMailAttachmentID)
                {
                    _hRMailAttachmentID = value;
                    NotifyChanged("HRMailAttachmentID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HRMailID
        {
            get { return _fK_HRMailID; }
            set
            {
                if (value != this._fK_HRMailID)
                {
                    _fK_HRMailID = value;
                    NotifyChanged("FK_HRMailID");
                }
            }
        }
        public String HRMailAttachmentName
        {
            get { return _hRMailAttachmentName; }
            set
            {
                if (value != this._hRMailAttachmentName)
                {
                    _hRMailAttachmentName = value;
                    NotifyChanged("HRMailAttachmentName");
                }
            }
        }
        public String HRMailAttachmentFileType
        {
            get { return _hRMailAttachmentFileType; }
            set
            {
                if (value != this._hRMailAttachmentFileType)
                {
                    _hRMailAttachmentFileType = value;
                    NotifyChanged("HRMailAttachmentFileType");
                }
            }
        }
        public String HRMailAttachmentFileSize
        {
            get { return _hRMailAttachmentFileSize; }
            set
            {
                if (value != this._hRMailAttachmentFileSize)
                {
                    _hRMailAttachmentFileSize = value;
                    NotifyChanged("HRMailAttachmentFileSize");
                }
            }
        }
        #endregion
    }
    #endregion
}