using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region HRManufactureTimeSheetItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRManufactureTimeSheetItemsInfo
    //Created Date:Saturday, December 21, 2013
    //-----------------------------------------------------------

    public class HRManufactureTimeSheetItemsInfo : BusinessObject
    {
        public HRManufactureTimeSheetItemsInfo()
        {
        }
        #region Variables
        protected int _hRManufactureTimeSheetItemID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HRManufactureTimeSheetID;
        protected int _fK_MMBatchID;
        protected int _fK_MMOperationID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICDepartmentID;
        protected int _fK_MMProductionNormID;
        protected int _fK_ICProductIDForBatch;
        protected int _fK_ARSaleOrderID;
        protected int _fK_MMProposalID;
        protected int _fK_HREmployeeID;
        protected int _hRManufactureTimeSheetItemBatchComponent;
        protected String _hRManufactureTimeSheetItemComments = String.Empty;
        protected String _hRManufactureTimeSheetItemProductNo = String.Empty;
        protected String _hRManufactureTimeSheetItemProductName = String.Empty;
        protected String _hRManufactureTimeSheetItemProductDesc = String.Empty;
        protected String _hRManufactureTimeSheetItemProductSerialNo = String.Empty;
        protected String _hRManufactureTimeSheetItemProductAttributes = String.Empty;
        protected double _hRManufactureTimeSheetItemProductQty;
        protected bool _hRManufactureTimeSheetItemOperationStatus = true;
        protected int _fK_ARSaleOrderItemID;
        #endregion

        #region Public properties
        public int HRManufactureTimeSheetItemID
        {
            get { return _hRManufactureTimeSheetItemID; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemID)
                {
                    _hRManufactureTimeSheetItemID = value;
                    NotifyChanged("HRManufactureTimeSheetItemID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HRManufactureTimeSheetID
        {
            get { return _fK_HRManufactureTimeSheetID; }
            set
            {
                if (value != this._fK_HRManufactureTimeSheetID)
                {
                    _fK_HRManufactureTimeSheetID = value;
                    NotifyChanged("FK_HRManufactureTimeSheetID");
                }
            }
        }
        public int FK_MMBatchID
        {
            get { return _fK_MMBatchID; }
            set
            {
                if (value != this._fK_MMBatchID)
                {
                    _fK_MMBatchID = value;
                    NotifyChanged("FK_MMBatchID");
                }
            }
        }
        public int FK_MMOperationID
        {
            get { return _fK_MMOperationID; }
            set
            {
                if (value != this._fK_MMOperationID)
                {
                    _fK_MMOperationID = value;
                    NotifyChanged("FK_MMOperationID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_MMProductionNormID
        {
            get { return _fK_MMProductionNormID; }
            set
            {
                if (value != this._fK_MMProductionNormID)
                {
                    _fK_MMProductionNormID = value;
                    NotifyChanged("FK_MMProductionNormID");
                }
            }
        }
        public int FK_ICProductIDForBatch
        {
            get { return _fK_ICProductIDForBatch; }
            set
            {
                if (value != this._fK_ICProductIDForBatch)
                {
                    _fK_ICProductIDForBatch = value;
                    NotifyChanged("FK_ICProductIDForBatch");
                }
            }
        }
        public int FK_ARSaleOrderID
        {
            get { return _fK_ARSaleOrderID; }
            set
            {
                if (value != this._fK_ARSaleOrderID)
                {
                    _fK_ARSaleOrderID = value;
                    NotifyChanged("FK_ARSaleOrderID");
                }
            }
        }
        public int FK_MMProposalID
        {
            get { return _fK_MMProposalID; }
            set
            {
                if (value != this._fK_MMProposalID)
                {
                    _fK_MMProposalID = value;
                    NotifyChanged("FK_MMProposalID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int HRManufactureTimeSheetItemBatchComponent
        {
            get { return _hRManufactureTimeSheetItemBatchComponent; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemBatchComponent)
                {
                    _hRManufactureTimeSheetItemBatchComponent = value;
                    NotifyChanged("HRManufactureTimeSheetItemBatchComponent");
                }
            }
        }
        public String HRManufactureTimeSheetItemComments
        {
            get { return _hRManufactureTimeSheetItemComments; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemComments)
                {
                    _hRManufactureTimeSheetItemComments = value;
                    NotifyChanged("HRManufactureTimeSheetItemComments");
                }
            }
        }
        public String HRManufactureTimeSheetItemProductNo
        {
            get { return _hRManufactureTimeSheetItemProductNo; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductNo)
                {
                    _hRManufactureTimeSheetItemProductNo = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductNo");
                }
            }
        }
        public String HRManufactureTimeSheetItemProductName
        {
            get { return _hRManufactureTimeSheetItemProductName; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductName)
                {
                    _hRManufactureTimeSheetItemProductName = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductName");
                }
            }
        }
        public String HRManufactureTimeSheetItemProductDesc
        {
            get { return _hRManufactureTimeSheetItemProductDesc; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductDesc)
                {
                    _hRManufactureTimeSheetItemProductDesc = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductDesc");
                }
            }
        }
        public String HRManufactureTimeSheetItemProductSerialNo
        {
            get { return _hRManufactureTimeSheetItemProductSerialNo; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductSerialNo)
                {
                    _hRManufactureTimeSheetItemProductSerialNo = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductSerialNo");
                }
            }
        }
        public String HRManufactureTimeSheetItemProductAttributes
        {
            get { return _hRManufactureTimeSheetItemProductAttributes; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductAttributes)
                {
                    _hRManufactureTimeSheetItemProductAttributes = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductAttributes");
                }
            }
        }
        public double HRManufactureTimeSheetItemProductQty
        {
            get { return _hRManufactureTimeSheetItemProductQty; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemProductQty)
                {
                    _hRManufactureTimeSheetItemProductQty = value;
                    NotifyChanged("HRManufactureTimeSheetItemProductQty");
                }
            }
        }
        public bool HRManufactureTimeSheetItemOperationStatus
        {
            get { return _hRManufactureTimeSheetItemOperationStatus; }
            set
            {
                if (value != this._hRManufactureTimeSheetItemOperationStatus)
                {
                    _hRManufactureTimeSheetItemOperationStatus = value;
                    NotifyChanged("HRManufactureTimeSheetItemOperationStatus");
                }
            }
        }
        public int FK_ARSaleOrderItemID
        {
            get { return _fK_ARSaleOrderItemID; }
            set
            {
                if (value != this._fK_ARSaleOrderItemID)
                {
                    _fK_ARSaleOrderItemID = value;
                    NotifyChanged("FK_ARSaleOrderItemID");
                }
            }
        }
        #endregion

    }
    #endregion
}