using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSLib
{
    #region ADUserConfigs
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ADUserConfigsController
    //Created Date:Thursday, December 19, 2019
    //-----------------------------------------------------------

    public class ADUserConfigsController : BaseBusinessController
    {
        public ADUserConfigsController()
        {
            dal = new DALBaseProvider("ADUserConfigs", typeof(ADUserConfigsInfo));
        }
        public List<ADUserConfigsInfo> GetAllUserConfigs(int userID)
        {
            var ds = dal.GetAllDataByForeignColumn("FK_ADUserID", userID);
            return this.GetListBusinessObjects<ADUserConfigsInfo>(ds);
        }
    }
    #endregion
}