using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region MEEmrShareHistories
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEEmrShareHistoriesController
    //Created Date:Monday, June 25, 2018
    //-----------------------------------------------------------

    public class MEEmrShareHistoriesController : BaseBusinessController
    {
        public MEEmrShareHistoriesController()
        {
            dal = new DALBaseProvider("MEEmrShareHistories", typeof(MEEmrShareHistoriesInfo));
        }
        public List<MEEmrShareHistoriesInfo> GetByEmrId(int emrID)
        {
            var ds = this.GetAllDataByForeignColumn("FK_MEEmrID", emrID);
            return GetListBusinessObjects<MEEmrShareHistoriesInfo>(ds);
        }

        public bool UpdateAllInactive(int emrID)
        {
            var value = dal.GetSingleValue("MEEmrShareHistories_UpdateAllInactive", emrID);
            return Convert.ToInt32(value) == 1;
        }

        public MEEmrShareHistoriesInfo CheckEditPermission(int emrId, int hREmployeeID, int fK_HRDepartmentID, string view, string mode)
        {
            return base.GetDataObject("MEEmrShareHistories_CheckEditPermission", emrId, hREmployeeID, fK_HRDepartmentID, view, mode) as MEEmrShareHistoriesInfo;
        }

    }
    #endregion
}