ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaStr1 NVARCHAR(1024)

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaStr2 NVARCHAR(1024)

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaStr3 NVARCHAR(1024)

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaStr4 NVARCHAR(1024)

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaStr5 NVARCHAR(1024)

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaNum1 DECIMAL

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaNum2 DECIMAL

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaNum3 DECIMAL

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaNum4 DECIMAL

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaNum5 DECIMAL

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaDate1 DATETIME

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaDate2 DATETIME

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaDate3 DATETIME

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaDate4 DATETIME

ALTER TABLE [dbo].[MEEmrs] ADD MEEmrMetaDate5 DATETIME
