using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEPackageItemGroups
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEPackageItemGroupsInfo
    //Created Date:Wednesday, February 09, 2011
    //-----------------------------------------------------------

    public class MEPackageItemGroupsInfo : BusinessObject
    {
        public MEPackageItemGroupsInfo()
        {
        }
        #region Variables
        protected int _mEPackageItemGroupID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _mEPackageItemGroupName = String.Empty;
        protected String _mEPackageItemGroupDesc = String.Empty;
        #endregion

        #region Public properties
        public int MEPackageItemGroupID
        {
            get { return _mEPackageItemGroupID; }
            set
            {
                if (value != this._mEPackageItemGroupID)
                {
                    _mEPackageItemGroupID = value;
                    NotifyChanged("MEPackageItemGroupID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String MEPackageItemGroupName
        {
            get { return _mEPackageItemGroupName; }
            set
            {
                if (value != this._mEPackageItemGroupName)
                {
                    _mEPackageItemGroupName = value;
                    NotifyChanged("MEPackageItemGroupName");
                }
            }
        }
        public String MEPackageItemGroupDesc
        {
            get { return _mEPackageItemGroupDesc; }
            set
            {
                if (value != this._mEPackageItemGroupDesc)
                {
                    _mEPackageItemGroupDesc = value;
                    NotifyChanged("MEPackageItemGroupDesc");
                }
            }
        }
        #endregion
    }
    #endregion
}