using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region AAInventoryStockSlot
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:AAInventoryStockSlotController
	//Created Date:Wednesday, April 18, 2007
	//-----------------------------------------------------------
	
	public class AAInventoryStockSlotController:BaseBusinessController
	{
        private readonly string spGetAAInventoryStockSlotByMAProductIDAndMAStockSlotID =
                                "AAInventoryStockSlot_SelectByMAProductIDAndMAStockSlotID";
		public AAInventoryStockSlotController()
		{
			dal= new DALBaseProvider("AAInventoryStockSlot",typeof(AAInventoryStockSlotInfo));
		}

        public AAInventoryStockSlotInfo GetAAInventoryStockSlotByMAProductIDAndMAStockSlotID(int iMAProductID, int iMAStockSlotID)
        {
            return (AAInventoryStockSlotInfo)dal.GetDataObject(spGetAAInventoryStockSlotByMAProductIDAndMAStockSlotID, iMAProductID, iMAStockSlotID);
        }
	}
	#endregion
}