using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region HRAdvanceRequestItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRAdvanceRequestItemsController
    //Created Date:Monday, October 28, 2013
    //-----------------------------------------------------------

    public class HRAdvanceRequestItemsController : BaseBusinessController
    {
        public HRAdvanceRequestItemsController()
        {
            dal = new DALBaseProvider("HRAdvanceRequestItems", typeof(HRAdvanceRequestItemsInfo));
        }
        /// <summary>
        /// Get the purchase order list for invoicing
        /// </summary>
        /// <returns>List of purchase orders</returns>
        public HRAdvanceRequestItemsInfo GetAdvanceRequestItemsByAdvanceRequestIDAndEmployeeNo(int advanceRequestID, string employeeNo )
        {
            DataSet ds = dal.GetDataSet("HRAdvanceRequestItems_GetAdvanceRequestItemsByAdvanceRequestIDAndEmployeeNo", advanceRequestID, employeeNo);
            List<HRAdvanceRequestsInfo> advanceRequestList = new List<HRAdvanceRequestsInfo>();
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count >0 )
            {
                DataRow row = ds.Tables[0].Rows[0];

                HRAdvanceRequestItemsInfo objAdvanceRequestItemsInfo = (HRAdvanceRequestItemsInfo)GetObjectFromDataRow(row);
                return objAdvanceRequestItemsInfo;
            }
            return null;
        }

        public DataSet GetAdvanceRequestItemsFromDateToDateByEmployeeID(int employeeID, DateTime dateFrom, DateTime dateTo)
        {
            DataSet ds = dal.GetDataSet("HRAdvanceRequestItems_GetAdvanceRequestItemsFromDateToDateByEmployeeID", employeeID, dateFrom, dateTo);
            return ds;
        }

        public DataSet GetAdvanceRequestItemsByEmployeeIDAndFromDateToDate(int employeeID, DateTime dateFrom, DateTime dateTo)
        {
            DataSet ds = dal.GetDataSet("HRAdvanceRequestItems_GetAdvanceRequestItemsByEmployeeIDAndFromDateToDate", employeeID, dateFrom, dateTo);
            return ds;
        }
    }
    #endregion
}