using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region HRCandidates
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRCandidatesController
    //Created Date:Monday, September 16, 2013
    //-----------------------------------------------------------

    public class HRCandidatesController : BaseBusinessController
    {
        public HRCandidatesController()
        {
            dal = new DALBaseProvider("HRCandidates", typeof(HRCandidatesInfo));
        }

        /// <summary>
        /// Get the list of employees based on some criteria
        /// </summary>
        /// <param name="employeeNo">Employee no</param>
        /// <param name="employeeName">Employee name</param>
        /// <param name="contactAddress">Contact address</param>
        /// <param name="gender">Gender</param>
        /// <param name="idNumber">Id number</param>
        /// <param name="roomID">Room id</param>
        /// <param name="levelID">Level id</param>
        /// <param name="branchID">Branch id</param>
        /// <returns>Employee list</returns>
        public DataSet GetCandidateList(
                                    string candidateNo,
                                    string candidateName,
                                    string candidateGender,
                                    int? candidateID,
                                    string candidateContactAddress,
                                    DateTime? dateFrom,
                                    DateTime? dateTo)
        {
            DataSet ds = dal.GetDataSet("HRCandidates_GetCandidateList",
                                        candidateNo,
                                        candidateName,
                                        candidateGender,
                                        candidateID,
                                        candidateContactAddress,
                                        dateFrom,
                                        dateTo);
            return ds;
        }
    }
    #endregion
}