using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region HREmployeeTranfers
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HREmployeeTranfersController
    //Created Date:Thursday, October 10, 2013
    //-----------------------------------------------------------

    public class HREmployeeTranfersController : BaseBusinessController
    {
        public HREmployeeTranfersController()
        {
            dal = new DALBaseProvider("HREmployeeTranfers", typeof(HREmployeeTranfersInfo));
        }

        public HREmployeeTranfersInfo GetOldEmployeeTranferByTranferID(int tranferID, int employeeID)
        {
            return (HREmployeeTranfersInfo)dal.GetDataObject("HREmployeeTranfers_GetOldEmployeeTranferByTranferID", tranferID, employeeID);
        }
    }
    #endregion
}