using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region HRMachineTimeKeepers
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:HRMachineTimeKeepersController
	//Created Date:02 November 2013
	//-----------------------------------------------------------
	
	public class HRMachineTimeKeepersController:BaseBusinessController
	{
		public HRMachineTimeKeepersController()
		{
			dal= new DALBaseProvider("HRMachineTimeKeepers",typeof(HRMachineTimeKeepersInfo));
		}
        /// <summary>
        /// Get the sale order list for canceling
        /// </summary>
        /// <returns>List of sale orders</returns>
        public List<HRMachineTimeKeepersInfo> GetAllObjectList()
        {
            DataSet ds = dal.GetDataSet("HRMachineTimeKeepers_SelectAll");
            List<HRMachineTimeKeepersInfo> machineTimeKeeperList = new List<HRMachineTimeKeepersInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRMachineTimeKeepersInfo objMachineTimeKeepersInfo = (HRMachineTimeKeepersInfo)GetObjectFromDataRow(row);
                    machineTimeKeeperList.Add(objMachineTimeKeepersInfo);
                }
            }
            return machineTimeKeeperList;
        }
	}
	#endregion
}