using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;
using System.Linq;

namespace BOSERP
{
    #region HRTimeSheetParams
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRTimeSheetParamsController
    //Created Date:Monday, April 04, 2011
    //-----------------------------------------------------------

    public class HRTimeSheetParamsController : BaseBusinessController
    {
        public HRTimeSheetParamsController()
        {
            dal = new DALBaseProvider("HRTimeSheetParams", typeof(HRTimeSheetParamsInfo));
        }
        
        /// <summary>
        /// Get time sheet params by type
        /// </summary>
        /// <param name="timeSheetParamType">string timeSheetParamType</param>
        /// <returns></returns>
        public List<HRTimeSheetParamsInfo> GetTimeSheetParamsByTimeSheetType(string timeSheetParamType)
        {
            DataSet ds = dal.GetDataSet("HRTimeSheetParams_GetTimeSheetParamList", timeSheetParamType);
            return (List<HRTimeSheetParamsInfo>)GetListFromDataSet(ds);
        }

        /// <summary>
        /// Get time sheet param list based on some criteria
        /// </summary>
        /// <returns>List of params</returns>
        public List<HRTimeSheetParamsInfo> GetTimeSheetParamsList(string paramType)
        {
            DataSet ds = dal.GetDataSet("HRTimeSheetParams_GetTimeSheetParamList", paramType);
            return (List<HRTimeSheetParamsInfo>)GetListFromDataSet(ds);
        }

        public List<HRTimeSheetParamsInfo> GetTimeSheetParamsList()
        {
            DataSet ds = dal.GetAllObject();
            return (List<HRTimeSheetParamsInfo>)GetListFromDataSet(ds);
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<HRTimeSheetParamsInfo> timeSheetParamList = new List<HRTimeSheetParamsInfo>();
            if (ds.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    HRTimeSheetParamsInfo objTimeSheetParamsInfo = (HRTimeSheetParamsInfo)GetObjectFromDataRow(row);
                    timeSheetParamList.Add(objTimeSheetParamsInfo);
                }
            }
            return timeSheetParamList;
        }
    }
    #endregion
}