using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ARDeliveryItemComponents
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARDeliveryItemComponentsController
    //Created Date:Wednesday, July 24, 2013
    //-----------------------------------------------------------

    public class ARDeliveryItemComponentsController : BaseBusinessController
    {
        public ARDeliveryItemComponentsController()
        {
            dal = new DALBaseProvider("ARDeliveryItemComponents", typeof(ARDeliveryItemComponentsInfo));
        }
    }
    #endregion
}