using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region METimeFrames
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:METimeFramesInfo
    //Created Date:Monday, April 11, 2011
    //-----------------------------------------------------------

    public class METimeFramesInfo : BusinessObject
    {
        public METimeFramesInfo()
        {
        }
        #region Variables
        protected int _mETimeFrameID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _mETimeFrameStartTime = DateTime.MaxValue;
        protected DateTime _mETimeFrameEndTime = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int METimeFrameID
        {
            get { return _mETimeFrameID; }
            set
            {
                if (value != this._mETimeFrameID)
                {
                    _mETimeFrameID = value;
                    NotifyChanged("METimeFrameID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime METimeFrameStartTime
        {
            get { return _mETimeFrameStartTime; }
            set
            {
                if (value != this._mETimeFrameStartTime)
                {
                    _mETimeFrameStartTime = value;
                    NotifyChanged("METimeFrameStartTime");
                }
            }
        }
        public DateTime METimeFrameEndTime
        {
            get { return _mETimeFrameEndTime; }
            set
            {
                if (value != this._mETimeFrameEndTime)
                {
                    _mETimeFrameEndTime = value;
                    NotifyChanged("METimeFrameEndTime");
                }
            }
        }
        #endregion
    }
    #endregion
}