using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ACAssetShipmentItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACAssetShipmentItemsInfo
    //Created Date:05 May 2012
    //-----------------------------------------------------------

    public class ACAssetShipmentItemsInfo : BusinessObject
    {
        public ACAssetShipmentItemsInfo()
        {
        }
        #region Variables
        protected int _aCAssetShipmentItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ACDocumentID;
        protected int _fK_ACAssetID;
        protected int _fK_HRDepartmentRoomID;
        protected double _aCAssetShipmentItemQty;
        protected double _aCAssetShipmentItemDepreciatedAmount;
        #endregion

        #region Public properties
        public int ACAssetShipmentItemID
        {
            get { return _aCAssetShipmentItemID; }
            set
            {
                if (value != this._aCAssetShipmentItemID)
                {
                    _aCAssetShipmentItemID = value;
                    NotifyChanged("ACAssetShipmentItemID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ACDocumentID
        {
            get { return _fK_ACDocumentID; }
            set
            {
                if (value != this._fK_ACDocumentID)
                {
                    _fK_ACDocumentID = value;
                    NotifyChanged("FK_ACDocumentID");
                }
            }
        }
        public int FK_ACAssetID
        {
            get { return _fK_ACAssetID; }
            set
            {
                if (value != this._fK_ACAssetID)
                {
                    _fK_ACAssetID = value;
                    NotifyChanged("FK_ACAssetID");
                }
            }
        }
        public int FK_HRDepartmentRoomID
        {
            get { return _fK_HRDepartmentRoomID; }
            set
            {
                if (value != this._fK_HRDepartmentRoomID)
                {
                    _fK_HRDepartmentRoomID = value;
                    NotifyChanged("FK_HRDepartmentRoomID");
                }
            }
        }
        public double ACAssetShipmentItemQty
        {
            get { return _aCAssetShipmentItemQty; }
            set
            {
                if (value != this._aCAssetShipmentItemQty)
                {
                    _aCAssetShipmentItemQty = value;
                    NotifyChanged("ACAssetShipmentItemQty");
                }
            }
        }
        public double ACAssetShipmentItemDepreciatedAmount
        {
            get { return _aCAssetShipmentItemDepreciatedAmount; }
            set
            {
                if (value != this._aCAssetShipmentItemDepreciatedAmount)
                {
                    _aCAssetShipmentItemDepreciatedAmount = value;
                    NotifyChanged("ACAssetShipmentItemDepreciatedAmount");
                }
            }
        }
        #endregion


        #region Extra Properties
        public string ACAssetNo { get; set; }

        public string ACAssetName { get; set; }

        public double AssetReceiptedQty { get; set; }

        public double AssetShippedQty { get; set; }        

        public double ACAssetInitQty { get; set; }
        
        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double ACAssetOriginalAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double ACAssetRemainedAmount { get; set; }

        public string ACDocumentNo { get; set; }

        public DateTime ACDocumentDate { get; set; }

        public string ACDocumentDesc { get; set; }

        public string ICMeasureUnitName { get; set; }

        public string HRDepartmentRoomName { get; set; }

        public int FK_ACAccountID { get; set; }

        public int FK_ACDepreciationAccountID { get; set; }

        #endregion
    }
    #endregion
}