ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_FK_HREmployeeClosedID
  DEFAULT 0 FOR [FK_HREmployeeClosedID];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrDateIn
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrDateIn];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrDateOut
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrDateOut];
GO
ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaDate1
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrMetaDate1];
GO
ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaDate2
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrMetaDate2];
GO
ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaDate3
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrMetaDate3];
GO
ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaDate4
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrMetaDate4];
GO
ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaDate5
  DEFAULT ('9999-12-31 23:59:59.997') FOR [MEEmrMetaDate5];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaNum1
  DEFAULT 0 FOR [MEEmrMetaNum1];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaNum2
  DEFAULT 0 FOR [MEEmrMetaNum2];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaNum3
  DEFAULT 0 FOR [MEEmrMetaNum3];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaNum4
  DEFAULT 0 FOR [MEEmrMetaNum4];
GO

ALTER TABLE dbo.[MEEmrs]
  ADD CONSTRAINT MEEmrs_DF_MEEmrMetaNum5
  DEFAULT 0 FOR [MEEmrMetaNum5];
GO

