using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ARSaleReturnItemComponents
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARSaleReturnItemComponentsController
    //Created Date:18 June 2012
    //-----------------------------------------------------------

    public class ARSaleReturnItemComponentsController : BaseBusinessController
    {
        public ARSaleReturnItemComponentsController()
        {
            dal = new DALBaseProvider("ARSaleReturnItemComponents", typeof(ARSaleReturnItemComponentsInfo));
        }

        /// <summary>
        /// Get component list of an item
        /// </summary>
        /// <param name="saleReturnItemID">Sale return item id</param>
        /// <returns>List of components</returns>
        public List<ARSaleReturnItemComponentsInfo> GetComponentsByItemID(int saleReturnItemID)
        {
            DataSet ds = dal.GetDataSet("ARSaleReturnItemComponents_GetComponentsByItemID", saleReturnItemID);
            return (List<ARSaleReturnItemComponentsInfo>)GetListFromDataSet(ds);
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<ARSaleReturnItemComponentsInfo> components = new List<ARSaleReturnItemComponentsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ARSaleReturnItemComponentsInfo component = (ARSaleReturnItemComponentsInfo)GetObjectFromDataRow(row);
                    components.Add(component);
                }
            }
            return components;
        }
    }
    #endregion
}