using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region MELabServers
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MELabServersController
    //Created Date:15 April 2014
    //-----------------------------------------------------------

    public class MELabServersController : BaseBusinessController
    {
        public MELabServersController()
        {
            dal = new DALBaseProvider("MELabServers", typeof(MELabServersInfo));
        }
        public Boolean LabServerInsertPatient(string sID, string STT, DateTime LAbDate,string PatientName, int YearOfBirth, string Gender )
        {

            //DbCommand cmd = database.GetStoredProcCommand("sp_HIS_InsertPatient", sID, STT, LAbDate, PatientName, YearOfBirth, Gender);
            //database.ExecuteNonQuery(cmd);
            //dal.ExecuteStoredProcedure
            dal.ExecuteStoredProcedure("sp_HIS_InsertPatient", sID, STT, LAbDate, PatientName, YearOfBirth, Gender);
             
            return true;
        }
        public Boolean LabServerInsertOrder(string sID, string LabNo, string LabName)
        {
            dal.ExecuteStoredProcedure("sp_HIS_InsertOrder", sID, LabNo, LabName);
            return true;
        }

        
    }
    #endregion
}