using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;
using System.Linq;

namespace BOSERP
{
	#region MEParamReportRelations
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MEParamReportRelationsController
	//Created Date:Tuesday, August 24, 2021
	//-----------------------------------------------------------

	public class MEParamReportRelationsController : BaseBusinessController
	{
		public MEParamReportRelationsController()
		{
			dal = new DALBaseProvider("MEParamReportRelations", typeof(MEParamReportRelationsInfo));
		}

		public MEParamReportRelationsInfo GetObjectByParamAndEmrType(int paramId, int emrTypeId)
		{
			return GetListBusinessObjects<MEParamReportRelationsInfo>(
				dal.GetDataSet($"SELECT TOP 1 * FROM [MEParamReportRelations] WHERE AAStatus = 'Alive' AND [FK_MEParamID] = {paramId} and [FK_MEEmrTypeID] = {emrTypeId}")
				).FirstOrDefault();
		}
		public MEParamReportRelationsInfo GetObjectByParamCodeAndEmrType(string paramCode, int emrTypeId)
		{
			return GetListBusinessObjects<MEParamReportRelationsInfo>(
				dal.GetDataSet("MEParamReportRelation_GetObjectByParamCodeAndType", paramCode, emrTypeId)
				).FirstOrDefault();
		}
	}
	#endregion
}