using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region MEReportBHYT917s
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MEReportBHYT917sController
	//Created Date:Thursday, July 20, 2017
	//-----------------------------------------------------------
	
	public class MEReportBHYT917sController:BaseBusinessController
	{
		public MEReportBHYT917sController()
		{
			dal= new DALBaseProvider("MEReportBHYT917s",typeof(MEReportBHYT917sInfo));
		}
	}
	#endregion
}