using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;
using System.Linq;

namespace BOSERP
{
    #region MEEmrTypeTemplates
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEEmrTypeTemplatesController
    //Created Date:Tuesday, November 21, 2017
    //-----------------------------------------------------------

    public class MEEmrTypeTemplatesController : BaseBusinessController
    {
        public MEEmrTypeTemplatesController()
        {
            dal = new DALBaseProvider("MEEmrTypeTemplates", typeof(MEEmrTypeTemplatesInfo));
        }
        public List<MEEmrTypeTemplatesInfo> GetAllByEmrTypeID(int typeID)
        {
            var ds = dal.GetAllDataByForeignColumn("FK_MEEmrTypeID", typeID);
            var businessObjectList = new List<MEEmrTypeTemplatesInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objBusinessObject = (MEEmrTypeTemplatesInfo)SqlDatabaseHelper.GetObjectFromDataRow(row, dal.ObjectType);
                    businessObjectList.Add(objBusinessObject);
                }
            }
            return businessObjectList;
        }
        public List<MEEmrTypeTemplatesInfo> GetAll()
        {
            return GetListBusinessObjects<MEEmrTypeTemplatesInfo>(GetAllObjects());
        }
        public MEEmrTypeTemplatesInfo GetObjectByTypeAndTemplateIndex(int fK_MEEmrTypeID, int fK_METemplateID)
        {
            return base.GetDataObject("MEEmrTypeTemplates_GetObjectByTypeAndTemplate", fK_MEEmrTypeID, fK_METemplateID) as MEEmrTypeTemplatesInfo;
        }
        
    }
    #endregion
}