using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region MEEmrTemplateActions
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEEmrTemplateActionsController
    //Created Date:Monday, November 20, 2017
    //-----------------------------------------------------------

    public class MEEmrTemplateActionsController : BaseBusinessController
    {
        public MEEmrTemplateActionsController()
        {
            dal = new DALBaseProvider("MEEmrTemplateActions", typeof(MEEmrTemplateActionsInfo));
        }
        public List<MEEmrTemplateActionsInfo> GetAllByTemplateID(int templateID)
        {
            var ds = dal.GetAllDataByForeignColumn("FK_METemplateID", templateID);
            var businessObjectList = new List<MEEmrTemplateActionsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objBusinessObject = (MEEmrTemplateActionsInfo)SqlDatabaseHelper.GetObjectFromDataRow(row, dal.ObjectType);
                    businessObjectList.Add(objBusinessObject);
                }
            }
            return businessObjectList;
        }
        public List<MEEmrTemplateActionsInfo> GetAllByTemplateIdAndWhen(int templateID, string when)
        {
            return GetListBusinessObjects<MEEmrTemplateActionsInfo>(
                GetDataSet("SELECT * FROM [MEEmrTemplateActions] " +
                "WHERE [AAStatus]='Alive' " +
                $"AND [FK_METemplateID] = {templateID}" +
                $"AND [MEEmrTemplateActionWhen] = '{when}'")
            );
        }
    }
    #endregion
}