using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using BOSCommon;
using BOSLib;
using BOSERP;

namespace BOSERP
{

    #region ICProducts

    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICProductsController
    //Created Date:Friday, March 21, 2008
    //-----------------------------------------------------------

    public class ICProductsController : BaseBusinessController
    {
        public ICProductsController()
        {
            dal = new DALBaseProvider("ICProducts", typeof(ICProductsInfo));
        }

        public DataSet GetProductsByCreatedDate(DateTime dtDateFrom, DateTime dtDateTo)
        {
            return dal.GetDataSet("ICProducts_SelectByCreatedDate", dtDateFrom, dtDateTo);
        }

        public ICProductsInfo GetProductByProductBarCode(string productBarCode)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductByProductBarCode", productBarCode);
            if (ds.Tables.Count > 0)
                return (ICProductsInfo) dal.GetSingleObject(ds.Tables[0]);
            return null;
        }

        /// <summary>
        ///     Get the product list by medicine name
        /// </summary>
        /// <param name="medicineName"></param>
        /// <returns></returns>
        public DataSet GetProductListByMedicineComponentNameOrMedicineName(string componentNameOrMedicineName,
            int stockID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListByMedicineComponentNameOrMedicineName",
                componentNameOrMedicineName, stockID);
            return ds;
        }

        public DataSet GetProductListByMedicineComponentNameOrMedicineName(string componentNameOrMedicineName)
        {
            var ds = dal.GetDataSet(
                "ICProducts_GetProductListByMedicineComponentNameOrMedicineNameNoCountByStockID",
                componentNameOrMedicineName);
            return ds;
        }

        /// <summary>
        ///     Override to call custom SP
        /// </summary>
        /// <param name="iObjectID"></param>
        /// <returns></returns>
        public override object GetObjectByID(int iObjectID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductByID", iObjectID);
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objProductsInfo;
            }
            return null;
        }

        /// <summary>
        ///     Get a product and its inventory by ProductID and StockID
        /// </summary>
        /// <param name="productID"></param>
        /// <param name="stockID"></param>
        /// <returns></returns>
        public ICProductsInfo GetProductByIDAndStockID(int productID, int stockID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductByIDAndStockID", productID, stockID);
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objProductsInfo;
            }
            return null;
        }

        /// <summary>
        ///     Get a product and its inventory by ProductID
        /// </summary>
        /// <param name="productID">The product id</param>
        /// <returns>Info of product</returns>
        public ICProductsInfo GetInventoryProductByProductID(int productID)
        {
            var ds = dal.GetDataSet("ICProducts_GetInventoryProductByProductID", productID);
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objProductsInfo;
            }
            return null;
        }

        /// <summary>
        ///     Get the product list by type
        /// </summary>
        /// <param name="productType"></param>
        /// <returns></returns>
        public DataSet GetProductsByType(string productType)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductsByType", productType);
            return ds;
        }

        /// <summary>
        ///     Get product by history detail id
        /// </summary>
        /// <param name="historyDetailID">The history detail id</param>
        /// <returns>Info of product</returns>
        public ICProductsInfo GetProductByHistoryDetailID(int historyDetailID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductByHistoryDetailID", historyDetailID);
            if (ds.Tables[0].Rows.Count > 0)
            {
                var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objProductsInfo;
            }
            return null;
        }

        /// <summary>
        ///     Get a product by its id
        /// </summary>
        /// <param name="productID">Product id</param>
        /// <returns>Product object</returns>
        public ICProductsInfo GetProductByID(int productID)
        {
            return (ICProductsInfo) dal.GetDataObject("ICProducts_GetProductByID", productID);
        }

        /// <summary>
        ///     Get the product list based on some criteria
        /// </summary>
        /// <param name="productNo">Product no</param>
        /// <param name="productSupplierNo">Product supplier no</param>
        /// <param name="productType">Product type</param>
        /// <param name="productDesc">Product desc</param>
        /// <param name="departmentID">Department id</param>
        /// <param name="productGroupID">Product group id</param>
        /// <param name="supplierID">Supplier id</param>
        /// <returns>List of products</returns>
        public DataSet GetProductSet(string productNo,
            string productSupplierNo,
            string productType,
            string productDesc,
            int? departmentID,
            int? productGroupID,
            int? supplierID)
        {
            return dal.GetDataSet("ICProducts_GetProductList",
                productNo,
                productSupplierNo,
                productType,
                productDesc,
                departmentID,
                productGroupID,
                supplierID);
        }

        /// <summary>
        ///     Get list Product to print Barcode
        /// </summary>
        /// <param name="productBarCode"> Product BarCode</param>
        /// <param name="productNo">Product No</param>
        /// <param name="productName">Product Name</param>
        /// <param name="productGroupID">Product Group ID</param>
        /// <param name="stockID">stock ID</param>
        /// <param name="createdDateFrom">CreatedDate From</param>
        /// <param name="createdDateTo">CreatedDate  To</param>
        /// <returns></returns>
        public DataSet GetBarcodeProductSet(string productBarCode, string productNo, string productSupplierNumber,
            string productDesc, int? productGroupID,
            int? productOriginID, DateTime? createdDateFrom, DateTime? createdDateTo)
        {
            return dal.GetDataSet("ICProducts_GetBarcodeProductList",
                productBarCode,
                productNo,
                productSupplierNumber,
                productDesc,
                productGroupID,
                productOriginID,
                createdDateFrom,
                createdDateTo);
        }

        /// <summary>
        ///     Get list Product Active to print Barcode
        /// </summary>
        /// <param name="productBarCode"> Product BarCode</param>
        /// <param name="productNo">Product No</param>
        /// <param name="productName">Product Name</param>
        /// <param name="productGroupName">Product Group Name</param>
        /// <param name="stockID">stock ID</param>
        /// <param name="createdDateFrom">CreatedDate From</param>
        /// <param name="createdDateTo">CreatedDate  To</param>
        /// <returns></returns>
        public DataSet GetBarcodeProductActiveSet(string productBarCode, string productNo, string productSupplierNumber,
            string productDesc, int? productGroupID,
            int? stockID, int? productOriginID, DateTime? createdDateFrom, DateTime? createdDateTo)
        {
            return dal.GetDataSet("ICProducts_GetBarcodeProductActiveList",
                productBarCode,
                productNo,
                productSupplierNumber,
                productDesc,
                productGroupID,
                stockID,
                productOriginID,
                createdDateFrom,
                createdDateTo);
        }

        /// <summary>
        ///     Get the product list based on some criteria
        /// </summary>
        /// <param name="departmentID">Department id</param>
        /// <param name="productGroupID">Product group id</param>
        /// <param name="supplierID">Supplier id</param>
        /// <returns>List of products</returns>
        public List<ICProductsInfo> GetProductList(int? departmentID, int? productGroupID, int? supplierID)
        {
            var ds = GetProductSet(null, null, null, null, departmentID, productGroupID, supplierID);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductListActive()
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListActive");
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductListActiveByCompanyIDAndInsLevelID(int companyID, int insLevelID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListActiveByCompanyIDAndInsLevelID", companyID, insLevelID);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductListDrugsActive()
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListDrugsActive");
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        /// <summary>
        ///     Get all products
        /// </summary>
        /// <returns>List of products</returns>
        public List<ICProductsInfo> GetAllProducts()
        {
            return GetProductList(null, null, null);
        }

        public DataSet GetProductList(int? departmentID, int? productGroupID, int? supplierID, int? stockID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductList2", departmentID, productGroupID, supplierID, stockID);
            return ds;
        }

        /// <summary>
        ///     ICProducts_GetAllProductListNoCountIDStock
        /// </summary>
        /// <param name="departmentID"></param>
        /// <param name="productGroupID"></param>
        /// <param name="supplierID"></param>
        /// <param name="stockID"></param>
        /// <returns></returns>
        public DataSet GetAllProductListNoCountIDStock(int? departmentID, int? productGroupID, int? supplierID)
        {
            var ds = dal.GetDataSet("ICProducts_GetAllProductListNoCountIDStock", departmentID, productGroupID,
                supplierID);
            return ds;
        }

        public DataSet GetAllProductListNoCountIDStockByStockId(int? departmentID, int? productGroupID, int? supplierID,
            int stockId)
        {
            var ds = dal.GetDataSet("ICProducts_GetAllProductListNoCountIDStockByStockId", departmentID, productGroupID,
                supplierID, stockId);
            return ds;
        }

        public List<ICProductsInfo> GetProductListMedicineNoStock(int? departmentID, int? productGroupID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListMedicineNoStock", departmentID, productGroupID);
            return ds.Tables.Count==0 ? new List<ICProductsInfo>() : (from DataRow dataRow in ds.Tables[0].Rows select (ICProductsInfo) GetObjectFromDataRow(dataRow)).ToList();
        }

        public DataSet GetAllProductListNoCountIDStockAndCompanyIDAndInsLevelID(int? departmentID, int? productGroupID,
            int? supplierID, int companyID, int insLevelID)
        {
            var ds = dal.GetDataSet("ICProducts_GetAllProductListNoCountIDStockAndCompanyIDAndInsLevelID",
                departmentID, productGroupID, supplierID, companyID, insLevelID);
            return ds;
        }

        public DataSet GetAllProductListNoCountIDStockAndCompanyIDAndInsLevelIDByStockId(int? departmentID, int? productGroupID,
            int? supplierID, int companyID, int insLevelID, int stockId)
        {
            var ds = dal.GetDataSet("ICProducts_GetAllProductListNoCountIDStockAndCompanyIDAndInsLevelIDByStockId",
                departmentID, productGroupID, supplierID, companyID, insLevelID, stockId);
            return ds;
        }

        /// <summary>
        ///     Get all products
        /// </summary>
        /// <returns>List of products</returns>
        public DataSet GetAllProductSet()
        {
            var ds = GetProductSet(null, null, null, null, null, null, null);
            return ds;
        }

        /// <summary>
        ///     Get an equipment and its inventory in a room
        /// </summary>
        /// <param name="equipmentID">Equipment id</param>
        /// <param name="serieID">Serie id</param>
        /// <param name="roomID">Room id</param>
        /// <returns>Equipment object</returns>
        public ICProductsInfo GetEquipmentByEquipmentIDAndSerieIDAndRoomID(int equipmentID, int serieID, int roomID)
        {
            return
                (ICProductsInfo)
                dal.GetDataObject("ICProducts_GetEquipmentByEquipmentIDAndSerieIDAndRoomID", equipmentID, serieID,
                    roomID);
        }

        /// <summary>
        ///     Get an equipment by its id
        /// </summary>
        /// <param name="equipmentID">Equipment id</param>
        /// <returns>Equipment object</returns>
        public ICProductsInfo GetEquipmentByID(int equipmentID)
        {
            return (ICProductsInfo) dal.GetDataObject("ICProducts_GetEquipmentByID", equipmentID);
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            var products = new List<ICProductsInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(row);
                    products.Add(objProductsInfo);
                }
            return products;
        }

        /// <summary>
        ///     Get equipment list based on some criteria
        /// </summary>
        /// <param name="equipmentNo">Equipment no</param>
        /// <param name="equipmentName">Equipment name</param>
        /// <returns>List of equipments</returns>
        public List<ICProductsInfo> GetEquipmentList(string equipmentNo, string equipmentName)
        {
            var ds = dal.GetDataSet("ICProducts_GetEquipmentList", equipmentNo, equipmentName);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        /// <summary>
        ///     Get all equipments
        /// </summary>
        /// <returns>List of equipments</returns>
        public List<ICProductsInfo> GetAllEquipments()
        {
            return GetEquipmentList(null, null);
        }

        /// <summary>
        ///     Get product list for exporting
        /// </summary>
        /// <returns>List of products</returns>
        public DataSet GetProductsForExporting()
        {
            var ds = dal.GetDataSet("ICProducts_GetProductsForExporting");
            return ds;
        }

        /// <summary>
        ///     Get the search product list for barcode print
        /// </summary>
        /// <param name="departmentID">Department id</param>
        /// <param name="productGroupID">Product group id</param>
        /// <param name="supplierID">Supplier id</param>
        /// <returns>List of products</returns>
        public List<ICProductsInfo> GetBarcodeProductList(string productBarCode, string productNo,
            string productSupplierNumber, string productDesc, int? productGroupID,
            int? productOriginID, DateTime? createdDateFrom, DateTime? createdDateTo)
        {
            var ds = GetBarcodeProductSet(productBarCode, productNo, productSupplierNumber, productDesc,
                productGroupID, productOriginID, createdDateFrom, createdDateTo);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        /// <summary>
        ///     Get the search product active list for barcode print
        /// </summary>
        /// <param name="departmentID">Department id</param>
        /// <param name="productGroupID">Product group id</param>
        /// <param name="supplierID">Supplier id</param>
        /// <returns>List of products</returns>
        public List<ICProductsInfo> GetBarcodeProductActiveList(string productBarCode, string productNo,
            string productSupplierNumber, string productDesc, int? productGroupID,
            int? stockID, int? productOriginID, DateTime? createdDateFrom, DateTime? createdDateTo)
        {
            var ds = GetBarcodeProductActiveSet(productBarCode, productNo, productSupplierNumber, productDesc,
                productGroupID, stockID, productOriginID, createdDateFrom, createdDateTo);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        /// <summary>
        ///     Get product list by product no
        /// </summary>
        /// <param name="productNo"></param>
        /// <returns></returns>
        public List<ICProductsInfo> GetProductListByProductNo(string productNo)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListByProductNo", productNo);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetSameProductListByProductNo(string productNo)
        {
            var ds = dal.GetDataSet("ICProducts_GetSameProductListByProductNo", productNo);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        /// <summary>
        ///     Get the product list and their inventory based on some criteria
        /// </summary>
        /// <param name="departmentID"></param>
        /// <param name="productGroupID"></param>
        /// <param name="supplierID"></param>
        /// <param name="stockID"></param>
        /// <returns>List of products</returns>
        public List<ICProductsInfo> GetProductList_2(int? departmentID, int? productGroupID, int? supplierID,
            int? stockID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductList2", departmentID, productGroupID, supplierID, stockID);
            var productList = new List<ICProductsInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(row);
                    productList.Add(objProductsInfo);
                }
            return productList;
        }

        public List<ICProductsInfo> AppendComponentNameForProductAndRemoveZeroInventoryStockQuantity(DataSet dsProduct)
        {
            var productList = new List<ICProductsInfo>();
            var objMedicineComponentsController = new MEMedicineComponentsController();
            if (dsProduct.Tables.Count > 0)
                foreach (DataRow row in dsProduct.Tables[0].Rows)
                {
                    var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(row);
                    if (objProductsInfo.ICInventoryStockQuantity >= 0)
                    {
                        //Get component name                        
                        var medicineComponentList =
                            objMedicineComponentsController.GetMedicineComponentListByProductID(
                                objProductsInfo.ICProductID);
                        if (medicineComponentList.Count > 0)
                        {
                            var medicineComponent = "";
                            foreach (var objMedicineComponentsInfo in medicineComponentList)
                                medicineComponent = medicineComponent + objMedicineComponentsInfo.MEComponentName + ", ";
                            medicineComponent = medicineComponent.Substring(0, medicineComponent.Length - 2);
                            objProductsInfo.MEComponentName = medicineComponent;
                        }
                        else
                        {
                            objProductsInfo.MEComponentName = "";
                        }
                        if (objProductsInfo.ICProductType == ProductType.Medicine.ToString())
                            productList.Add(objProductsInfo);
                    }
                }
            return productList;
        }

        /// <summary>
        ///     UtHV
        ///     10022017
        ///     Khong cho bs search cac thuoc co trang thai khong hoat dong
        /// </summary>
        /// <param name="dsProduct"></param>
        /// <returns></returns>
        public List<ICProductsInfo>
            AppendComponentNameForProductAndRemoveZeroInventoryStockQuantityAndRemoveInactiveProducts(DataSet dsProduct, int stockID)
        {
            var productList = new List<ICProductsInfo>();
            var objMedicineComponentsController = new MEMedicineComponentsController();
            if (dsProduct.Tables.Count > 0)
                foreach (DataRow row in dsProduct.Tables[0].Rows)
                {
                    var objProductsInfo = (ICProductsInfo) GetObjectFromDataRow(row);

                    //Khong cho bs search cac thuoc co trang thai khong hoat dong
                    if (objProductsInfo.ICProductActiveCheck == false)
                        continue;

                    if (objProductsInfo.ICInventoryStockQuantity > 0)
                    {
                        //Get component name                        
                        var medicineComponentList =
                            objMedicineComponentsController.GetMedicineComponentListByProductID(
                                objProductsInfo.ICProductID);
                        if (medicineComponentList.Count > 0)
                        {
                            var medicineComponent = "";
                            foreach (var objMedicineComponentsInfo in medicineComponentList)
                                medicineComponent = medicineComponent + objMedicineComponentsInfo.MEComponentName + ", ";
                            medicineComponent = medicineComponent.Substring(0, medicineComponent.Length - 2);
                            objProductsInfo.MEComponentName = medicineComponent;
                        }
                        else
                        {
                            objProductsInfo.MEComponentName = "";
                        }

                        //DDCan [ADD] [25/07/2017] [Quatity can sale], START
                        int saleOrderStockID = 0;
                        ICStocksController objStocksController = new ICStocksController();
                        saleOrderStockID = objStocksController.GetStockBySaleStockID(stockID, StockType.SaleOrder.ToString()).ICStockID;

                        ICInventoryStocksController objInventoryStocksController = new ICInventoryStocksController();
                        //double saleQuantity = objInventoryStocksController.GetStockQuantityByProductAndStock(objProductsInfo.ICProductID, saleOrderStockID);
                        //objProductsInfo.ICInventoryStockQuantity = objProductsInfo.ICInventoryStockQuantity - saleQuantity;
                        //DDCan [ADD] [25/07/2017] [Quatity can sale], END

                        //DDCan [MOD] [25/07/2017] [Quatity can sale], START
                        //if (objProductsInfo.ICProductType == ProductType.Medicine.ToString())
                        //    productList.Add(objProductsInfo);
                        if (objProductsInfo.ICProductType == ProductType.Medicine.ToString() && objProductsInfo.ICInventoryStockQuantity >= 0)
                            productList.Add(objProductsInfo);
                        //DDCan [MOD] [25/07/2017] [Quatity can sale], END
                    }
                }
            return productList;
        }

        public List<ICProductsInfo> GetProductListByProductSubType(string productSubType)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListByProductSubType", productSubType);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductListByCompanyID(int companyID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductListByCompanyID", companyID);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductByCompanyIDAndInsLevelIDAndProductGroupID(int companyID, int insLevelID,
            int productGroupID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductByCompanyIDAndInsLevelIDAndProductGroupID", companyID,
                insLevelID, productGroupID);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public List<ICProductsInfo> GetProductsByTypeAndCompanyIDAndInsLevelID(string productType, int companyID,
            int insLevelID)
        {
            var ds = dal.GetDataSet("ICProducts_GetProductsByTypeAndCompanyIDAndInsLevelID", productType, companyID,
                insLevelID);
            return (List<ICProductsInfo>) GetListFromDataSet(ds);
        }

        public DataSet GetProductsForLookupEdit()
        {
            return dal.GetDataSet("ICProducts_GetProductsForLookupEdit");
        }
    }

    #endregion
}