using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ARCreditNoteInvoices
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARCreditNoteInvoicesController
    //Created Date:Wednesday, November 12, 2008
    //-----------------------------------------------------------

    public class ARCreditNoteInvoicesController : BaseBusinessController
    {
        public ARCreditNoteInvoicesController()
        {
            dal = new DALBaseProvider("ARCreditNoteInvoices", typeof(ARCreditNoteInvoicesInfo));
        }
    }
    #endregion
}