using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region CSCompanys
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:CSCompanysController
	//Created Date:Sunday, June 22, 2008
	//-----------------------------------------------------------
	
	public class CSCompanysController:BaseBusinessController
	{
		public CSCompanysController()
		{
			dal= new DALBaseProvider("CSCompanys",typeof(CSCompanysInfo));
		}        
    }
	#endregion
}