using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region ADCriterias
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:ADCriteriasController
	//Created Date:Thursday, May 20, 2010
	//-----------------------------------------------------------
	
	public class ADCriteriasController:BaseBusinessController
	{
		public ADCriteriasController()
		{
			dal= new DALBaseProvider("ADCriterias",typeof(ADCriteriasInfo));
		}
        public List<ADCriteriasInfo> GetAllObjectByModuleAndUser(int iModuleID, int iUserID)
        {
            String strQuery = String.Format("SELECT * FROM ADCriterias WHERE FK_STModuleID={0} AND FK_ADUserID ={1} AND AAStatus ='Alive'",iModuleID,iUserID);
            DataSet ds = dal.GetDataSet(strQuery);
            List<ADCriteriasInfo> result = new List<ADCriteriasInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ADCriteriasInfo objCriteriasInfo = (ADCriteriasInfo)GetObjectFromDataRow(row);
                    result.Add(objCriteriasInfo);
                }
            }
            return result;
        }
        public bool IsExistCriteriaName(String strCriteriaName, int iModuleID, int iUserID)
        {
            String strQuery = String.Format("SELECT * FROM ADCriterias WHERE ADCriteriaName='{0}' AND FK_STModuleID={1} AND FK_ADUserID ={2} AND AAStatus ='Alive'",strCriteriaName, iModuleID, iUserID);
            DataSet dsCriterias =dal.GetDataSet(strQuery);
                if(dsCriterias!=null)
                {
                    if(dsCriterias.Tables[0].Rows.Count>0)
                        return true;
                }
                return false;   
        }
	}
	#endregion
}