using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEInteractingMedicines
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEInteractingMedicinesInfo
    //Created Date:Sunday, October 02, 2011
    //-----------------------------------------------------------

    public class MEInteractingMedicinesInfo : BusinessObject
    {
        public MEInteractingMedicinesInfo()
        {
        }
        #region Variables
        protected int _mEInteractingMedicineID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICProductID;
        protected int _fK_ICInteractingProductID;
        protected String _mEInteractingMedicineDesc = String.Empty;
        #endregion

        #region Public properties
        public int MEInteractingMedicineID
        {
            get { return _mEInteractingMedicineID; }
            set
            {
                if (value != this._mEInteractingMedicineID)
                {
                    _mEInteractingMedicineID = value;
                    NotifyChanged("MEInteractingMedicineID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICInteractingProductID
        {
            get { return _fK_ICInteractingProductID; }
            set
            {
                if (value != this._fK_ICInteractingProductID)
                {
                    _fK_ICInteractingProductID = value;
                    NotifyChanged("FK_ICInteractingProductID");
                }
            }
        }
        public String MEInteractingMedicineDesc
        {
            get { return _mEInteractingMedicineDesc; }
            set
            {
                if (value != this._mEInteractingMedicineDesc)
                {
                    _mEInteractingMedicineDesc = value;
                    NotifyChanged("MEInteractingMedicineDesc");
                }
            }
        }
        #endregion

        #region Extra Properties
        public string ICProductName { get; set; }
        public string ICInteractingProductName { get; set; }
        #endregion
    }
    #endregion
}