using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ARDocumentPayments
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARDocumentPaymentsInfo
    //Created Date:Monday, May 10, 2010
    //-----------------------------------------------------------

    public class ARDocumentPaymentsInfo : BusinessObject
    {
        public ARDocumentPaymentsInfo()
        {
        }

        #region Variables
        protected int _aRDocumentPaymentID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_AROpenDocumentID;
        protected int _fK_ARCustomerPaymentID;
        protected DateTime _aRDocumentPaymentDate = DateTime.MaxValue;
        protected double _aRDocumentPaymentAmount;
        protected double _aRDocumentPaymentExchangeRate;
        #endregion

        #region Public properties
        public int ARDocumentPaymentID
        {
            get { return _aRDocumentPaymentID; }
            set
            {
                if (value != this._aRDocumentPaymentID)
                {
                    _aRDocumentPaymentID = value;
                    NotifyChanged("ARDocumentPaymentID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_AROpenDocumentID
        {
            get { return _fK_AROpenDocumentID; }
            set
            {
                if (value != this._fK_AROpenDocumentID)
                {
                    _fK_AROpenDocumentID = value;
                    NotifyChanged("FK_AROpenDocumentID");
                }
            }
        }
        public int FK_ARCustomerPaymentID
        {
            get { return _fK_ARCustomerPaymentID; }
            set
            {
                if (value != this._fK_ARCustomerPaymentID)
                {
                    _fK_ARCustomerPaymentID = value;
                    NotifyChanged("FK_ARCustomerPaymentID");
                }
            }
        }
        public DateTime ARDocumentPaymentDate
        {
            get { return _aRDocumentPaymentDate; }
            set
            {
                if (value != this._aRDocumentPaymentDate)
                {
                    _aRDocumentPaymentDate = value;
                    NotifyChanged("ARDocumentPaymentDate");
                }
            }
        }
        public double ARDocumentPaymentAmount
        {
            get { return _aRDocumentPaymentAmount; }
            set
            {
                if (value != this._aRDocumentPaymentAmount)
                {
                    _aRDocumentPaymentAmount = value;
                    NotifyChanged("ARDocumentPaymentAmount");
                }
            }
        }
        public double ARDocumentPaymentExchangeRate
        {
            get { return _aRDocumentPaymentExchangeRate; }
            set
            {
                if (value != this._aRDocumentPaymentExchangeRate)
                {
                    _aRDocumentPaymentExchangeRate = value;
                    NotifyChanged("ARDocumentPaymentExchangeRate");
                }
            }
        }
        #endregion

        #region Extra properties
        public string AROpenDocumentNo { get; set; }

        public DateTime AROpenDocumentDate { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double AROpenDocumentBalanceDue { get; set; }

        public string ARCustomerPaymentNo { get; set; }

        public DateTime ARCustomerPaymentDate { get; set; }

        /// <summary>
        /// Gets or sets the name of customer
        /// </summary>
        public string ARCustomerName { get; set; }               

        public string BRBranchName { get; set; }       

        public String ARCustomerContactAddressLine3 { get; set; }

        public string HREmployeeName { get; set; }

        public string TypePayment { get; set; }

        public double TotalAmount { get; set; }

        public DateTime ARSaleOrderDate { get; set; }

        public double PaymentTotalAmount { get; set; }

        public string ARCustomerPaymentType { get; set; }

        public string ARPaymentMethodCombo { get; set; }

        public string ARCustomerPaymentDetailDesc { get; set; }

        public double ARSaleOrderTotalAmount { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double DepositTransfer { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double DepositRemain {
            get
            {
                return ARDocumentPaymentAmount - DepositTransfer;
            }
        }
        public string ListType { get; set; }
        public double ARSaleOrderBalanceDue { get; set; }
        public string ICProductNo { get; set; }
        public string ARSaleOrderItemProductDesc { get; set; }
        public double ARSaleOrderItemProductUnitPrice { get; set; }
        public double ARSaleOrderItemProductQty { get; set; }
        public double ARSaleOrderItemTotalAmount { get; set; }
        public double ARSaleOrderItemProductDiscount { get; set; }
        public double ARSaleOrderItemProductTaxPercent { get; set; }
        #endregion
    }
    #endregion
}