using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEParamRelations
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEParamRelationsInfo
    //Created Date:Monday, December 11, 2017
    //-----------------------------------------------------------

    public class MEParamRelationsInfo : BusinessObject
    {
        public MEParamRelationsInfo()
        {
        }
        #region Variables
        protected int _mEParamRelationID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MEParamParentID;
        protected int _fK_MEParamChildID;
        protected int _mEParamRelationOrder;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected bool _mEParamRelationGroupHeader = false;
        protected bool _mEParamRelationGroupFooter = false;
        protected bool _mEParamRelationOnlyAddMe = false;
        protected bool _mEParamRelationGroup = false;
        #endregion

        #region Public properties
        public int MEParamRelationID
        {
            get { return _mEParamRelationID; }
            set
            {
                if (value != this._mEParamRelationID)
                {
                    _mEParamRelationID = value;
                    NotifyChanged("MEParamRelationID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MEParamParentID
        {
            get { return _fK_MEParamParentID; }
            set
            {
                if (value != this._fK_MEParamParentID)
                {
                    _fK_MEParamParentID = value;
                    NotifyChanged("FK_MEParamParentID");
                }
            }
        }
        public int FK_MEParamChildID
        {
            get { return _fK_MEParamChildID; }
            set
            {
                if (value != this._fK_MEParamChildID)
                {
                    _fK_MEParamChildID = value;
                    NotifyChanged("FK_MEParamChildID");
                }
            }
        }
        public int MEParamRelationOrder
        {
            get { return _mEParamRelationOrder; }
            set
            {
                if (value != this._mEParamRelationOrder)
                {
                    _mEParamRelationOrder = value;
                    NotifyChanged("MEParamRelationOrder");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public bool MEParamRelationGroupHeader
        {
            get { return _mEParamRelationGroupHeader; }
            set
            {
                if (value != this._mEParamRelationGroupHeader)
                {
                    _mEParamRelationGroupHeader = value;
                    NotifyChanged("MEParamRelationGroupHeader");
                }
            }
        }
        public bool MEParamRelationGroupFooter
        {
            get { return _mEParamRelationGroupFooter; }
            set
            {
                if (value != this._mEParamRelationGroupFooter)
                {
                    _mEParamRelationGroupFooter = value;
                    NotifyChanged("MEParamRelationGroupFooter");
                }
            }
        }
        public bool MEParamRelationOnlyAddMe
        {
            get { return _mEParamRelationOnlyAddMe; }
            set
            {
                if (value != this._mEParamRelationOnlyAddMe)
                {
                    _mEParamRelationOnlyAddMe = value;
                    NotifyChanged("MEParamRelationOnlyAddMe");
                }
            }
        }
        public bool MEParamRelationGroup
        {
            get { return _mEParamRelationGroup; }
            set
            {
                if (value != this._mEParamRelationGroup)
                {
                    _mEParamRelationGroup = value;
                    NotifyChanged("MEParamRelationGroup");
                }
            }
        }
        #endregion
    }
    #endregion
}