using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region MECHBases
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MECHBasesController
	//Created Date:18 January 2017
	//-----------------------------------------------------------
	
	public class MECHBasesController:BaseBusinessController
	{
		public MECHBasesController()
		{
			dal= new DALBaseProvider("MECHBases",typeof(MECHBasesInfo));
		}

	    public MECHBasesInfo GetAccountByPatientId(int patientId)
	    {
	        var data = dal.GetDataSet("MECHBases_SelectByPatient", patientId);
	        if (data.Tables[0].Rows.Count == 0)
	            return null;
            return (MECHBasesInfo)GetObjectFromDataRow(data.Tables[0].Rows[0]);
        }
	}
	#endregion
}