using System;
using System.Collections.Generic;
using System.Text;
using BOSLib;
namespace BOSERP
{
    #region APPurchaseOrderItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:APPurchaseOrderItemsInfo
    //Created Date:Wednesday, November 17, 2010
    //-----------------------------------------------------------

    public class APPurchaseOrderItemsInfo : ERPModuleItemsEntity
    {
        public APPurchaseOrderItemsInfo()
        {
        }
        #region Variables
        protected int _aPPurchaseOrderItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_APPurchaseOrderID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_ICStockID;
        protected int _fK_ICStockSlotID;
        protected int _fK_APProposalID;
        protected int _fK_APProposalItemID;
        protected String _aPPurchaseOrderItemProductType = String.Empty;
        protected int _aPPurchaseOrderItemSortOrder;
        protected String _aPPurchaseOrderItemProductSerialNo = String.Empty;
        protected String _aPPurchaseOrderItemProductAttribute = String.Empty;
        protected String _aPPurchaseOrderItemProductName = String.Empty;
        protected String _aPPurchaseOrderItemProductDesc = String.Empty;
        protected String _aPPurchaseOrderItemProductSellUnit = String.Empty;
        protected String _aPPurchaseOrderItemProductBasicUnit = String.Empty;
        protected String _aPPurchaseOrderItemProductPackagingUnit = String.Empty;
        protected double _aPPurchaseOrderItemProductSellFactor;
        protected double _aPPurchaseOrderItemProductPackagingFactor;
        protected double _aPPurchaseOrderItemProductUnitPrice;
        protected double _aPPurchaseOrderItemProductUnitCost;
        protected double _aPPurchaseOrderItemProductGroupDiscount;
        protected double _aPPurchaseOrderItemProductDiscount;
        protected double _aPPurchaseOrderItemProductTaxPercent;
        protected double _aPPurchaseOrderItemProductQtyOld;
        protected double _aPPurchaseOrderItemProductQty;
        protected double _aPPurchaseOrderItemProductBasicQty;
        protected double _aPPurchaseOrderItemProductPakagingQty;
        protected double _aPPurchaseOrderItemQty1;
        protected double _aPPurchaseOrderItemQty2;
        protected double _aPPurchaseOrderItemQty3;
        protected double _aPPurchaseOrderItemQty4;
        protected double _aPPurchaseOrderItemQty5;
        protected double _aPPurchaseOrderItemQty6;
        protected String _aPPurchaseOrderItemComment = String.Empty;
        protected double _aPPurchaseOrderItemUnitVolumn;
        protected double _aPPurchaseOrderItemUnitWeight;
        protected double _aPPurchaseOrderItemExtCost;
        protected double _aPPurchaseOrderItemTaxAmount;
        protected double _aPPurchaseOrderItemDiscountAmount;
        protected double _aPPurchaseOrderItemTotalCost;
        protected DateTime _aPPurchaseOrderItemDeliveryDate = DateTime.MaxValue;
        protected String _aPPurchaseOrderItemType = String.Empty;
        protected double _aPPurchaseOrderItemReceiptedQty;
        protected String _aPPurchaseOrderItemProductSupplierNo = String.Empty;
        protected double _aPPurchaseOrderItemPackagedQty;
        #endregion

        #region Public properties
        public int APPurchaseOrderItemID
        {
            get { return _aPPurchaseOrderItemID; }
            set
            {
                if (value != this._aPPurchaseOrderItemID)
                {
                    _aPPurchaseOrderItemID = value;
                    NotifyChanged("APPurchaseOrderItemID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_APPurchaseOrderID
        {
            get { return _fK_APPurchaseOrderID; }
            set
            {
                if (value != this._fK_APPurchaseOrderID)
                {
                    _fK_APPurchaseOrderID = value;
                    NotifyChanged("FK_APPurchaseOrderID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ICStockSlotID
        {
            get { return _fK_ICStockSlotID; }
            set
            {
                if (value != this._fK_ICStockSlotID)
                {
                    _fK_ICStockSlotID = value;
                    NotifyChanged("FK_ICStockSlotID");
                }
            }
        }
        public int FK_APProposalID
        {
            get { return _fK_APProposalID; }
            set
            {
                if (value != this._fK_APProposalID)
                {
                    _fK_APProposalID = value;
                    NotifyChanged("FK_APProposalID");
                }
            }
        }
        public int FK_APProposalItemID
        {
            get { return _fK_APProposalItemID; }
            set
            {
                if (value != this._fK_APProposalItemID)
                {
                    _fK_APProposalItemID = value;
                    NotifyChanged("FK_APProposalItemID");
                }
            }
        }
        public String APPurchaseOrderItemProductType
        {
            get { return _aPPurchaseOrderItemProductType; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductType)
                {
                    _aPPurchaseOrderItemProductType = value;
                    NotifyChanged("APPurchaseOrderItemProductType");
                }
            }
        }
        public int APPurchaseOrderItemSortOrder
        {
            get { return _aPPurchaseOrderItemSortOrder; }
            set
            {
                if (value != this._aPPurchaseOrderItemSortOrder)
                {
                    _aPPurchaseOrderItemSortOrder = value;
                    NotifyChanged("APPurchaseOrderItemSortOrder");
                }
            }
        }
        public String APPurchaseOrderItemProductSerialNo
        {
            get { return _aPPurchaseOrderItemProductSerialNo; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductSerialNo)
                {
                    _aPPurchaseOrderItemProductSerialNo = value;
                    NotifyChanged("APPurchaseOrderItemProductSerialNo");
                }
            }
        }
        public String APPurchaseOrderItemProductAttribute
        {
            get { return _aPPurchaseOrderItemProductAttribute; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductAttribute)
                {
                    _aPPurchaseOrderItemProductAttribute = value;
                    NotifyChanged("APPurchaseOrderItemProductAttribute");
                }
            }
        }
        public String APPurchaseOrderItemProductName
        {
            get { return _aPPurchaseOrderItemProductName; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductName)
                {
                    _aPPurchaseOrderItemProductName = value;
                    NotifyChanged("APPurchaseOrderItemProductName");
                }
            }
        }
        public String APPurchaseOrderItemProductDesc
        {
            get { return _aPPurchaseOrderItemProductDesc; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductDesc)
                {
                    _aPPurchaseOrderItemProductDesc = value;
                    NotifyChanged("APPurchaseOrderItemProductDesc");
                }
            }
        }
        public String APPurchaseOrderItemProductSellUnit
        {
            get { return _aPPurchaseOrderItemProductSellUnit; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductSellUnit)
                {
                    _aPPurchaseOrderItemProductSellUnit = value;
                    NotifyChanged("APPurchaseOrderItemProductSellUnit");
                }
            }
        }
        public String APPurchaseOrderItemProductBasicUnit
        {
            get { return _aPPurchaseOrderItemProductBasicUnit; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductBasicUnit)
                {
                    _aPPurchaseOrderItemProductBasicUnit = value;
                    NotifyChanged("APPurchaseOrderItemProductBasicUnit");
                }
            }
        }
        public String APPurchaseOrderItemProductPackagingUnit
        {
            get { return _aPPurchaseOrderItemProductPackagingUnit; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductPackagingUnit)
                {
                    _aPPurchaseOrderItemProductPackagingUnit = value;
                    NotifyChanged("APPurchaseOrderItemProductPackagingUnit");
                }
            }
        }
        public double APPurchaseOrderItemProductSellFactor
        {
            get { return _aPPurchaseOrderItemProductSellFactor; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductSellFactor)
                {
                    _aPPurchaseOrderItemProductSellFactor = value;
                    NotifyChanged("APPurchaseOrderItemProductSellFactor");
                }
            }
        }
        public double APPurchaseOrderItemProductPackagingFactor
        {
            get { return _aPPurchaseOrderItemProductPackagingFactor; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductPackagingFactor)
                {
                    _aPPurchaseOrderItemProductPackagingFactor = value;
                    NotifyChanged("APPurchaseOrderItemProductPackagingFactor");
                }
            }
        }
        public double APPurchaseOrderItemProductUnitPrice
        {
            get { return _aPPurchaseOrderItemProductUnitPrice; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductUnitPrice)
                {
                    _aPPurchaseOrderItemProductUnitPrice = value;
                    NotifyChanged("APPurchaseOrderItemProductUnitPrice");
                }
            }
        }
        public double APPurchaseOrderItemProductUnitCost
        {
            get { return _aPPurchaseOrderItemProductUnitCost; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductUnitCost)
                {
                    _aPPurchaseOrderItemProductUnitCost = value;
                    NotifyChanged("APPurchaseOrderItemProductUnitCost");
                }
            }
        }
        public double APPurchaseOrderItemProductGroupDiscount
        {
            get { return _aPPurchaseOrderItemProductGroupDiscount; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductGroupDiscount)
                {
                    _aPPurchaseOrderItemProductGroupDiscount = value;
                    NotifyChanged("APPurchaseOrderItemProductGroupDiscount");
                }
            }
        }
        public double APPurchaseOrderItemProductDiscount
        {
            get { return _aPPurchaseOrderItemProductDiscount; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductDiscount)
                {
                    _aPPurchaseOrderItemProductDiscount = value;
                    NotifyChanged("APPurchaseOrderItemProductDiscount");
                }
            }
        }
        public double APPurchaseOrderItemProductTaxPercent
        {
            get { return _aPPurchaseOrderItemProductTaxPercent; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductTaxPercent)
                {
                    _aPPurchaseOrderItemProductTaxPercent = value;
                    NotifyChanged("APPurchaseOrderItemProductTaxPercent");
                }
            }
        }
        public double APPurchaseOrderItemProductQtyOld
        {
            get { return _aPPurchaseOrderItemProductQtyOld; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductQtyOld)
                {
                    _aPPurchaseOrderItemProductQtyOld = value;
                    NotifyChanged("APPurchaseOrderItemProductQtyOld");
                }
            }
        }
        public double APPurchaseOrderItemProductQty
        {
            get { return _aPPurchaseOrderItemProductQty; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductQty)
                {
                    _aPPurchaseOrderItemProductQty = value;
                    NotifyChanged("APPurchaseOrderItemProductQty");
                }
            }
        }
        public double APPurchaseOrderItemProductBasicQty
        {
            get { return _aPPurchaseOrderItemProductBasicQty; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductBasicQty)
                {
                    _aPPurchaseOrderItemProductBasicQty = value;
                    NotifyChanged("APPurchaseOrderItemProductBasicQty");
                }
            }
        }
        public double APPurchaseOrderItemProductPakagingQty
        {
            get { return _aPPurchaseOrderItemProductPakagingQty; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductPakagingQty)
                {
                    _aPPurchaseOrderItemProductPakagingQty = value;
                    NotifyChanged("APPurchaseOrderItemProductPakagingQty");
                }
            }
        }
        public double APPurchaseOrderItemQty1
        {
            get { return _aPPurchaseOrderItemQty1; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty1)
                {
                    _aPPurchaseOrderItemQty1 = value;
                    NotifyChanged("APPurchaseOrderItemQty1");
                }
            }
        }
        public double APPurchaseOrderItemQty2
        {
            get { return _aPPurchaseOrderItemQty2; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty2)
                {
                    _aPPurchaseOrderItemQty2 = value;
                    NotifyChanged("APPurchaseOrderItemQty2");
                }
            }
        }
        public double APPurchaseOrderItemQty3
        {
            get { return _aPPurchaseOrderItemQty3; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty3)
                {
                    _aPPurchaseOrderItemQty3 = value;
                    NotifyChanged("APPurchaseOrderItemQty3");
                }
            }
        }
        public double APPurchaseOrderItemQty4
        {
            get { return _aPPurchaseOrderItemQty4; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty4)
                {
                    _aPPurchaseOrderItemQty4 = value;
                    NotifyChanged("APPurchaseOrderItemQty4");
                }
            }
        }
        public double APPurchaseOrderItemQty5
        {
            get { return _aPPurchaseOrderItemQty5; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty5)
                {
                    _aPPurchaseOrderItemQty5 = value;
                    NotifyChanged("APPurchaseOrderItemQty5");
                }
            }
        }
        public double APPurchaseOrderItemQty6
        {
            get { return _aPPurchaseOrderItemQty6; }
            set
            {
                if (value != this._aPPurchaseOrderItemQty6)
                {
                    _aPPurchaseOrderItemQty6 = value;
                    NotifyChanged("APPurchaseOrderItemQty6");
                }
            }
        }
        public String APPurchaseOrderItemComment
        {
            get { return _aPPurchaseOrderItemComment; }
            set
            {
                if (value != this._aPPurchaseOrderItemComment)
                {
                    _aPPurchaseOrderItemComment = value;
                    NotifyChanged("APPurchaseOrderItemComment");
                }
            }
        }
        public double APPurchaseOrderItemUnitVolumn
        {
            get { return _aPPurchaseOrderItemUnitVolumn; }
            set
            {
                if (value != this._aPPurchaseOrderItemUnitVolumn)
                {
                    _aPPurchaseOrderItemUnitVolumn = value;
                    NotifyChanged("APPurchaseOrderItemUnitVolumn");
                }
            }
        }
        public double APPurchaseOrderItemUnitWeight
        {
            get { return _aPPurchaseOrderItemUnitWeight; }
            set
            {
                if (value != this._aPPurchaseOrderItemUnitWeight)
                {
                    _aPPurchaseOrderItemUnitWeight = value;
                    NotifyChanged("APPurchaseOrderItemUnitWeight");
                }
            }
        }
        public double APPurchaseOrderItemExtCost
        {
            get { return _aPPurchaseOrderItemExtCost; }
            set
            {
                if (value != this._aPPurchaseOrderItemExtCost)
                {
                    _aPPurchaseOrderItemExtCost = value;
                    NotifyChanged("APPurchaseOrderItemExtCost");
                }
            }
        }
        public double APPurchaseOrderItemTaxAmount
        {
            get { return _aPPurchaseOrderItemTaxAmount; }
            set
            {
                if (value != this._aPPurchaseOrderItemTaxAmount)
                {
                    _aPPurchaseOrderItemTaxAmount = value;
                    NotifyChanged("APPurchaseOrderItemTaxAmount");
                }
            }
        }
        public double APPurchaseOrderItemDiscountAmount
        {
            get { return _aPPurchaseOrderItemDiscountAmount; }
            set
            {
                if (value != this._aPPurchaseOrderItemDiscountAmount)
                {
                    _aPPurchaseOrderItemDiscountAmount = value;
                    NotifyChanged("APPurchaseOrderItemDiscountAmount");
                }
            }
        }
        public double APPurchaseOrderItemTotalCost
        {
            get { return _aPPurchaseOrderItemTotalCost; }
            set
            {
                if (value != this._aPPurchaseOrderItemTotalCost)
                {
                    _aPPurchaseOrderItemTotalCost = value;
                    NotifyChanged("APPurchaseOrderItemTotalCost");
                }
            }
        }
        public DateTime APPurchaseOrderItemDeliveryDate
        {
            get { return _aPPurchaseOrderItemDeliveryDate; }
            set
            {
                if (value != this._aPPurchaseOrderItemDeliveryDate)
                {
                    _aPPurchaseOrderItemDeliveryDate = value;
                    NotifyChanged("APPurchaseOrderItemDeliveryDate");
                }
            }
        }
        public String APPurchaseOrderItemType
        {
            get { return _aPPurchaseOrderItemType; }
            set
            {
                if (value != this._aPPurchaseOrderItemType)
                {
                    _aPPurchaseOrderItemType = value;
                    NotifyChanged("APPurchaseOrderItemType");
                }
            }
        }
        public double APPurchaseOrderItemReceiptedQty
        {
            get { return _aPPurchaseOrderItemReceiptedQty; }
            set
            {
                if (value != this._aPPurchaseOrderItemReceiptedQty)
                {
                    _aPPurchaseOrderItemReceiptedQty = value;
                    NotifyChanged("APPurchaseOrderItemReceiptedQty");
                }
            }
        }
        public String APPurchaseOrderItemProductSupplierNo
        {
            get { return _aPPurchaseOrderItemProductSupplierNo; }
            set
            {
                if (value != this._aPPurchaseOrderItemProductSupplierNo)
                {
                    _aPPurchaseOrderItemProductSupplierNo = value;
                    NotifyChanged("APPurchaseOrderItemProductSupplierNo");
                }
            }
        }
        public double APPurchaseOrderItemPackagedQty
        {
            get { return _aPPurchaseOrderItemPackagedQty; }
            set
            {
                if (value != this._aPPurchaseOrderItemPackagedQty)
                {
                    _aPPurchaseOrderItemPackagedQty = value;
                    NotifyChanged("APPurchaseOrderItemPackagedQty");
                }
            }
        }
        #endregion

        #region Extra Properties
        public byte[] APPurchaseOrderItemProductPicture { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupQty)]
        public double APPurchaseOrderItemRemainedQty { get; set; }

        /// <summary>
        /// Gets or sets text of purchase order item type
        /// </summary>
        public string ADConfigText { get; set; }

        public String APPurchaseOrderType { get; set; }
        public string APPurchaseOrderTypeDisplayText { get; set; }
        public String APPurchaseOrderStatus { get; set; }
        public string APPurchaseOrderStatusDisplayText { get; set; }
        public String APSupplierName { get; set; }
        public String ICMeasureUnitName { get; set; }
        public String APSupplierContactPhone1 { get; set; }
        public String APSupplierContactPhone2 { get; set; }
        public String APPurchaseOrderNo { get; set; }    
        public DateTime APPurchaseOrderDate { get; set; }
        public DateTime APPurchaseOrderDeliveryDate { get; set; }
        public DateTime APPurchaseOrderPackingDate { get; set; }
        public String APPurchaseOrderDesc { get; set; }
        public string APPurchaseOrderComment { get; set; }
        public String APPurchaseOrderRowNumber { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPriceByCurrency)]
        public double APPurchaseOrderTotalCost { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPriceByCurrency)]
        public double APPurchaseOrderDepositBalance { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPriceByCurrency)]
        public double APPurchaseOrderBalanceDue { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupExchangeRate)]
        public double APPurchaseOrderVolume { get; set; }
        
        public bool IsSubItem { get; set; }
        public int ICStockID { get; set; }
        #endregion
    }
    #endregion
}