using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region APSupplierPaymentDetails
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:APSupplierPaymentDetailsInfo
    //Created Date:Tuesday, January 17, 2012
    //-----------------------------------------------------------

    public class APSupplierPaymentDetailsInfo : BusinessObject
    {
        public APSupplierPaymentDetailsInfo()
        {
        }
        #region Variables
        protected int _aPSupplierPaymentDetailID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_APSupplierPaymentID;
        protected String _aPPaymentMethodCombo = String.Empty;
        protected double _aPSupplierPaymentDetailAmount;
        protected String _aPSupplierPaymentDetailInfo = String.Empty;
        #endregion

        #region Public properties
        public int APSupplierPaymentDetailID
        {
            get { return _aPSupplierPaymentDetailID; }
            set
            {
                if (value != this._aPSupplierPaymentDetailID)
                {
                    _aPSupplierPaymentDetailID = value;
                    NotifyChanged("APSupplierPaymentDetailID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_APSupplierPaymentID
        {
            get { return _fK_APSupplierPaymentID; }
            set
            {
                if (value != this._fK_APSupplierPaymentID)
                {
                    _fK_APSupplierPaymentID = value;
                    NotifyChanged("FK_APSupplierPaymentID");
                }
            }
        }
        public String APPaymentMethodCombo
        {
            get { return _aPPaymentMethodCombo; }
            set
            {
                if (value != this._aPPaymentMethodCombo)
                {
                    _aPPaymentMethodCombo = value;
                    NotifyChanged("APPaymentMethodCombo");
                }
            }
        }
        public double APSupplierPaymentDetailAmount
        {
            get { return _aPSupplierPaymentDetailAmount; }
            set
            {
                if (value != this._aPSupplierPaymentDetailAmount)
                {
                    _aPSupplierPaymentDetailAmount = value;
                    NotifyChanged("APSupplierPaymentDetailAmount");
                }
            }
        }
        public String APSupplierPaymentDetailInfo
        {
            get { return _aPSupplierPaymentDetailInfo; }
            set
            {
                if (value != this._aPSupplierPaymentDetailInfo)
                {
                    _aPSupplierPaymentDetailInfo = value;
                    NotifyChanged("APSupplierPaymentDetailInfo");
                }
            }
        }
        #endregion
    }
    #endregion
}