using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region ICReceiptItems
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:ICReceiptItemsController
	//Created Date:Saturday, May 31, 2008
	//-----------------------------------------------------------
	
	public class ICReceiptItemsController:BaseBusinessController
	{
		public ICReceiptItemsController()
		{
			dal= new DALBaseProvider("ICReceiptItems",typeof(ICReceiptItemsInfo));
		}

        public DataSet GetReceiptItemsByProductSerialNoAndStockID(
                                                            String strProductSerialNo,
                                                            int iStockID)
        {
            return dal.GetDataSet("ICReceiptItems_SelectByProductSerialNoAndStockID",
                                                         strProductSerialNo,
                                                         iStockID);
        }

        public ICReceiptItemsInfo GetReceiptItemByProductSerialNoAndStockID(
                                                            String strProductSerialNo,
                                                            int iStockID)
        {
            return (ICReceiptItemsInfo)dal.GetDataObject("ICReceiptItems_SelectByProductSerialNoAndStockID",
                                                         strProductSerialNo,
                                                         iStockID);
        }

        public DataSet GetReceiptItemsByProductSerialNo(String strProductSerialNo)
        {
            return dal.GetDataSet("ICReceiptItems_SelectByProductSerialNo", strProductSerialNo);
        }

        public ICReceiptItemsInfo GetReceiptItemByProductSerialNo(String strProductSerialNo)
        {
            return (ICReceiptItemsInfo)dal.GetDataObject("ICReceiptItems_SelectByProductSerialNo", strProductSerialNo);
        }

        public DataSet GetReceiptItemsByProductID(int iProductID)
        {
            return dal.GetDataSet("ICReceiptItems_SelectByProductID", iProductID);
        }

        public ICReceiptItemsInfo GetReceiptItemByProductID(int iProductID)
        {
            return (ICReceiptItemsInfo)dal.GetDataObject("ICReceiptItems_SelectByProductID", iProductID);
        }

        public DataSet GetReceiptItemsByProductIDAndStockID(int iProductID, int iStockID)
        {
            DataSet ds = GetReceiptItemsByProductID(iProductID);
            if (ds.Tables.Count > 0)
            {
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    ICReceiptItemsInfo objReceiptItemsInfo = (ICReceiptItemsInfo)GetObjectFromDataRow(ds.Tables[0].Rows[i]);
                    if (objReceiptItemsInfo != null)
                        if (objReceiptItemsInfo.FK_ICStockID != iStockID)
                        {
                            ds.Tables[0].Rows.RemoveAt(i);
                            i--;
                        }
                }
            }
            return ds;
        }

        public ICReceiptItemsInfo GetReceiptItemByProductIDAndStockID(int iProductID, int iStockID)
        {
            DataSet ds = GetReceiptItemsByProductIDAndStockID(iProductID, iStockID);
            if (ds.Tables.Count > 0)
                return (ICReceiptItemsInfo)dal.GetSingleObject(ds.Tables[0]);
            return null;
        }

        /// <summary>
        /// Get receipt item by sale return id
        /// </summary>
        /// <param name="saleReturnID">Sale return id</param>
        /// <returns>Data of the receipt item</returns>
        public DataSet GetReceiptItemsBySaleReturnID(int saleReturnID)
        {
            return dal.GetDataSet("ICReceiptItems_GetReceiptItemsBySaleReturnID", saleReturnID);
        }

        /// <summary>
        /// Get Receipt item by sale return id and SaleReturn item id
        /// </summary>
        /// <param name="SaleReturnID">Sale return id</param>
        /// <param name="SaleReturnItemID">Sale return item id</param>
        /// <returns>Receipt item info</returns>
        public ICReceiptItemsInfo GetReceiptItemBySaleReturnIDAndSaleReturnItemID(int saleReturnID, int saleReturnItemID)
        {
            DataSet ds = dal.GetDataSet("ICReceiptItems_GetReceiptItemBySaleReturnIDAndSaleReturnItemID", saleReturnID, saleReturnItemID);
            if (ds.Tables[0].Rows.Count > 0)
            {
                ICReceiptItemsInfo objReceiptItemsInfo = (ICReceiptItemsInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objReceiptItemsInfo;
            }
            return null;
        }

        /// <summary>
        /// Get receipt item by receipt id and item type
        /// </summary>
        /// <param name="receiptID">Receipt id</param>
        /// <param name="receiptItemType">Type of the receipt item</param>
        /// <returns>Data of the receipt item</returns>
        public DataSet GetReceiptItemByReceiptIDAndReceiptItemType(int receiptID, string receiptItemType)
        {
            DataSet ds = dal.GetDataSet("ICReceiptItems_GetReceiptItemByReceiptIDAndReceiptItemType", receiptID, receiptItemType);
            return ds;
        }

        /// <summary>
        /// Get receipt item list including the item's components of a receipt
        /// </summary>
        /// <param name="receiptID">Receipt id</param>
        /// <returns>List of receipt items</returns>
        public List<ICReceiptItemsInfo> GetComponentItemsByReceiptID(int receiptID)
        {
            DataSet ds = dal.GetDataSet("ICReceiptItems_GetComponentItemsByReceiptID", receiptID);
            List<ICReceiptItemsInfo> receiptItems = new List<ICReceiptItemsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ICReceiptItemsInfo objReceiptItemsInfo = (ICReceiptItemsInfo)GetObjectFromDataRow(row);
                    receiptItems.Add(objReceiptItemsInfo);
                }
            }
            return receiptItems;
        }

        /// <summary>
        /// Get all items of a receipt
        /// </summary>
        /// <param name="receiptID">Receipt id</param>
        /// <returns>List of receipt items</returns>
        public List<ICReceiptItemsInfo> GetItemsByReceiptID(int receiptID)
        {
            DataSet ds = dal.GetDataSet("ICReceiptItems_GetItemsByReceiptID", receiptID);
            List<ICReceiptItemsInfo> receiptItems = new List<ICReceiptItemsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ICReceiptItemsInfo objReceiptItemsInfo = (ICReceiptItemsInfo)GetObjectFromDataRow(row);
                    receiptItems.Add(objReceiptItemsInfo);
                }
            }
            return receiptItems;
        }

        /// <summary>
        /// Get total inventory cost of a product by date range
        /// </summary>
        /// <param name="productID">Product id</param>
        /// <param name="fromDate">Date the cost is calculated from</param>
        /// <param name="toDate">Date the cost is calculated to</param>
        /// <returns>Total inventory cost</returns>
        public double GetTotalInventoryCostByProductIDAndDate(int productID, DateTime? fromDate, DateTime? toDate)
        {
            double totalCost = Convert.ToDouble(dal.GetSingleValue("ICReceiptItems_GetTotalInventoryCostByProductIDAndDate", productID, fromDate, toDate));
            return totalCost;
        }

        /// <summary>
        /// Get total receipted quantity of a product by date range
        /// </summary>        
        /// <param name="productID">Product id</param>
        /// /// <param name="fromDate">Date the quantity is calculated from</param>
        /// <param name="toDate">Date the quantity is calculated to</param>
        /// <returns>Total receipted quantity</returns>
        public double GetTotalQtyByProductIDAndDate(int productID, DateTime? fromDate, DateTime? toDate)
        {
            double totalQty = Convert.ToDouble(dal.GetSingleValue("ICReceiptItems_GetTotalQtyByProductIDAndDate", productID, fromDate, toDate));            
            return totalQty;
        }

        /// <summary>
        /// Get cost of goods sold of an item of a return receipt
        /// </summary>
        /// <param name="receiptItemID">Receipt item id</param>
        /// <returns>Cost of goods sold</returns>
        public double GetCostOfGoodsSold(int receiptItemID)
        {
            object costOfGoodsSold = dal.GetSingleValue("ICReceiptItems_GetCostOfGoodsSold", receiptItemID);
            return Convert.ToDouble(costOfGoodsSold);
        }


        /// <summary>
        /// Get the total extended cost of a receipt
        /// </summary>
        /// <param name="receiptID">Receipt id</param>
        /// <returns>Extended cost</returns>
        public double GetTotalExtCostByReceiptID(int receiptID)
        {
            return Convert.ToDouble(dal.GetSingleValue("ICReceiptItems_GetTotalExtCostByReceiptID", receiptID));
        }
	}
	#endregion
}