using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ACBankTransactions
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ACBankTransactionsController
    //Created Date:Tuesday, March 13, 2012
    //-----------------------------------------------------------

    public class ACBankTransactionsController : BaseBusinessController
    {
        public ACBankTransactionsController()
        {
            dal = new DALBaseProvider("ACBankTransactions", typeof(ACBankTransactionsInfo));
        }

        /// <summary>
        /// Gets the bank transaction list.
        /// </summary>
        /// <param name="bankTransactionNo">The bank transaction no.</param>
        /// <param name="objectID">The object ID.</param>        
        /// <param name="bankTransactionType">Type of the bank transaction.</param>
        /// <param name="employeeID">The employee ID.</param>
        /// <param name="fromDate">From date.</param>
        /// <param name="toDate">To date.</param>
        /// <returns>List of bank transaction</returns>
        public DataSet GetBankTransactionList(string bankTransactionNo,
                                    int? objectID,          
                                    string objectType,              
                                    string bankTransactionType,
                                    int? employeeID,
                                    DateTime? fromDate,
                                    DateTime? toDate)
        {
            return dal.GetDataSet("ACBankTransactions_GetBankTransactionList", 
                                bankTransactionNo, 
                                objectID, 
                                objectType,
                                bankTransactionType, 
                                employeeID, 
                                fromDate, 
                                toDate);
        }

        public DataSet GetBankTransactionList(string bankTransactionNo,
                                    int? FK_BRBranchID,
                                    int? objectID,
                                    string objectType,
                                    string bankTransactionType,
                                    int? employeeID,
                                    DateTime? fromDate,
                                    DateTime? toDate)
        {
            return dal.GetDataSet("ACBankTransactions_GetBankTransactionListByBranchID",
                                bankTransactionNo,
                                objectID,
                                objectType,
                                bankTransactionType,
                                employeeID,
                                fromDate,
                                toDate,
                                FK_BRBranchID);
        }
        public DataSet GetBankTransactionList(string bankTransactionNo,
                                            List<BRBranchsInfo> branchList,
                                            int? objectID,
                                            string objectType,
                                            string bankTransactionType,
                                            int? employeeID,
                                            DateTime? fromDate,
                                            DateTime? toDate)
        {
            DataSet rtn = new DataSet();
            foreach (BRBranchsInfo ojbBranchsInfo in branchList)
            {
                DataSet ds = dal.GetDataSet("ACBankTransactions_GetBankTransactionListByBranchID",
                                bankTransactionNo,
                                objectID,
                                objectType,
                                bankTransactionType,
                                employeeID,
                                fromDate,
                                toDate,
                                ojbBranchsInfo.BRBranchID);
                rtn.Merge(ds);
            }

            return rtn;
        }

        /// <summary>
        /// Gets the bank transaction list by branch id
        /// </summary>
        /// <param name="bankTransactionNo">The bank transaction no.</param>
        /// <param name="objectID">The object ID.</param>        
        /// <param name="bankTransactionType">Type of the bank transaction.</param>
        /// <param name="employeeID">The employee ID.</param>
        /// <param name="fromDate">From date.</param>
        /// <param name="toDate">To date.</param>
        /// <param name="branchID">BRBranch ID.</param>
        /// <returns>List of bank transaction</returns>
        public DataSet GetBankTransactionListByBranchID(string bankTransactionNo,
                                    int? objectID,
                                    string objectType,
                                    string bankTransactionType,
                                    int? employeeID,
                                    DateTime? fromDate,
                                    DateTime? toDate,
                                    int? branchID)
        {
            return dal.GetDataSet("ACBankTransactions_GetBankTransactionListByBranchID",
                                bankTransactionNo,
                                objectID,
                                objectType,
                                bankTransactionType,
                                employeeID,
                                fromDate,
                                toDate,
                                branchID);
        }

        /// <summary>
        /// Gets the bank transaction list by list of branch id
        /// </summary>
        /// <param name="bankTransactionNo">The bank transaction no.</param>
        /// <param name="objectID">The object ID.</param>        
        /// <param name="bankTransactionType">Type of the bank transaction.</param>
        /// <param name="employeeID">The employee ID.</param>
        /// <param name="fromDate">From date.</param>
        /// <param name="toDate">To date.</param>
        /// <param name="branchID">branch ID.</param>
        /// <param name="branchID"> list branch ID.</param>
        /// <returns>List of bank transaction</returns>
        public DataSet GetBankTransactionListByListOfBranchID(string bankTransactionNo,
                                    int? objectID,
                                    string objectType,
                                    string bankTransactionType,
                                    int? employeeID,
                                    DateTime? fromDate,
                                    DateTime? toDate,
                                    int? branchID,
                                    List<BRBranchsInfo> branchList)
        {
            DataSet rtn = new DataSet();
            foreach (BRBranchsInfo ojbBranchsInfo in branchList)
            {
                DataSet ds = GetBankTransactionListByBranchID(bankTransactionNo, objectID, objectType, bankTransactionType, employeeID, fromDate, toDate
                                                                , ojbBranchsInfo.BRBranchID);
                rtn.Merge(ds);
            }

            return rtn;
        }

        /// <summary>
        /// Get a bank transaction by its reference info
        /// </summary>
        /// <param name="reference">Reference info</param>
        /// <returns>Bank transaction object</returns>
        public ACBankTransactionsInfo GetBankTransactionByReference(string reference)
        {
            return (ACBankTransactionsInfo)dal.GetDataObject("ACBankTransactions_GetBankTransactionByReference", reference);
        }

        /// <summary>
        /// Get a bank transaction by its id
        /// </summary>
        /// <param name="bankTransactionID">Bank transaction id</param>
        /// <returns>Bank transaction object</returns>
        public ACBankTransactionsInfo GetBankTransactionByID(int bankTransactionID)
        {
            return (ACBankTransactionsInfo)dal.GetDataObject("ACBankTransactions_GetBankTransactionByID", bankTransactionID);
        }

        /// <summary>
        /// Get bank transactions for transferring
        /// </summary>
        /// <returns>List of transferred bank transactions</returns>
        public List<ACBankTransactionsInfo> GetBankTransactionsForTransferring()
        {
            DataSet ds = dal.GetDataSet("ACBankTransactions_GetBankTransactionsForTransferring");
            return (List<ACBankTransactionsInfo>)GetListFromDataSet(ds);
        }

        /// <summary>
        /// Get bank transactions for broadcasting to a branch
        /// </summary>
        /// <param name="branchID">Branch id</param>
        /// <returns>List of broadcasted bank transactions</returns>
        public List<ACBankTransactionsInfo> GetBankTransactionsForBroadcasting(int branchID)
        {
            DataSet ds = dal.GetDataSet("ACBankTransactions_GetBankTransactionsForBroadcasting", branchID);
            return (List<ACBankTransactionsInfo>)GetListFromDataSet(ds);
        }

        public override System.Collections.IList GetListFromDataSet(DataSet ds)
        {
            List<ACBankTransactionsInfo> bankTransactions = new List<ACBankTransactionsInfo>();
            if (ds.Tables.Count > 0)
            {
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    ACBankTransactionsInfo bankTransaction = (ACBankTransactionsInfo)GetObjectFromDataRow(row);
                    bankTransactions.Add(bankTransaction);
                }
            }
            return bankTransactions;
        }
    }
    #endregion
}