using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region HRDepartmentRooms
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HRDepartmentRoomsInfo
    //Created Date:Monday, April 09, 2012
    //-----------------------------------------------------------

    public class HRDepartmentRoomsInfo : BusinessObject
    {
        public HRDepartmentRoomsInfo()
        {
        }

        #region Variables
        protected int _hRDepartmentRoomID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_HRDepartmentID;
        protected int _fK_BRBranchID;
        protected String _hRDepartmentRoomNo = String.Empty;
        protected String _hRDepartmentRoomName = String.Empty;
        protected String _hRDepartmentRoomDesc = String.Empty;
        private string _hRBs24x7BranchId = String.Empty;
        #endregion

        #region Public properties
        public int HRDepartmentRoomID
        {
            get { return _hRDepartmentRoomID; }
            set
            {
                if (value != this._hRDepartmentRoomID)
                {
                    _hRDepartmentRoomID = value;
                    NotifyChanged("HRDepartmentRoomID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_HRDepartmentID
        {
            get { return _fK_HRDepartmentID; }
            set
            {
                if (value != this._fK_HRDepartmentID)
                {
                    _fK_HRDepartmentID = value;
                    NotifyChanged("FK_HRDepartmentID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public String HRDepartmentRoomNo
        {
            get { return _hRDepartmentRoomNo; }
            set
            {
                if (value != this._hRDepartmentRoomNo)
                {
                    _hRDepartmentRoomNo = value;
                    NotifyChanged("HRDepartmentRoomNo");
                }
            }
        }
        public String HRDepartmentRoomName
        {
            get { return _hRDepartmentRoomName; }
            set
            {
                if (value != this._hRDepartmentRoomName)
                {
                    _hRDepartmentRoomName = value;
                    NotifyChanged("HRDepartmentRoomName");
                }
            }
        }
        public String HRDepartmentRoomDesc
        {
            get { return _hRDepartmentRoomDesc; }
            set
            {
                if (value != this._hRDepartmentRoomDesc)
                {
                    _hRDepartmentRoomDesc = value;
                    NotifyChanged("HRDepartmentRoomDesc");
                }
            }
        }
        public String HRBs24x7BranchId
        {
            get { return _hRBs24x7BranchId; }
            set
            {
                if (value != this._hRBs24x7BranchId)
                {
                    _hRBs24x7BranchId = value;
                    NotifyChanged("HRBs24x7BranchId");
                }
            }
        }
        #endregion

        #region Extra Properties
        public String HREmployeeName { get; set; }

        public int MECountPatientWait { get; set; }

        public String MECurrentPatient { get; set; }

        public String MENextPatient { get; set; }
        ///// <summary>
        ///// Gets or sets list of room bed in a room
        ///// </summary>
        public IBOSList<HRRoomBedsInfo> RoomBedList { get; set; }
        #endregion
    }
    #endregion
}