GO
IF COL_LENGTH('MEEmrs', 'MEEmrICDCodeIn') IS NOT NULL
BEGIN
	ALTER TABLE dbo.MEEmrs DROP CONSTRAINT DF_MEEmrs_MEEmrICDCodeIn
	ALTER TABLE dbo.MEEmrs DROP COLUMN MEEmrICDCodeIn
END
GO
IF COL_LENGTH('MEEmrs', 'MEEmrICDStrIn') IS NOT NULL
BEGIN
	ALTER TABLE dbo.MEEmrs DROP CONSTRAINT DF_MEEmrs_MEEmrICDStrIn
	ALTER TABLE dbo.MEEmrs DROP COLUMN MEEmrICDStrIn
END
GO
IF COL_LENGTH('MEEmrs', 'MEEmrICDCodeOut') IS NOT NULL
BEGIN
	ALTER TABLE dbo.MEEmrs DROP CONSTRAINT DF_MEEmrs_MEEmrICDCodeOut
	ALTER TABLE dbo.MEEmrs DROP COLUMN MEEmrICDCodeOut
END
GO
IF COL_LENGTH('MEEmrs', 'MEEmrICDStrOut') IS NOT NULL
BEGIN
	ALTER TABLE dbo.MEEmrs DROP CONSTRAINT DF_MEEmrs_MEEmrICDStrOut
	ALTER TABLE dbo.MEEmrs DROP COLUMN MEEmrICDStrOut
END

GO
ALTER TABLE MEEmrs ADD MEEmrICDCodeIn nvarchar(128) 
GO
UPDATE  MEEmrs SET MEEmrICDCodeIn=''
GO
ALTER TABLE MEEmrs ADD CONSTRAINT DF_MEEmrs_MEEmrICDCodeIn DEFAULT '' FOR MEEmrICDCodeIn

GO
ALTER TABLE MEEmrs ADD MEEmrICDStrIn nvarchar(1024) 
GO
UPDATE  MEEmrs SET MEEmrICDStrIn=''
GO
ALTER TABLE MEEmrs ADD CONSTRAINT DF_MEEmrs_MEEmrICDStrIn DEFAULT '' FOR MEEmrICDStrIn

GO
ALTER TABLE MEEmrs ADD MEEmrICDCodeOut nvarchar(128) 
GO
UPDATE  MEEmrs SET MEEmrICDCodeOut=''
GO
ALTER TABLE MEEmrs ADD CONSTRAINT DF_MEEmrs_MEEmrICDCodeOut DEFAULT '' FOR MEEmrICDCodeOut

GO
ALTER TABLE MEEmrs ADD MEEmrICDStrOut nvarchar(1024) 
GO
UPDATE  MEEmrs SET MEEmrICDStrOut=''
GO
ALTER TABLE MEEmrs ADD CONSTRAINT DF_MEEmrs_MEEmrICDStrOut DEFAULT '' FOR MEEmrICDStrOut


