using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
	#region MEEmrSums
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MEEmrSumsInfo
	//Created Date:Wednesday, September 8, 2021
	//-----------------------------------------------------------

	public class MEEmrSumsInfo : BusinessObject
	{
		public MEEmrSumsInfo()
		{
		}
		#region Variables
		protected int _mEEmrSumID;
		protected String _aAStatus = DefaultAAStatus;
		protected String _aACreatedUser = String.Empty;
		protected DateTime _aACreatedDate = DateTime.MaxValue;
		protected String _aAUpdatedUser = String.Empty;
		protected DateTime _aAUpdatedDate = DateTime.MaxValue;
		protected int _fK_MEEmrID;
		protected String _mEEmrSumCode = String.Empty;
		protected String _mEEmrSumStoreCode = String.Empty;
		protected DateTime _mEEmrSumDate = DateTime.MaxValue;
		protected String _mEEmrSumRemark = String.Empty;
		protected String _mEEmrSumFileName = String.Empty;
		protected String _mEEmrSumMongoID = String.Empty;
		protected String _mEEmrSumStatus = DefaultStatus;
		protected String _mEEmrSumXMLStatus = DefaultStatus;
		protected String _mEEmrSumXMLDesc = String.Empty;
		protected DateTime _mEEmrSumXMLDate = DateTime.MaxValue;
		protected int _mEEmrSumXMLSentNum;
		protected bool _mEEmrSumXMLCombine = true;
		#endregion

		#region Public properties
		public int MEEmrSumID
		{
			get { return _mEEmrSumID; }
			set
			{
				if (value != this._mEEmrSumID)
				{
					_mEEmrSumID = value;
					NotifyChanged("MEEmrSumID");
				}
			}
		}
		public String AAStatus
		{
			get { return _aAStatus; }
			set
			{
				if (value != this._aAStatus)
				{
					_aAStatus = value;
					NotifyChanged("AAStatus");
				}
			}
		}
		public String AACreatedUser
		{
			get { return _aACreatedUser; }
			set
			{
				if (value != this._aACreatedUser)
				{
					_aACreatedUser = value;
					NotifyChanged("AACreatedUser");
				}
			}
		}
		public DateTime AACreatedDate
		{
			get { return _aACreatedDate; }
			set
			{
				if (value != this._aACreatedDate)
				{
					_aACreatedDate = value;
					NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get { return _aAUpdatedUser; }
			set
			{
				if (value != this._aAUpdatedUser)
				{
					_aAUpdatedUser = value;
					NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public DateTime AAUpdatedDate
		{
			get { return _aAUpdatedDate; }
			set
			{
				if (value != this._aAUpdatedDate)
				{
					_aAUpdatedDate = value;
					NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public int FK_MEEmrID
		{
			get { return _fK_MEEmrID; }
			set
			{
				if (value != this._fK_MEEmrID)
				{
					_fK_MEEmrID = value;
					NotifyChanged("FK_MEEmrID");
				}
			}
		}
		public String MEEmrSumCode
		{
			get { return _mEEmrSumCode; }
			set
			{
				if (value != this._mEEmrSumCode)
				{
					_mEEmrSumCode = value;
					NotifyChanged("MEEmrSumCode");
				}
			}
		}
		public String MEEmrSumStoreCode
		{
			get { return _mEEmrSumStoreCode; }
			set
			{
				if (value != this._mEEmrSumStoreCode)
				{
					_mEEmrSumStoreCode = value;
					NotifyChanged("MEEmrSumStoreCode");
				}
			}
		}
		public DateTime MEEmrSumDate
		{
			get { return _mEEmrSumDate; }
			set
			{
				if (value != this._mEEmrSumDate)
				{
					_mEEmrSumDate = value;
					NotifyChanged("MEEmrSumDate");
				}
			}
		}
		public String MEEmrSumRemark
		{
			get { return _mEEmrSumRemark; }
			set
			{
				if (value != this._mEEmrSumRemark)
				{
					_mEEmrSumRemark = value;
					NotifyChanged("MEEmrSumRemark");
				}
			}
		}
		public String MEEmrSumFileName
		{
			get { return _mEEmrSumFileName; }
			set
			{
				if (value != this._mEEmrSumFileName)
				{
					_mEEmrSumFileName = value;
					NotifyChanged("MEEmrSumFileName");
				}
			}
		}
		public String MEEmrSumMongoID
		{
			get { return _mEEmrSumMongoID; }
			set
			{
				if (value != this._mEEmrSumMongoID)
				{
					_mEEmrSumMongoID = value;
					NotifyChanged("MEEmrSumMongoID");
				}
			}
		}
		public String MEEmrSumStatus
		{
			get { return _mEEmrSumStatus; }
			set
			{
				if (value != this._mEEmrSumStatus)
				{
					_mEEmrSumStatus = value;
					NotifyChanged("MEEmrSumStatus");
				}
			}
		}
		public String MEEmrSumXMLStatus
		{
			get { return _mEEmrSumXMLStatus; }
			set
			{
				if (value != this._mEEmrSumXMLStatus)
				{
					_mEEmrSumXMLStatus = value;
					NotifyChanged("MEEmrSumXMLStatus");
				}
			}
		}
		public String MEEmrSumXMLDesc
		{
			get { return _mEEmrSumXMLDesc; }
			set
			{
				if (value != this._mEEmrSumXMLDesc)
				{
					_mEEmrSumXMLDesc = value;
					NotifyChanged("MEEmrSumXMLDesc");
				}
			}
		}
		public DateTime MEEmrSumXMLDate
		{
			get { return _mEEmrSumXMLDate; }
			set
			{
				if (value != this._mEEmrSumXMLDate)
				{
					_mEEmrSumXMLDate = value;
					NotifyChanged("MEEmrSumXMLDate");
				}
			}
		}
		public int MEEmrSumXMLSentNum
		{
			get { return _mEEmrSumXMLSentNum; }
			set
			{
				if (value != this._mEEmrSumXMLSentNum)
				{
					_mEEmrSumXMLSentNum = value;
					NotifyChanged("MEEmrSumXMLSentNum");
				}
			}
		}
		public bool MEEmrSumXMLCombine
		{
			get { return _mEEmrSumXMLCombine; }
			set
			{
				if (value != this._mEEmrSumXMLCombine)
				{
					_mEEmrSumXMLCombine = value;
					NotifyChanged("MEEmrSumXMLCombine");
				}
			}
		}

		#endregion

		#region Extra
		public string MEEmrNo { get; internal set; }
		public string MEPatientNo { get; set; }
		public string MEPatientName { get; set; }
		public DateTime MEPatientBirthday { get; set; }
		public DateTime MEEmrDateIn { get; set; }
		public DateTime MEEmrDateOut { get; set; }
		public string MEEmrTypeName { get; set; }
		public string HRDepartmentName { get; set; }
		public string MEEmrICDStrOut { get; set; }
		#endregion
	}
	#endregion
}