using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEEmrGroupImages
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEEmrGroupImagesInfo
    //Created Date:Wednesday, April 18, 2018
    //-----------------------------------------------------------

    public class MEEmrGroupImagesInfo : BusinessObject
    {
        public MEEmrGroupImagesInfo()
        {
        }
        #region Variables
        protected int _mEEmrGroupImageID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _mEEmrGroupImageNo = String.Empty;
        protected int _mEEmrGroupImageOrder;
        protected String _mEEmrGroupImageName = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        #endregion

        #region Public properties
        public int MEEmrGroupImageID
        {
            get { return _mEEmrGroupImageID; }
            set
            {
                if (value != this._mEEmrGroupImageID)
                {
                    _mEEmrGroupImageID = value;
                    NotifyChanged("MEEmrGroupImageID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String MEEmrGroupImageNo
        {
            get { return _mEEmrGroupImageNo; }
            set
            {
                if (value != this._mEEmrGroupImageNo)
                {
                    _mEEmrGroupImageNo = value;
                    NotifyChanged("MEEmrGroupImageNo");
                }
            }
        }
        public int MEEmrGroupImageOrder
        {
            get { return _mEEmrGroupImageOrder; }
            set
            {
                if (value != this._mEEmrGroupImageOrder)
                {
                    _mEEmrGroupImageOrder = value;
                    NotifyChanged("MEEmrGroupImageOrder");
                }
            }
        }
        public String MEEmrGroupImageName
        {
            get { return _mEEmrGroupImageName; }
            set
            {
                if (value != this._mEEmrGroupImageName)
                {
                    _mEEmrGroupImageName = value;
                    NotifyChanged("MEEmrGroupImageName");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        #endregion
    }
    #endregion
}