using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
	#region MEEmrTypes
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MEEmrTypesInfo
	//Created Date:05 Tháng Hai 2021
	//-----------------------------------------------------------

	public class MEEmrTypesInfo : BusinessObject
	{
		public MEEmrTypesInfo()
		{
		}
		#region Variables
		protected int _mEEmrTypeID;
		protected String _aAStatus = DefaultAAStatus;
		protected String _mEEmrTypeNo = String.Empty;
		protected String _mEEmrTypeName = String.Empty;
		protected String _mEEmrTypeDesc = String.Empty;
		protected String _aACreatedUser = String.Empty;
		protected DateTime _aACreatedDate = DateTime.MaxValue;
		protected String _aAUpdatedUser = String.Empty;
		protected DateTime _aAUpdatedDate = DateTime.MaxValue;
		protected bool _mEEmrTypeIsTmp = true;
		protected int _fK_HRDepartmentID;
		protected String _mEEmrTypeProfile = String.Empty;
		protected int _mEEmrTypeDgtSignatureX;
		protected int _mEEmrTypeDgtSignatureY;
		protected int _mEEmrTypeDgtSignatureWidth;
		protected int _mEEmrTypeDgtSignatureHeight;
		protected int _mEEmrTypeDgtSignatureFontSize;
		protected int _mEEmrTypeDgtSignatureTextColor;
		protected int _mEEmrTypeDgtSignaturePage;
		protected bool _mEEmrTypeDgtSignatureImage = true;
		protected bool _mEEmrTypeDgtSignatureVisible = true;
		protected String _mEEmrTypeDgtSignatureReason = String.Empty;
		protected int _mEEmrTypeMaxCountPerPatient;
		protected bool _mEEmrTypeFilterTemplate = false;
		protected bool _mEEmrTypeOneEmrOnePhase = false;

		#endregion

		#region Public properties
		public int MEEmrTypeID
		{
			get { return _mEEmrTypeID; }
			set
			{
				if (value != this._mEEmrTypeID)
				{
					_mEEmrTypeID = value;
					NotifyChanged("MEEmrTypeID");
				}
			}
		}
		public String AAStatus
		{
			get { return _aAStatus; }
			set
			{
				if (value != this._aAStatus)
				{
					_aAStatus = value;
					NotifyChanged("AAStatus");
				}
			}
		}
		public String MEEmrTypeNo
		{
			get { return _mEEmrTypeNo; }
			set
			{
				if (value != this._mEEmrTypeNo)
				{
					_mEEmrTypeNo = value;
					NotifyChanged("MEEmrTypeNo");
				}
			}
		}
		public String MEEmrTypeName
		{
			get { return _mEEmrTypeName; }
			set
			{
				if (value != this._mEEmrTypeName)
				{
					_mEEmrTypeName = value;
					NotifyChanged("MEEmrTypeName");
				}
			}
		}
		public String MEEmrTypeDesc
		{
			get { return _mEEmrTypeDesc; }
			set
			{
				if (value != this._mEEmrTypeDesc)
				{
					_mEEmrTypeDesc = value;
					NotifyChanged("MEEmrTypeDesc");
				}
			}
		}
		public String AACreatedUser
		{
			get { return _aACreatedUser; }
			set
			{
				if (value != this._aACreatedUser)
				{
					_aACreatedUser = value;
					NotifyChanged("AACreatedUser");
				}
			}
		}
		public DateTime AACreatedDate
		{
			get { return _aACreatedDate; }
			set
			{
				if (value != this._aACreatedDate)
				{
					_aACreatedDate = value;
					NotifyChanged("AACreatedDate");
				}
			}
		}
		public String AAUpdatedUser
		{
			get { return _aAUpdatedUser; }
			set
			{
				if (value != this._aAUpdatedUser)
				{
					_aAUpdatedUser = value;
					NotifyChanged("AAUpdatedUser");
				}
			}
		}
		public DateTime AAUpdatedDate
		{
			get { return _aAUpdatedDate; }
			set
			{
				if (value != this._aAUpdatedDate)
				{
					_aAUpdatedDate = value;
					NotifyChanged("AAUpdatedDate");
				}
			}
		}
		public bool MEEmrTypeIsTmp
		{
			get { return _mEEmrTypeIsTmp; }
			set
			{
				if (value != this._mEEmrTypeIsTmp)
				{
					_mEEmrTypeIsTmp = value;
					NotifyChanged("MEEmrTypeIsTmp");
				}
			}
		}
		public int FK_HRDepartmentID
		{
			get { return _fK_HRDepartmentID; }
			set
			{
				if (value != this._fK_HRDepartmentID)
				{
					_fK_HRDepartmentID = value;
					NotifyChanged("FK_HRDepartmentID");
				}
			}
		}
		public String MEEmrTypeProfile
		{
			get { return _mEEmrTypeProfile; }
			set
			{
				if (value != this._mEEmrTypeProfile)
				{
					_mEEmrTypeProfile = value;
					NotifyChanged("MEEmrTypeProfile");
				}
			}
		}
		public int MEEmrTypeDgtSignatureX
		{
			get { return _mEEmrTypeDgtSignatureX; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureX)
				{
					_mEEmrTypeDgtSignatureX = value;
					NotifyChanged("MEEmrTypeDgtSignatureX");
				}
			}
		}
		public int MEEmrTypeDgtSignatureY
		{
			get { return _mEEmrTypeDgtSignatureY; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureY)
				{
					_mEEmrTypeDgtSignatureY = value;
					NotifyChanged("MEEmrTypeDgtSignatureY");
				}
			}
		}
		public int MEEmrTypeDgtSignatureWidth
		{
			get { return _mEEmrTypeDgtSignatureWidth; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureWidth)
				{
					_mEEmrTypeDgtSignatureWidth = value;
					NotifyChanged("MEEmrTypeDgtSignatureWidth");
				}
			}
		}
		public int MEEmrTypeDgtSignatureHeight
		{
			get { return _mEEmrTypeDgtSignatureHeight; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureHeight)
				{
					_mEEmrTypeDgtSignatureHeight = value;
					NotifyChanged("MEEmrTypeDgtSignatureHeight");
				}
			}
		}
		public int MEEmrTypeDgtSignatureFontSize
		{
			get { return _mEEmrTypeDgtSignatureFontSize; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureFontSize)
				{
					_mEEmrTypeDgtSignatureFontSize = value;
					NotifyChanged("MEEmrTypeDgtSignatureFontSize");
				}
			}
		}
		public int MEEmrTypeDgtSignatureTextColor
		{
			get { return _mEEmrTypeDgtSignatureTextColor; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureTextColor)
				{
					_mEEmrTypeDgtSignatureTextColor = value;
					NotifyChanged("MEEmrTypeDgtSignatureTextColor");
				}
			}
		}
		public int MEEmrTypeDgtSignaturePage
		{
			get { return _mEEmrTypeDgtSignaturePage; }
			set
			{
				if (value != this._mEEmrTypeDgtSignaturePage)
				{
					_mEEmrTypeDgtSignaturePage = value;
					NotifyChanged("MEEmrTypeDgtSignaturePage");
				}
			}
		}
		public bool MEEmrTypeDgtSignatureImage
		{
			get { return _mEEmrTypeDgtSignatureImage; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureImage)
				{
					_mEEmrTypeDgtSignatureImage = value;
					NotifyChanged("MEEmrTypeDgtSignatureImage");
				}
			}
		}
		public bool MEEmrTypeDgtSignatureVisible
		{
			get { return _mEEmrTypeDgtSignatureVisible; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureVisible)
				{
					_mEEmrTypeDgtSignatureVisible = value;
					NotifyChanged("MEEmrTypeDgtSignatureVisible");
				}
			}
		}
		public String MEEmrTypeDgtSignatureReason
		{
			get { return _mEEmrTypeDgtSignatureReason; }
			set
			{
				if (value != this._mEEmrTypeDgtSignatureReason)
				{
					_mEEmrTypeDgtSignatureReason = value;
					NotifyChanged("MEEmrTypeDgtSignatureReason");
				}
			}
		}
		public int MEEmrTypeMaxCountPerPatient
		{
			get { return _mEEmrTypeMaxCountPerPatient; }
			set
			{
				if (value != this._mEEmrTypeMaxCountPerPatient)
				{
					_mEEmrTypeMaxCountPerPatient = value;
					NotifyChanged("MEEmrTypeMaxCountPerPatient");
				}
			}
		}
		public bool MEEmrTypeFilterTemplate
		{
			get { return _mEEmrTypeFilterTemplate; }
			set
			{
				if (value != this._mEEmrTypeFilterTemplate)
				{
					_mEEmrTypeFilterTemplate = value;
					NotifyChanged("MEEmrTypeFilterTemplate");
				}
			}
		}
		public bool MEEmrTypeOneEmrOnePhase
		{
			get { return _mEEmrTypeOneEmrOnePhase; }
			set
			{
				if (value != this._mEEmrTypeOneEmrOnePhase)
				{
					_mEEmrTypeOneEmrOnePhase = value;
					NotifyChanged("MEEmrTypeOneEmrOnePhase");
				}
			}
		}

		#endregion
	}
	#endregion
}