using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEMedicineComponents
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEMedicineComponentsInfo
    //Created Date:Thursday, February 17, 2011
    //-----------------------------------------------------------

    public class MEMedicineComponentsInfo : BusinessObject
    {
        public MEMedicineComponentsInfo()
        {
        }
        #region Variables
        protected int _mEMedicineComponentID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MEComponentID;
        protected int _fK_ICProductID;
        protected String _mEMedicineComponentConcentration = String.Empty;
        #endregion

        #region Public properties
        public int MEMedicineComponentID
        {
            get { return _mEMedicineComponentID; }
            set
            {
                if (value != this._mEMedicineComponentID)
                {
                    _mEMedicineComponentID = value;
                    NotifyChanged("MEMedicineComponentID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MEComponentID
        {
            get { return _fK_MEComponentID; }
            set
            {
                if (value != this._fK_MEComponentID)
                {
                    _fK_MEComponentID = value;
                    NotifyChanged("FK_MEComponentID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public String MEMedicineComponentConcentration
        {
            get { return _mEMedicineComponentConcentration; }
            set
            {
                if (value != this._mEMedicineComponentConcentration)
                {
                    _mEMedicineComponentConcentration = value;
                    NotifyChanged("MEMedicineComponentConcentration");
                }
            }
        }
        #endregion

        #region Extra properties
        public string MEComponentName { get; set; }
        #endregion
    }
    #endregion
}