using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region MEVisitLabs
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:MEVisitLabsInfo
    //Created Date:Tuesday, March 08, 2011
    //-----------------------------------------------------------

    public class MEVisitLabsInfo : BusinessObject
    {
        public MEVisitLabsInfo()
        {
        }
        #region Variables
        protected int _mEVisitLabID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_MEPatientVisitID;
        protected int _fK_MELabID;
        protected int _fK_MEPatientID;
        protected int _fK_HREmployeeID;
        protected DateTime _mEVisitLabDate = DateTime.MaxValue;
        protected DateTime _mEVisitLabReturnDate = DateTime.MaxValue;
        protected String _mEVisitLabReturnMethod = String.Empty;
        protected String _mEVisitLabRemark = String.Empty;
        protected String _mEVisitLabStatus = DefaultStatus;
        protected String _mEVisitLabsBarcode = String.Empty;
        protected String _mEVisitLabSentStatus = DefaultStatus;
        #endregion

        #region Public properties
        public int MEVisitLabID
        {
            get { return _mEVisitLabID; }
            set
            {
                if (value != this._mEVisitLabID)
                {
                    _mEVisitLabID = value;
                    NotifyChanged("MEVisitLabID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_MEPatientVisitID
        {
            get { return _fK_MEPatientVisitID; }
            set
            {
                if (value != this._fK_MEPatientVisitID)
                {
                    _fK_MEPatientVisitID = value;
                    NotifyChanged("FK_MEPatientVisitID");
                }
            }
        }
        public int FK_MELabID
        {
            get { return _fK_MELabID; }
            set
            {
                if (value != this._fK_MELabID)
                {
                    _fK_MELabID = value;
                    NotifyChanged("FK_MELabID");
                }
            }
        }
        public int FK_MEPatientID
        {
            get { return _fK_MEPatientID; }
            set
            {
                if (value != this._fK_MEPatientID)
                {
                    _fK_MEPatientID = value;
                    NotifyChanged("FK_MEPatientID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public DateTime MEVisitLabDate
        {
            get { return _mEVisitLabDate; }
            set
            {
                if (value != this._mEVisitLabDate)
                {
                    _mEVisitLabDate = value;
                    NotifyChanged("MEVisitLabDate");
                }
            }
        }
        public DateTime MEVisitLabReturnDate
        {
            get { return _mEVisitLabReturnDate; }
            set
            {
                if (value != this._mEVisitLabReturnDate)
                {
                    _mEVisitLabReturnDate = value;
                    NotifyChanged("MEVisitLabReturnDate");
                }
            }
        }
        public String MEVisitLabReturnMethod
        {
            get { return _mEVisitLabReturnMethod; }
            set
            {
                if (value != this._mEVisitLabReturnMethod)
                {
                    _mEVisitLabReturnMethod = value;
                    NotifyChanged("MEVisitLabReturnMethod");
                }
            }
        }
        public String MEVisitLabRemark
        {
            get { return _mEVisitLabRemark; }
            set
            {
                if (value != this._mEVisitLabRemark)
                {
                    _mEVisitLabRemark = value;
                    NotifyChanged("MEVisitLabRemark");
                }
            }
        }
        public String MEVisitLabStatus
        {
            get { return _mEVisitLabStatus; }
            set
            {
                if (value != this._mEVisitLabStatus)
                {
                    _mEVisitLabStatus = value;
                    NotifyChanged("MEVisitLabStatus");
                }
            }
        }
        public String MEVisitLabsBarcode
        {
            get { return _mEVisitLabsBarcode; }
            set
            {
                if (value != this._mEVisitLabsBarcode)
                {
                    _mEVisitLabsBarcode = value;
                    NotifyChanged("MEVisitLabsBarcode");
                }
            }
        }
        public String MEVisitLabSentStatus
        {
            get { return _mEVisitLabSentStatus; }
            set
            {
                if (value != this._mEVisitLabSentStatus)
                {
                    _mEVisitLabSentStatus = value;
                    NotifyChanged("MEVisitLabSentStatus");
                }
            }
        }
        #endregion



        #region Extra Properties
         public String MELabName { get; set ;}
         public string MEVisitLabParamValue { get; set; }
         public String MELabID { get; set; }
        #endregion

    }
    #endregion
}