using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ICReceiptComponentItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICReceiptComponentItemsInfo
    //Created Date:Friday, November 18, 2011
    //-----------------------------------------------------------

    public class ICReceiptComponentItemsInfo : BusinessObject
    {
        public ICReceiptComponentItemsInfo()
        {
            IsPackageGroup = false;
        }

        #region Variables
        protected int _iCReceiptComponentItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICReceiptItemID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_ICStockID;
        protected String _iCReceiptComponentItemProductSupplierNo = String.Empty;
        protected String _iCReceiptComponentItemProductName = String.Empty;
        protected String _iCReceiptComponentItemProductDesc = String.Empty;
        protected String _iCReceiptComponentItemProductAttribute = String.Empty;
        protected String _iCReceiptComponentItemType = String.Empty;
        protected double _iCReceiptComponentItemPackageQty;
        protected double _iCReceiptComponentItemProductQty;
        protected bool _isPackageGroup = true;
        #endregion

        #region Public properties
        public int ICReceiptComponentItemID
        {
            get { return _iCReceiptComponentItemID; }
            set
            {
                if (value != this._iCReceiptComponentItemID)
                {
                    _iCReceiptComponentItemID = value;
                    NotifyChanged("ICReceiptComponentItemID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ICReceiptItemID
        {
            get { return _fK_ICReceiptItemID; }
            set
            {
                if (value != this._fK_ICReceiptItemID)
                {
                    _fK_ICReceiptItemID = value;
                    NotifyChanged("FK_ICReceiptItemID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public String ICReceiptComponentItemProductSupplierNo
        {
            get { return _iCReceiptComponentItemProductSupplierNo; }
            set
            {
                if (value != this._iCReceiptComponentItemProductSupplierNo)
                {
                    _iCReceiptComponentItemProductSupplierNo = value;
                    NotifyChanged("ICReceiptComponentItemProductSupplierNo");
                }
            }
        }
        public String ICReceiptComponentItemProductName
        {
            get { return _iCReceiptComponentItemProductName; }
            set
            {
                if (value != this._iCReceiptComponentItemProductName)
                {
                    _iCReceiptComponentItemProductName = value;
                    NotifyChanged("ICReceiptComponentItemProductName");
                }
            }
        }
        public String ICReceiptComponentItemProductDesc
        {
            get { return _iCReceiptComponentItemProductDesc; }
            set
            {
                if (value != this._iCReceiptComponentItemProductDesc)
                {
                    _iCReceiptComponentItemProductDesc = value;
                    NotifyChanged("ICReceiptComponentItemProductDesc");
                }
            }
        }
        public String ICReceiptComponentItemProductAttribute
        {
            get { return _iCReceiptComponentItemProductAttribute; }
            set
            {
                if (value != this._iCReceiptComponentItemProductAttribute)
                {
                    _iCReceiptComponentItemProductAttribute = value;
                    NotifyChanged("ICReceiptComponentItemProductAttribute");
                }
            }
        }
        public String ICReceiptComponentItemType
        {
            get { return _iCReceiptComponentItemType; }
            set
            {
                if (value != this._iCReceiptComponentItemType)
                {
                    _iCReceiptComponentItemType = value;
                    NotifyChanged("ICReceiptComponentItemType");
                }
            }
        }
        public double ICReceiptComponentItemPackageQty
        {
            get { return _iCReceiptComponentItemPackageQty; }
            set
            {
                if (value != this._iCReceiptComponentItemPackageQty)
                {
                    _iCReceiptComponentItemPackageQty = value;
                    NotifyChanged("ICReceiptComponentItemPackageQty");
                }
            }
        }
        public double ICReceiptComponentItemProductQty
        {
            get { return _iCReceiptComponentItemProductQty; }
            set
            {
                if (value != this._iCReceiptComponentItemProductQty)
                {
                    _iCReceiptComponentItemProductQty = value;
                    NotifyChanged("ICReceiptComponentItemProductQty");
                }
            }
        }
        public bool IsPackageGroup
        {
            get { return _isPackageGroup; }
            set
            {
                if (value != this._isPackageGroup)
                {
                    _isPackageGroup = value;
                    NotifyChanged("IsPackageGroup");
                }
            }
        }
        #endregion

        #region Extra Properties
        public double ICProductComponentQty { get; set; }
        /// <summary>
        /// Gets or sets the package list associating with the item
        /// </summary>
        public IBOSList<ICReceiptItemPackagesInfo> ReceiptItemPackageList { get; set; }
        #endregion
    }
    #endregion
}