using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ICReceipts
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICReceiptsInfo
    //Created Date:Monday, March 15, 2010
    //-----------------------------------------------------------

    public class ICReceiptsInfo : BusinessObject
    {
        public ICReceiptsInfo()
        {
            IsTransferred = false;
            ReceiptDateFrom = BOSUtil.GetYearBeginDate();
            ReceiptDateTo = BOSUtil.GetYearEndDate();
        }

        #region Variables
        protected int _iCReceiptID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_HREmployeeID;
        protected int _fK_GELanguageID;
        protected int _fK_GECurrencyID;
        protected int _fK_APSupplierID;
        protected int _fK_ACObjectID;
        protected int _fK_ICStockID;
        protected int _fK_ICStockSlotID;
        protected int _fK_GEShippingMethodID;
        protected int _fK_BRBranchID;
        protected int _fK_BRTransferredBranchID;
        protected String _iCReceiptNo = String.Empty;
        protected String _iCReceiptName = String.Empty;
        protected String _iCReceiptDesc = String.Empty;
        protected String _iCReceiptComment = String.Empty;
        protected String _iCReceiptPackNo = String.Empty;
        protected DateTime _iCReceiptDate = DateTime.MaxValue;
        protected DateTime _iCReceiptValidateDate = DateTime.MaxValue;
        protected DateTime _iCReceiptDeliveryDate = DateTime.MaxValue;
        protected double _iCReceiptDiscountPerCent;
        protected double _iCReceiptDiscountFix;
        protected String _iCReceiptReference = String.Empty;
        protected bool _iCReceiptActiveCheck = true;
        protected String _iCReceiptTaxNumber = String.Empty;
        protected String _iCReceiptTypeCombo = String.Empty;
        protected String _iCReceiptStatus = DefaultStatus;
        protected double _iCReceiptTaxPercent;
        protected double _iCReceiptTaxAmount;
        protected double _iCReceiptSubTotalCost;
        protected double _iCReceiptTotalCost;
        protected String _iCReceiptMatchCode01Combo = String.Empty;
        protected String _iCReceiptMatchCode02Combo = String.Empty;
        protected String _iCReceiptMatchCode03Combo = String.Empty;
        protected String _iCReceiptMatchCode04Combo = String.Empty;
        protected String _iCReceiptMatchCode05Combo = String.Empty;
        protected String _iCReceiptMatchCode06Combo = String.Empty;
        protected String _iCReceiptMatchCode07Combo = String.Empty;
        protected String _iCReceiptMatchCode08Combo = String.Empty;
        protected String _iCReceiptMatchCode09Combo = String.Empty;
        protected String _iCReceiptMatchCode10Combo = String.Empty;
        protected String _iCReceiptMatchCode11Combo = String.Empty;
        protected String _iCReceiptMatchCode12Combo = String.Empty;
        protected String _iCReceiptProject = String.Empty;
        protected int _fK_APSupplierContactInvoiceID;
        protected String _iCReceiptInvoiceContactName = String.Empty;
        protected String _iCReceiptInvoiceContactFirstName = String.Empty;
        protected String _iCReceiptInvoiceContactLastName = String.Empty;
        protected String _iCReceiptInvoiceContactTitle = String.Empty;
        protected String _iCReceiptInvoiceContactHeaderLetter = String.Empty;
        protected String _iCReceiptInvoiceContactHeaderMessage = String.Empty;
        protected String _iCReceiptInvoiceContactEmail1 = String.Empty;
        protected String _iCReceiptInvoiceContactEmail2 = String.Empty;
        protected String _iCReceiptInvoiceContactWebsite = String.Empty;
        protected String _iCReceiptInvoiceContactPhonePrivate = String.Empty;
        protected String _iCReceiptInvoiceContactPhone = String.Empty;
        protected String _iCReceiptInvoiceContactPhone1 = String.Empty;
        protected String _iCReceiptInvoiceContactCellPhone = String.Empty;
        protected String _iCReceiptInvoiceContactCellPhone1 = String.Empty;
        protected String _iCReceiptInvoiceContactFax = String.Empty;
        protected String _iCReceiptInvoiceContactType = String.Empty;
        protected String _iCReceiptInvoiceContactInformation = String.Empty;
        protected String _iCReceiptInvoiceContactDepartment = String.Empty;
        protected String _iCReceiptInvoiceContactRoom = String.Empty;
        protected String _iCReceiptInvoiceAddressLine1 = String.Empty;
        protected String _iCReceiptInvoiceAddressLine2 = String.Empty;
        protected String _iCReceiptInvoiceAddressLine3 = String.Empty;
        protected String _iCReceiptInvoiceAddressStreet = String.Empty;
        protected String _iCReceiptInvoiceAddressCity = String.Empty;
        protected String _iCReceiptInvoiceAddressPostalCode = String.Empty;
        protected String _iCReceiptInvoiceAddressStateProvince = String.Empty;
        protected String _iCReceiptInvoiceAddressZipCode = String.Empty;
        protected String _iCReceiptInvoiceAddressCountry = String.Empty;
        protected int _fK_APSupplierContactPOID;
        protected String _iCReceiptPOContactName = String.Empty;
        protected DateTime _iCReceiptPOContactBirthday = DateTime.MaxValue;
        protected String _iCReceiptPOContactFirstName = String.Empty;
        protected String _iCReceiptPOContactLastName = String.Empty;
        protected String _iCReceiptPOContactTitle = String.Empty;
        protected String _iCReceiptPOContactHeaderLetter = String.Empty;
        protected String _iCReceiptPOContactHeaderMessage = String.Empty;
        protected String _iCReceiptPOContactEmail1 = String.Empty;
        protected String _iCReceiptPOContactEmail2 = String.Empty;
        protected String _iCReceiptPOContactWebsite = String.Empty;
        protected String _iCReceiptPOContactPhonePrivate = String.Empty;
        protected String _iCReceiptPOContactPhone = String.Empty;
        protected String _iCReceiptPOContactPhone1 = String.Empty;
        protected String _iCReceiptPOContactCellPhone = String.Empty;
        protected String _iCReceiptPOContactCellPhone1 = String.Empty;
        protected String _iCReceiptPOContactFax = String.Empty;
        protected String _iCReceiptPOContactType = String.Empty;
        protected String _iCReceiptPOContactInformation = String.Empty;
        protected String _iCReceiptPOContactDepartment = String.Empty;
        protected String _iCReceiptPOContactRoom = String.Empty;
        protected String _iCReceiptPOAddressLine1 = String.Empty;
        protected String _iCReceiptPOAddressLine2 = String.Empty;
        protected String _iCReceiptPOAddressLine3 = String.Empty;
        protected String _iCReceiptPOAddressStreet = String.Empty;
        protected String _iCReceiptPOAddressCity = String.Empty;
        protected String _iCReceiptPOAddressPostalCode = String.Empty;
        protected String _iCReceiptPOAddressStateProvince = String.Empty;
        protected String _iCReceiptPOAddressZipCode = String.Empty;
        protected String _iCReceiptPOAddressCountry = String.Empty;
        protected String _iCReceiptDeliveryContactName = String.Empty;
        protected DateTime _iCReceiptDeliveryContactBirthday = DateTime.MaxValue;
        protected String _iCReceiptDeliveryContactFirstName = String.Empty;
        protected String _iCReceiptDeliveryContactLastName = String.Empty;
        protected String _iCReceiptDeliveryContactTitle = String.Empty;
        protected String _iCReceiptDeliveryContactHeaderLetter = String.Empty;
        protected String _iCReceiptDeliveryContactHeaderMessage = String.Empty;
        protected String _iCReceiptDeliveryContactEmail1 = String.Empty;
        protected String _iCReceiptDeliveryContactEmail2 = String.Empty;
        protected String _iCReceiptDeliveryContactWebsite = String.Empty;
        protected String _iCReceiptDeliveryContactPhonePrivate = String.Empty;
        protected String _iCReceiptDeliveryContactPhone = String.Empty;
        protected String _iCReceiptDeliveryContactPhone1 = String.Empty;
        protected String _iCReceiptDeliveryContactCellPhone = String.Empty;
        protected String _iCReceiptDeliveryContactCellPhone1 = String.Empty;
        protected String _iCReceiptDeliveryContactFax = String.Empty;
        protected String _iCReceiptDeliveryContactType = String.Empty;
        protected String _iCReceiptDeliveryContactInformation = String.Empty;
        protected String _iCReceiptDeliveryContactDepartment = String.Empty;
        protected String _iCReceiptDeliveryContactRoom = String.Empty;
        protected String _iCReceiptDeliveryAddressLine1 = String.Empty;
        protected String _iCReceiptDeliveryAddressLine2 = String.Empty;
        protected String _iCReceiptDeliveryAddressLine3 = String.Empty;
        protected String _iCReceiptDeliveryAddressStreet = String.Empty;
        protected String _iCReceiptDeliveryAddressCity = String.Empty;
        protected String _iCReceiptDeliveryAddressPostalCode = String.Empty;
        protected String _iCReceiptDeliveryAddressStateProvince = String.Empty;
        protected String _iCReceiptDeliveryAddressZipCode = String.Empty;
        protected String _iCReceiptDeliveryAddressCountry = String.Empty;
        protected double _iCReceiptShippingFees;
        protected double _iCReceiptShippingExtraFees;
        protected double _iCReceiptShippingInsuranceFees;
        protected double _iCReceiptShippingPackagingFees;
        protected double _iCReceiptShippingReservedFees1;
        protected double _iCReceiptShippingReservedFees2;
        protected double _iCReceiptShippingReservedFees3;
        protected double _iCReceiptShippingReservedFees4;
        protected String _iCReceiptShippingMethodDesc = String.Empty;
        protected String _iCReceiptShippingMethodName = String.Empty;
        protected String _iCReceiptInvoiceInNo = String.Empty;
        protected DateTime _iCReceiptInvoiceInDate = DateTime.MaxValue;
        protected double _iCReceiptExchangeRate;
        protected bool _isTransferred = true;
        protected DateTime _iCReceiptTransferredDate = DateTime.MaxValue;
        protected String _iCObjectType = String.Empty;
        protected String _iCReceiptFormNo = String.Empty;
        protected String _iCReceiptSymbol = String.Empty;
        protected String _iCVATDocumentNo = String.Empty;
        protected String _iCInputDocumentType = String.Empty;
        protected int _fK_ACSegmentID;
        #endregion

        #region Public properties
        public int ICReceiptID
        {
            get { return _iCReceiptID; }
            set
            {
                if (value != this._iCReceiptID)
                {
                    _iCReceiptID = value;
                    NotifyChanged("ICReceiptID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_GELanguageID
        {
            get { return _fK_GELanguageID; }
            set
            {
                if (value != this._fK_GELanguageID)
                {
                    _fK_GELanguageID = value;
                    NotifyChanged("FK_GELanguageID");
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                    NotifyChanged("FK_GECurrencyID");
                }
            }
        }
        public int FK_APSupplierID
        {
            get { return _fK_APSupplierID; }
            set
            {
                if (value != this._fK_APSupplierID)
                {
                    _fK_APSupplierID = value;
                    NotifyChanged("FK_APSupplierID");
                }
            }
        }
        public int FK_ACObjectID
        {
            get { return _fK_ACObjectID; }
            set
            {
                if (value != this._fK_ACObjectID)
                {
                    _fK_ACObjectID = value;
                    NotifyChanged("FK_ACObjectID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ICStockSlotID
        {
            get { return _fK_ICStockSlotID; }
            set
            {
                if (value != this._fK_ICStockSlotID)
                {
                    _fK_ICStockSlotID = value;
                    NotifyChanged("FK_ICStockSlotID");
                }
            }
        }
        public int FK_GEShippingMethodID
        {
            get { return _fK_GEShippingMethodID; }
            set
            {
                if (value != this._fK_GEShippingMethodID)
                {
                    _fK_GEShippingMethodID = value;
                    NotifyChanged("FK_GEShippingMethodID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public int FK_BRTransferredBranchID
        {
            get { return _fK_BRTransferredBranchID; }
            set
            {
                if (value != this._fK_BRTransferredBranchID)
                {
                    _fK_BRTransferredBranchID = value;
                    NotifyChanged("FK_BRTransferredBranchID");
                }
            }
        }
        public String ICReceiptNo
        {
            get { return _iCReceiptNo; }
            set
            {
                if (value != this._iCReceiptNo)
                {
                    _iCReceiptNo = value;
                    NotifyChanged("ICReceiptNo");
                }
            }
        }
        public String ICReceiptName
        {
            get { return _iCReceiptName; }
            set
            {
                if (value != this._iCReceiptName)
                {
                    _iCReceiptName = value;
                    NotifyChanged("ICReceiptName");
                }
            }
        }
        public String ICReceiptDesc
        {
            get { return _iCReceiptDesc; }
            set
            {
                if (value != this._iCReceiptDesc)
                {
                    _iCReceiptDesc = value;
                    NotifyChanged("ICReceiptDesc");
                }
            }
        }
        public String ICReceiptComment
        {
            get { return _iCReceiptComment; }
            set
            {
                if (value != this._iCReceiptComment)
                {
                    _iCReceiptComment = value;
                    NotifyChanged("ICReceiptComment");
                }
            }
        }
        public String ICReceiptPackNo
        {
            get { return _iCReceiptPackNo; }
            set
            {
                if (value != this._iCReceiptPackNo)
                {
                    _iCReceiptPackNo = value;
                    NotifyChanged("ICReceiptPackNo");
                }
            }
        }
        public DateTime ICReceiptDate
        {
            get { return _iCReceiptDate; }
            set
            {
                if (value != this._iCReceiptDate)
                {
                    _iCReceiptDate = value;
                    NotifyChanged("ICReceiptDate");
                }
            }
        }
        public DateTime ICReceiptValidateDate
        {
            get { return _iCReceiptValidateDate; }
            set
            {
                if (value != this._iCReceiptValidateDate)
                {
                    _iCReceiptValidateDate = value;
                    NotifyChanged("ICReceiptValidateDate");
                }
            }
        }
        public DateTime ICReceiptDeliveryDate
        {
            get { return _iCReceiptDeliveryDate; }
            set
            {
                if (value != this._iCReceiptDeliveryDate)
                {
                    _iCReceiptDeliveryDate = value;
                    NotifyChanged("ICReceiptDeliveryDate");
                }
            }
        }
        public double ICReceiptDiscountPerCent
        {
            get { return _iCReceiptDiscountPerCent; }
            set
            {
                if (value != this._iCReceiptDiscountPerCent)
                {
                    _iCReceiptDiscountPerCent = value;
                    NotifyChanged("ICReceiptDiscountPerCent");
                }
            }
        }
        public double ICReceiptDiscountFix
        {
            get { return _iCReceiptDiscountFix; }
            set
            {
                if (value != this._iCReceiptDiscountFix)
                {
                    _iCReceiptDiscountFix = value;
                    NotifyChanged("ICReceiptDiscountFix");
                }
            }
        }
        public String ICReceiptReference
        {
            get { return _iCReceiptReference; }
            set
            {
                if (value != this._iCReceiptReference)
                {
                    _iCReceiptReference = value;
                    NotifyChanged("ICReceiptReference");
                }
            }
        }
        public bool ICReceiptActiveCheck
        {
            get { return _iCReceiptActiveCheck; }
            set
            {
                if (value != this._iCReceiptActiveCheck)
                {
                    _iCReceiptActiveCheck = value;
                    NotifyChanged("ICReceiptActiveCheck");
                }
            }
        }
        public String ICReceiptTaxNumber
        {
            get { return _iCReceiptTaxNumber; }
            set
            {
                if (value != this._iCReceiptTaxNumber)
                {
                    _iCReceiptTaxNumber = value;
                    NotifyChanged("ICReceiptTaxNumber");
                }
            }
        }
        public String ICReceiptTypeCombo
        {
            get { return _iCReceiptTypeCombo; }
            set
            {
                if (value != this._iCReceiptTypeCombo)
                {
                    _iCReceiptTypeCombo = value;
                    NotifyChanged("ICReceiptTypeCombo");
                }
            }
        }
        public String ICReceiptStatus
        {
            get { return _iCReceiptStatus; }
            set
            {
                if (value != this._iCReceiptStatus)
                {
                    _iCReceiptStatus = value;
                    NotifyChanged("ICReceiptStatus");
                }
            }
        }
        public double ICReceiptTaxPercent
        {
            get { return _iCReceiptTaxPercent; }
            set
            {
                if (value != this._iCReceiptTaxPercent)
                {
                    _iCReceiptTaxPercent = value;
                    NotifyChanged("ICReceiptTaxPercent");
                }
            }
        }
        public double ICReceiptTaxAmount
        {
            get { return _iCReceiptTaxAmount; }
            set
            {
                if (value != this._iCReceiptTaxAmount)
                {
                    _iCReceiptTaxAmount = value;
                    NotifyChanged("ICReceiptTaxAmount");
                }
            }
        }
        public double ICReceiptSubTotalCost
        {
            get { return _iCReceiptSubTotalCost; }
            set
            {
                if (value != this._iCReceiptSubTotalCost)
                {
                    _iCReceiptSubTotalCost = value;
                    NotifyChanged("ICReceiptSubTotalCost");
                }
            }
        }
        public double ICReceiptTotalCost
        {
            get { return _iCReceiptTotalCost; }
            set
            {
                if (value != this._iCReceiptTotalCost)
                {
                    _iCReceiptTotalCost = value;
                    NotifyChanged("ICReceiptTotalCost");
                }
            }
        }
        public String ICReceiptMatchCode01Combo
        {
            get { return _iCReceiptMatchCode01Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode01Combo)
                {
                    _iCReceiptMatchCode01Combo = value;
                    NotifyChanged("ICReceiptMatchCode01Combo");
                }
            }
        }
        public String ICReceiptMatchCode02Combo
        {
            get { return _iCReceiptMatchCode02Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode02Combo)
                {
                    _iCReceiptMatchCode02Combo = value;
                    NotifyChanged("ICReceiptMatchCode02Combo");
                }
            }
        }
        public String ICReceiptMatchCode03Combo
        {
            get { return _iCReceiptMatchCode03Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode03Combo)
                {
                    _iCReceiptMatchCode03Combo = value;
                    NotifyChanged("ICReceiptMatchCode03Combo");
                }
            }
        }
        public String ICReceiptMatchCode04Combo
        {
            get { return _iCReceiptMatchCode04Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode04Combo)
                {
                    _iCReceiptMatchCode04Combo = value;
                    NotifyChanged("ICReceiptMatchCode04Combo");
                }
            }
        }
        public String ICReceiptMatchCode05Combo
        {
            get { return _iCReceiptMatchCode05Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode05Combo)
                {
                    _iCReceiptMatchCode05Combo = value;
                    NotifyChanged("ICReceiptMatchCode05Combo");
                }
            }
        }
        public String ICReceiptMatchCode06Combo
        {
            get { return _iCReceiptMatchCode06Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode06Combo)
                {
                    _iCReceiptMatchCode06Combo = value;
                    NotifyChanged("ICReceiptMatchCode06Combo");
                }
            }
        }
        public String ICReceiptMatchCode07Combo
        {
            get { return _iCReceiptMatchCode07Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode07Combo)
                {
                    _iCReceiptMatchCode07Combo = value;
                    NotifyChanged("ICReceiptMatchCode07Combo");
                }
            }
        }
        public String ICReceiptMatchCode08Combo
        {
            get { return _iCReceiptMatchCode08Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode08Combo)
                {
                    _iCReceiptMatchCode08Combo = value;
                    NotifyChanged("ICReceiptMatchCode08Combo");
                }
            }
        }
        public String ICReceiptMatchCode09Combo
        {
            get { return _iCReceiptMatchCode09Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode09Combo)
                {
                    _iCReceiptMatchCode09Combo = value;
                    NotifyChanged("ICReceiptMatchCode09Combo");
                }
            }
        }
        public String ICReceiptMatchCode10Combo
        {
            get { return _iCReceiptMatchCode10Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode10Combo)
                {
                    _iCReceiptMatchCode10Combo = value;
                    NotifyChanged("ICReceiptMatchCode10Combo");
                }
            }
        }
        public String ICReceiptMatchCode11Combo
        {
            get { return _iCReceiptMatchCode11Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode11Combo)
                {
                    _iCReceiptMatchCode11Combo = value;
                    NotifyChanged("ICReceiptMatchCode11Combo");
                }
            }
        }
        public String ICReceiptMatchCode12Combo
        {
            get { return _iCReceiptMatchCode12Combo; }
            set
            {
                if (value != this._iCReceiptMatchCode12Combo)
                {
                    _iCReceiptMatchCode12Combo = value;
                    NotifyChanged("ICReceiptMatchCode12Combo");
                }
            }
        }
        public String ICReceiptProject
        {
            get { return _iCReceiptProject; }
            set
            {
                if (value != this._iCReceiptProject)
                {
                    _iCReceiptProject = value;
                    NotifyChanged("ICReceiptProject");
                }
            }
        }
        public int FK_APSupplierContactInvoiceID
        {
            get { return _fK_APSupplierContactInvoiceID; }
            set
            {
                if (value != this._fK_APSupplierContactInvoiceID)
                {
                    _fK_APSupplierContactInvoiceID = value;
                    NotifyChanged("FK_APSupplierContactInvoiceID");
                }
            }
        }
        public String ICReceiptInvoiceContactName
        {
            get { return _iCReceiptInvoiceContactName; }
            set
            {
                if (value != this._iCReceiptInvoiceContactName)
                {
                    _iCReceiptInvoiceContactName = value;
                    NotifyChanged("ICReceiptInvoiceContactName");
                }
            }
        }
        public String ICReceiptInvoiceContactFirstName
        {
            get { return _iCReceiptInvoiceContactFirstName; }
            set
            {
                if (value != this._iCReceiptInvoiceContactFirstName)
                {
                    _iCReceiptInvoiceContactFirstName = value;
                    NotifyChanged("ICReceiptInvoiceContactFirstName");
                }
            }
        }
        public String ICReceiptInvoiceContactLastName
        {
            get { return _iCReceiptInvoiceContactLastName; }
            set
            {
                if (value != this._iCReceiptInvoiceContactLastName)
                {
                    _iCReceiptInvoiceContactLastName = value;
                    NotifyChanged("ICReceiptInvoiceContactLastName");
                }
            }
        }
        public String ICReceiptInvoiceContactTitle
        {
            get { return _iCReceiptInvoiceContactTitle; }
            set
            {
                if (value != this._iCReceiptInvoiceContactTitle)
                {
                    _iCReceiptInvoiceContactTitle = value;
                    NotifyChanged("ICReceiptInvoiceContactTitle");
                }
            }
        }
        public String ICReceiptInvoiceContactHeaderLetter
        {
            get { return _iCReceiptInvoiceContactHeaderLetter; }
            set
            {
                if (value != this._iCReceiptInvoiceContactHeaderLetter)
                {
                    _iCReceiptInvoiceContactHeaderLetter = value;
                    NotifyChanged("ICReceiptInvoiceContactHeaderLetter");
                }
            }
        }
        public String ICReceiptInvoiceContactHeaderMessage
        {
            get { return _iCReceiptInvoiceContactHeaderMessage; }
            set
            {
                if (value != this._iCReceiptInvoiceContactHeaderMessage)
                {
                    _iCReceiptInvoiceContactHeaderMessage = value;
                    NotifyChanged("ICReceiptInvoiceContactHeaderMessage");
                }
            }
        }
        public String ICReceiptInvoiceContactEmail1
        {
            get { return _iCReceiptInvoiceContactEmail1; }
            set
            {
                if (value != this._iCReceiptInvoiceContactEmail1)
                {
                    _iCReceiptInvoiceContactEmail1 = value;
                    NotifyChanged("ICReceiptInvoiceContactEmail1");
                }
            }
        }
        public String ICReceiptInvoiceContactEmail2
        {
            get { return _iCReceiptInvoiceContactEmail2; }
            set
            {
                if (value != this._iCReceiptInvoiceContactEmail2)
                {
                    _iCReceiptInvoiceContactEmail2 = value;
                    NotifyChanged("ICReceiptInvoiceContactEmail2");
                }
            }
        }
        public String ICReceiptInvoiceContactWebsite
        {
            get { return _iCReceiptInvoiceContactWebsite; }
            set
            {
                if (value != this._iCReceiptInvoiceContactWebsite)
                {
                    _iCReceiptInvoiceContactWebsite = value;
                    NotifyChanged("ICReceiptInvoiceContactWebsite");
                }
            }
        }
        public String ICReceiptInvoiceContactPhonePrivate
        {
            get { return _iCReceiptInvoiceContactPhonePrivate; }
            set
            {
                if (value != this._iCReceiptInvoiceContactPhonePrivate)
                {
                    _iCReceiptInvoiceContactPhonePrivate = value;
                    NotifyChanged("ICReceiptInvoiceContactPhonePrivate");
                }
            }
        }
        public String ICReceiptInvoiceContactPhone
        {
            get { return _iCReceiptInvoiceContactPhone; }
            set
            {
                if (value != this._iCReceiptInvoiceContactPhone)
                {
                    _iCReceiptInvoiceContactPhone = value;
                    NotifyChanged("ICReceiptInvoiceContactPhone");
                }
            }
        }
        public String ICReceiptInvoiceContactPhone1
        {
            get { return _iCReceiptInvoiceContactPhone1; }
            set
            {
                if (value != this._iCReceiptInvoiceContactPhone1)
                {
                    _iCReceiptInvoiceContactPhone1 = value;
                    NotifyChanged("ICReceiptInvoiceContactPhone1");
                }
            }
        }
        public String ICReceiptInvoiceContactCellPhone
        {
            get { return _iCReceiptInvoiceContactCellPhone; }
            set
            {
                if (value != this._iCReceiptInvoiceContactCellPhone)
                {
                    _iCReceiptInvoiceContactCellPhone = value;
                    NotifyChanged("ICReceiptInvoiceContactCellPhone");
                }
            }
        }
        public String ICReceiptInvoiceContactCellPhone1
        {
            get { return _iCReceiptInvoiceContactCellPhone1; }
            set
            {
                if (value != this._iCReceiptInvoiceContactCellPhone1)
                {
                    _iCReceiptInvoiceContactCellPhone1 = value;
                    NotifyChanged("ICReceiptInvoiceContactCellPhone1");
                }
            }
        }
        public String ICReceiptInvoiceContactFax
        {
            get { return _iCReceiptInvoiceContactFax; }
            set
            {
                if (value != this._iCReceiptInvoiceContactFax)
                {
                    _iCReceiptInvoiceContactFax = value;
                    NotifyChanged("ICReceiptInvoiceContactFax");
                }
            }
        }
        public String ICReceiptInvoiceContactType
        {
            get { return _iCReceiptInvoiceContactType; }
            set
            {
                if (value != this._iCReceiptInvoiceContactType)
                {
                    _iCReceiptInvoiceContactType = value;
                    NotifyChanged("ICReceiptInvoiceContactType");
                }
            }
        }
        public String ICReceiptInvoiceContactInformation
        {
            get { return _iCReceiptInvoiceContactInformation; }
            set
            {
                if (value != this._iCReceiptInvoiceContactInformation)
                {
                    _iCReceiptInvoiceContactInformation = value;
                    NotifyChanged("ICReceiptInvoiceContactInformation");
                }
            }
        }
        public String ICReceiptInvoiceContactDepartment
        {
            get { return _iCReceiptInvoiceContactDepartment; }
            set
            {
                if (value != this._iCReceiptInvoiceContactDepartment)
                {
                    _iCReceiptInvoiceContactDepartment = value;
                    NotifyChanged("ICReceiptInvoiceContactDepartment");
                }
            }
        }
        public String ICReceiptInvoiceContactRoom
        {
            get { return _iCReceiptInvoiceContactRoom; }
            set
            {
                if (value != this._iCReceiptInvoiceContactRoom)
                {
                    _iCReceiptInvoiceContactRoom = value;
                    NotifyChanged("ICReceiptInvoiceContactRoom");
                }
            }
        }
        public String ICReceiptInvoiceAddressLine1
        {
            get { return _iCReceiptInvoiceAddressLine1; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressLine1)
                {
                    _iCReceiptInvoiceAddressLine1 = value;
                    NotifyChanged("ICReceiptInvoiceAddressLine1");
                }
            }
        }
        public String ICReceiptInvoiceAddressLine2
        {
            get { return _iCReceiptInvoiceAddressLine2; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressLine2)
                {
                    _iCReceiptInvoiceAddressLine2 = value;
                    NotifyChanged("ICReceiptInvoiceAddressLine2");
                }
            }
        }
        public String ICReceiptInvoiceAddressLine3
        {
            get { return _iCReceiptInvoiceAddressLine3; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressLine3)
                {
                    _iCReceiptInvoiceAddressLine3 = value;
                    NotifyChanged("ICReceiptInvoiceAddressLine3");
                }
            }
        }
        public String ICReceiptInvoiceAddressStreet
        {
            get { return _iCReceiptInvoiceAddressStreet; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressStreet)
                {
                    _iCReceiptInvoiceAddressStreet = value;
                    NotifyChanged("ICReceiptInvoiceAddressStreet");
                }
            }
        }
        public String ICReceiptInvoiceAddressCity
        {
            get { return _iCReceiptInvoiceAddressCity; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressCity)
                {
                    _iCReceiptInvoiceAddressCity = value;
                    NotifyChanged("ICReceiptInvoiceAddressCity");
                }
            }
        }
        public String ICReceiptInvoiceAddressPostalCode
        {
            get { return _iCReceiptInvoiceAddressPostalCode; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressPostalCode)
                {
                    _iCReceiptInvoiceAddressPostalCode = value;
                    NotifyChanged("ICReceiptInvoiceAddressPostalCode");
                }
            }
        }
        public String ICReceiptInvoiceAddressStateProvince
        {
            get { return _iCReceiptInvoiceAddressStateProvince; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressStateProvince)
                {
                    _iCReceiptInvoiceAddressStateProvince = value;
                    NotifyChanged("ICReceiptInvoiceAddressStateProvince");
                }
            }
        }
        public String ICReceiptInvoiceAddressZipCode
        {
            get { return _iCReceiptInvoiceAddressZipCode; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressZipCode)
                {
                    _iCReceiptInvoiceAddressZipCode = value;
                    NotifyChanged("ICReceiptInvoiceAddressZipCode");
                }
            }
        }
        public String ICReceiptInvoiceAddressCountry
        {
            get { return _iCReceiptInvoiceAddressCountry; }
            set
            {
                if (value != this._iCReceiptInvoiceAddressCountry)
                {
                    _iCReceiptInvoiceAddressCountry = value;
                    NotifyChanged("ICReceiptInvoiceAddressCountry");
                }
            }
        }
        public int FK_APSupplierContactPOID
        {
            get { return _fK_APSupplierContactPOID; }
            set
            {
                if (value != this._fK_APSupplierContactPOID)
                {
                    _fK_APSupplierContactPOID = value;
                    NotifyChanged("FK_APSupplierContactPOID");
                }
            }
        }
        public String ICReceiptPOContactName
        {
            get { return _iCReceiptPOContactName; }
            set
            {
                if (value != this._iCReceiptPOContactName)
                {
                    _iCReceiptPOContactName = value;
                    NotifyChanged("ICReceiptPOContactName");
                }
            }
        }
        public DateTime ICReceiptPOContactBirthday
        {
            get { return _iCReceiptPOContactBirthday; }
            set
            {
                if (value != this._iCReceiptPOContactBirthday)
                {
                    _iCReceiptPOContactBirthday = value;
                    NotifyChanged("ICReceiptPOContactBirthday");
                }
            }
        }
        public String ICReceiptPOContactFirstName
        {
            get { return _iCReceiptPOContactFirstName; }
            set
            {
                if (value != this._iCReceiptPOContactFirstName)
                {
                    _iCReceiptPOContactFirstName = value;
                    NotifyChanged("ICReceiptPOContactFirstName");
                }
            }
        }
        public String ICReceiptPOContactLastName
        {
            get { return _iCReceiptPOContactLastName; }
            set
            {
                if (value != this._iCReceiptPOContactLastName)
                {
                    _iCReceiptPOContactLastName = value;
                    NotifyChanged("ICReceiptPOContactLastName");
                }
            }
        }
        public String ICReceiptPOContactTitle
        {
            get { return _iCReceiptPOContactTitle; }
            set
            {
                if (value != this._iCReceiptPOContactTitle)
                {
                    _iCReceiptPOContactTitle = value;
                    NotifyChanged("ICReceiptPOContactTitle");
                }
            }
        }
        public String ICReceiptPOContactHeaderLetter
        {
            get { return _iCReceiptPOContactHeaderLetter; }
            set
            {
                if (value != this._iCReceiptPOContactHeaderLetter)
                {
                    _iCReceiptPOContactHeaderLetter = value;
                    NotifyChanged("ICReceiptPOContactHeaderLetter");
                }
            }
        }
        public String ICReceiptPOContactHeaderMessage
        {
            get { return _iCReceiptPOContactHeaderMessage; }
            set
            {
                if (value != this._iCReceiptPOContactHeaderMessage)
                {
                    _iCReceiptPOContactHeaderMessage = value;
                    NotifyChanged("ICReceiptPOContactHeaderMessage");
                }
            }
        }
        public String ICReceiptPOContactEmail1
        {
            get { return _iCReceiptPOContactEmail1; }
            set
            {
                if (value != this._iCReceiptPOContactEmail1)
                {
                    _iCReceiptPOContactEmail1 = value;
                    NotifyChanged("ICReceiptPOContactEmail1");
                }
            }
        }
        public String ICReceiptPOContactEmail2
        {
            get { return _iCReceiptPOContactEmail2; }
            set
            {
                if (value != this._iCReceiptPOContactEmail2)
                {
                    _iCReceiptPOContactEmail2 = value;
                    NotifyChanged("ICReceiptPOContactEmail2");
                }
            }
        }
        public String ICReceiptPOContactWebsite
        {
            get { return _iCReceiptPOContactWebsite; }
            set
            {
                if (value != this._iCReceiptPOContactWebsite)
                {
                    _iCReceiptPOContactWebsite = value;
                    NotifyChanged("ICReceiptPOContactWebsite");
                }
            }
        }
        public String ICReceiptPOContactPhonePrivate
        {
            get { return _iCReceiptPOContactPhonePrivate; }
            set
            {
                if (value != this._iCReceiptPOContactPhonePrivate)
                {
                    _iCReceiptPOContactPhonePrivate = value;
                    NotifyChanged("ICReceiptPOContactPhonePrivate");
                }
            }
        }
        public String ICReceiptPOContactPhone
        {
            get { return _iCReceiptPOContactPhone; }
            set
            {
                if (value != this._iCReceiptPOContactPhone)
                {
                    _iCReceiptPOContactPhone = value;
                    NotifyChanged("ICReceiptPOContactPhone");
                }
            }
        }
        public String ICReceiptPOContactPhone1
        {
            get { return _iCReceiptPOContactPhone1; }
            set
            {
                if (value != this._iCReceiptPOContactPhone1)
                {
                    _iCReceiptPOContactPhone1 = value;
                    NotifyChanged("ICReceiptPOContactPhone1");
                }
            }
        }
        public String ICReceiptPOContactCellPhone
        {
            get { return _iCReceiptPOContactCellPhone; }
            set
            {
                if (value != this._iCReceiptPOContactCellPhone)
                {
                    _iCReceiptPOContactCellPhone = value;
                    NotifyChanged("ICReceiptPOContactCellPhone");
                }
            }
        }
        public String ICReceiptPOContactCellPhone1
        {
            get { return _iCReceiptPOContactCellPhone1; }
            set
            {
                if (value != this._iCReceiptPOContactCellPhone1)
                {
                    _iCReceiptPOContactCellPhone1 = value;
                    NotifyChanged("ICReceiptPOContactCellPhone1");
                }
            }
        }
        public String ICReceiptPOContactFax
        {
            get { return _iCReceiptPOContactFax; }
            set
            {
                if (value != this._iCReceiptPOContactFax)
                {
                    _iCReceiptPOContactFax = value;
                    NotifyChanged("ICReceiptPOContactFax");
                }
            }
        }
        public String ICReceiptPOContactType
        {
            get { return _iCReceiptPOContactType; }
            set
            {
                if (value != this._iCReceiptPOContactType)
                {
                    _iCReceiptPOContactType = value;
                    NotifyChanged("ICReceiptPOContactType");
                }
            }
        }
        public String ICReceiptPOContactInformation
        {
            get { return _iCReceiptPOContactInformation; }
            set
            {
                if (value != this._iCReceiptPOContactInformation)
                {
                    _iCReceiptPOContactInformation = value;
                    NotifyChanged("ICReceiptPOContactInformation");
                }
            }
        }
        public String ICReceiptPOContactDepartment
        {
            get { return _iCReceiptPOContactDepartment; }
            set
            {
                if (value != this._iCReceiptPOContactDepartment)
                {
                    _iCReceiptPOContactDepartment = value;
                    NotifyChanged("ICReceiptPOContactDepartment");
                }
            }
        }
        public String ICReceiptPOContactRoom
        {
            get { return _iCReceiptPOContactRoom; }
            set
            {
                if (value != this._iCReceiptPOContactRoom)
                {
                    _iCReceiptPOContactRoom = value;
                    NotifyChanged("ICReceiptPOContactRoom");
                }
            }
        }
        public String ICReceiptPOAddressLine1
        {
            get { return _iCReceiptPOAddressLine1; }
            set
            {
                if (value != this._iCReceiptPOAddressLine1)
                {
                    _iCReceiptPOAddressLine1 = value;
                    NotifyChanged("ICReceiptPOAddressLine1");
                }
            }
        }
        public String ICReceiptPOAddressLine2
        {
            get { return _iCReceiptPOAddressLine2; }
            set
            {
                if (value != this._iCReceiptPOAddressLine2)
                {
                    _iCReceiptPOAddressLine2 = value;
                    NotifyChanged("ICReceiptPOAddressLine2");
                }
            }
        }
        public String ICReceiptPOAddressLine3
        {
            get { return _iCReceiptPOAddressLine3; }
            set
            {
                if (value != this._iCReceiptPOAddressLine3)
                {
                    _iCReceiptPOAddressLine3 = value;
                    NotifyChanged("ICReceiptPOAddressLine3");
                }
            }
        }
        public String ICReceiptPOAddressStreet
        {
            get { return _iCReceiptPOAddressStreet; }
            set
            {
                if (value != this._iCReceiptPOAddressStreet)
                {
                    _iCReceiptPOAddressStreet = value;
                    NotifyChanged("ICReceiptPOAddressStreet");
                }
            }
        }
        public String ICReceiptPOAddressCity
        {
            get { return _iCReceiptPOAddressCity; }
            set
            {
                if (value != this._iCReceiptPOAddressCity)
                {
                    _iCReceiptPOAddressCity = value;
                    NotifyChanged("ICReceiptPOAddressCity");
                }
            }
        }
        public String ICReceiptPOAddressPostalCode
        {
            get { return _iCReceiptPOAddressPostalCode; }
            set
            {
                if (value != this._iCReceiptPOAddressPostalCode)
                {
                    _iCReceiptPOAddressPostalCode = value;
                    NotifyChanged("ICReceiptPOAddressPostalCode");
                }
            }
        }
        public String ICReceiptPOAddressStateProvince
        {
            get { return _iCReceiptPOAddressStateProvince; }
            set
            {
                if (value != this._iCReceiptPOAddressStateProvince)
                {
                    _iCReceiptPOAddressStateProvince = value;
                    NotifyChanged("ICReceiptPOAddressStateProvince");
                }
            }
        }
        public String ICReceiptPOAddressZipCode
        {
            get { return _iCReceiptPOAddressZipCode; }
            set
            {
                if (value != this._iCReceiptPOAddressZipCode)
                {
                    _iCReceiptPOAddressZipCode = value;
                    NotifyChanged("ICReceiptPOAddressZipCode");
                }
            }
        }
        public String ICReceiptPOAddressCountry
        {
            get { return _iCReceiptPOAddressCountry; }
            set
            {
                if (value != this._iCReceiptPOAddressCountry)
                {
                    _iCReceiptPOAddressCountry = value;
                    NotifyChanged("ICReceiptPOAddressCountry");
                }
            }
        }
        public String ICReceiptDeliveryContactName
        {
            get { return _iCReceiptDeliveryContactName; }
            set
            {
                if (value != this._iCReceiptDeliveryContactName)
                {
                    _iCReceiptDeliveryContactName = value;
                    NotifyChanged("ICReceiptDeliveryContactName");
                }
            }
        }
        public DateTime ICReceiptDeliveryContactBirthday
        {
            get { return _iCReceiptDeliveryContactBirthday; }
            set
            {
                if (value != this._iCReceiptDeliveryContactBirthday)
                {
                    _iCReceiptDeliveryContactBirthday = value;
                    NotifyChanged("ICReceiptDeliveryContactBirthday");
                }
            }
        }
        public String ICReceiptDeliveryContactFirstName
        {
            get { return _iCReceiptDeliveryContactFirstName; }
            set
            {
                if (value != this._iCReceiptDeliveryContactFirstName)
                {
                    _iCReceiptDeliveryContactFirstName = value;
                    NotifyChanged("ICReceiptDeliveryContactFirstName");
                }
            }
        }
        public String ICReceiptDeliveryContactLastName
        {
            get { return _iCReceiptDeliveryContactLastName; }
            set
            {
                if (value != this._iCReceiptDeliveryContactLastName)
                {
                    _iCReceiptDeliveryContactLastName = value;
                    NotifyChanged("ICReceiptDeliveryContactLastName");
                }
            }
        }
        public String ICReceiptDeliveryContactTitle
        {
            get { return _iCReceiptDeliveryContactTitle; }
            set
            {
                if (value != this._iCReceiptDeliveryContactTitle)
                {
                    _iCReceiptDeliveryContactTitle = value;
                    NotifyChanged("ICReceiptDeliveryContactTitle");
                }
            }
        }
        public String ICReceiptDeliveryContactHeaderLetter
        {
            get { return _iCReceiptDeliveryContactHeaderLetter; }
            set
            {
                if (value != this._iCReceiptDeliveryContactHeaderLetter)
                {
                    _iCReceiptDeliveryContactHeaderLetter = value;
                    NotifyChanged("ICReceiptDeliveryContactHeaderLetter");
                }
            }
        }
        public String ICReceiptDeliveryContactHeaderMessage
        {
            get { return _iCReceiptDeliveryContactHeaderMessage; }
            set
            {
                if (value != this._iCReceiptDeliveryContactHeaderMessage)
                {
                    _iCReceiptDeliveryContactHeaderMessage = value;
                    NotifyChanged("ICReceiptDeliveryContactHeaderMessage");
                }
            }
        }
        public String ICReceiptDeliveryContactEmail1
        {
            get { return _iCReceiptDeliveryContactEmail1; }
            set
            {
                if (value != this._iCReceiptDeliveryContactEmail1)
                {
                    _iCReceiptDeliveryContactEmail1 = value;
                    NotifyChanged("ICReceiptDeliveryContactEmail1");
                }
            }
        }
        public String ICReceiptDeliveryContactEmail2
        {
            get { return _iCReceiptDeliveryContactEmail2; }
            set
            {
                if (value != this._iCReceiptDeliveryContactEmail2)
                {
                    _iCReceiptDeliveryContactEmail2 = value;
                    NotifyChanged("ICReceiptDeliveryContactEmail2");
                }
            }
        }
        public String ICReceiptDeliveryContactWebsite
        {
            get { return _iCReceiptDeliveryContactWebsite; }
            set
            {
                if (value != this._iCReceiptDeliveryContactWebsite)
                {
                    _iCReceiptDeliveryContactWebsite = value;
                    NotifyChanged("ICReceiptDeliveryContactWebsite");
                }
            }
        }
        public String ICReceiptDeliveryContactPhonePrivate
        {
            get { return _iCReceiptDeliveryContactPhonePrivate; }
            set
            {
                if (value != this._iCReceiptDeliveryContactPhonePrivate)
                {
                    _iCReceiptDeliveryContactPhonePrivate = value;
                    NotifyChanged("ICReceiptDeliveryContactPhonePrivate");
                }
            }
        }
        public String ICReceiptDeliveryContactPhone
        {
            get { return _iCReceiptDeliveryContactPhone; }
            set
            {
                if (value != this._iCReceiptDeliveryContactPhone)
                {
                    _iCReceiptDeliveryContactPhone = value;
                    NotifyChanged("ICReceiptDeliveryContactPhone");
                }
            }
        }
        public String ICReceiptDeliveryContactPhone1
        {
            get { return _iCReceiptDeliveryContactPhone1; }
            set
            {
                if (value != this._iCReceiptDeliveryContactPhone1)
                {
                    _iCReceiptDeliveryContactPhone1 = value;
                    NotifyChanged("ICReceiptDeliveryContactPhone1");
                }
            }
        }
        public String ICReceiptDeliveryContactCellPhone
        {
            get { return _iCReceiptDeliveryContactCellPhone; }
            set
            {
                if (value != this._iCReceiptDeliveryContactCellPhone)
                {
                    _iCReceiptDeliveryContactCellPhone = value;
                    NotifyChanged("ICReceiptDeliveryContactCellPhone");
                }
            }
        }
        public String ICReceiptDeliveryContactCellPhone1
        {
            get { return _iCReceiptDeliveryContactCellPhone1; }
            set
            {
                if (value != this._iCReceiptDeliveryContactCellPhone1)
                {
                    _iCReceiptDeliveryContactCellPhone1 = value;
                    NotifyChanged("ICReceiptDeliveryContactCellPhone1");
                }
            }
        }
        public String ICReceiptDeliveryContactFax
        {
            get { return _iCReceiptDeliveryContactFax; }
            set
            {
                if (value != this._iCReceiptDeliveryContactFax)
                {
                    _iCReceiptDeliveryContactFax = value;
                    NotifyChanged("ICReceiptDeliveryContactFax");
                }
            }
        }
        public String ICReceiptDeliveryContactType
        {
            get { return _iCReceiptDeliveryContactType; }
            set
            {
                if (value != this._iCReceiptDeliveryContactType)
                {
                    _iCReceiptDeliveryContactType = value;
                    NotifyChanged("ICReceiptDeliveryContactType");
                }
            }
        }
        public String ICReceiptDeliveryContactInformation
        {
            get { return _iCReceiptDeliveryContactInformation; }
            set
            {
                if (value != this._iCReceiptDeliveryContactInformation)
                {
                    _iCReceiptDeliveryContactInformation = value;
                    NotifyChanged("ICReceiptDeliveryContactInformation");
                }
            }
        }
        public String ICReceiptDeliveryContactDepartment
        {
            get { return _iCReceiptDeliveryContactDepartment; }
            set
            {
                if (value != this._iCReceiptDeliveryContactDepartment)
                {
                    _iCReceiptDeliveryContactDepartment = value;
                    NotifyChanged("ICReceiptDeliveryContactDepartment");
                }
            }
        }
        public String ICReceiptDeliveryContactRoom
        {
            get { return _iCReceiptDeliveryContactRoom; }
            set
            {
                if (value != this._iCReceiptDeliveryContactRoom)
                {
                    _iCReceiptDeliveryContactRoom = value;
                    NotifyChanged("ICReceiptDeliveryContactRoom");
                }
            }
        }
        public String ICReceiptDeliveryAddressLine1
        {
            get { return _iCReceiptDeliveryAddressLine1; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressLine1)
                {
                    _iCReceiptDeliveryAddressLine1 = value;
                    NotifyChanged("ICReceiptDeliveryAddressLine1");
                }
            }
        }
        public String ICReceiptDeliveryAddressLine2
        {
            get { return _iCReceiptDeliveryAddressLine2; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressLine2)
                {
                    _iCReceiptDeliveryAddressLine2 = value;
                    NotifyChanged("ICReceiptDeliveryAddressLine2");
                }
            }
        }
        public String ICReceiptDeliveryAddressLine3
        {
            get { return _iCReceiptDeliveryAddressLine3; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressLine3)
                {
                    _iCReceiptDeliveryAddressLine3 = value;
                    NotifyChanged("ICReceiptDeliveryAddressLine3");
                }
            }
        }
        public String ICReceiptDeliveryAddressStreet
        {
            get { return _iCReceiptDeliveryAddressStreet; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressStreet)
                {
                    _iCReceiptDeliveryAddressStreet = value;
                    NotifyChanged("ICReceiptDeliveryAddressStreet");
                }
            }
        }
        public String ICReceiptDeliveryAddressCity
        {
            get { return _iCReceiptDeliveryAddressCity; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressCity)
                {
                    _iCReceiptDeliveryAddressCity = value;
                    NotifyChanged("ICReceiptDeliveryAddressCity");
                }
            }
        }
        public String ICReceiptDeliveryAddressPostalCode
        {
            get { return _iCReceiptDeliveryAddressPostalCode; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressPostalCode)
                {
                    _iCReceiptDeliveryAddressPostalCode = value;
                    NotifyChanged("ICReceiptDeliveryAddressPostalCode");
                }
            }
        }
        public String ICReceiptDeliveryAddressStateProvince
        {
            get { return _iCReceiptDeliveryAddressStateProvince; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressStateProvince)
                {
                    _iCReceiptDeliveryAddressStateProvince = value;
                    NotifyChanged("ICReceiptDeliveryAddressStateProvince");
                }
            }
        }
        public String ICReceiptDeliveryAddressZipCode
        {
            get { return _iCReceiptDeliveryAddressZipCode; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressZipCode)
                {
                    _iCReceiptDeliveryAddressZipCode = value;
                    NotifyChanged("ICReceiptDeliveryAddressZipCode");
                }
            }
        }
        public String ICReceiptDeliveryAddressCountry
        {
            get { return _iCReceiptDeliveryAddressCountry; }
            set
            {
                if (value != this._iCReceiptDeliveryAddressCountry)
                {
                    _iCReceiptDeliveryAddressCountry = value;
                    NotifyChanged("ICReceiptDeliveryAddressCountry");
                }
            }
        }
        public double ICReceiptShippingFees
        {
            get { return _iCReceiptShippingFees; }
            set
            {
                if (value != this._iCReceiptShippingFees)
                {
                    _iCReceiptShippingFees = value;
                    NotifyChanged("ICReceiptShippingFees");
                }
            }
        }
        public double ICReceiptShippingExtraFees
        {
            get { return _iCReceiptShippingExtraFees; }
            set
            {
                if (value != this._iCReceiptShippingExtraFees)
                {
                    _iCReceiptShippingExtraFees = value;
                    NotifyChanged("ICReceiptShippingExtraFees");
                }
            }
        }
        public double ICReceiptShippingInsuranceFees
        {
            get { return _iCReceiptShippingInsuranceFees; }
            set
            {
                if (value != this._iCReceiptShippingInsuranceFees)
                {
                    _iCReceiptShippingInsuranceFees = value;
                    NotifyChanged("ICReceiptShippingInsuranceFees");
                }
            }
        }
        public double ICReceiptShippingPackagingFees
        {
            get { return _iCReceiptShippingPackagingFees; }
            set
            {
                if (value != this._iCReceiptShippingPackagingFees)
                {
                    _iCReceiptShippingPackagingFees = value;
                    NotifyChanged("ICReceiptShippingPackagingFees");
                }
            }
        }
        public double ICReceiptShippingReservedFees1
        {
            get { return _iCReceiptShippingReservedFees1; }
            set
            {
                if (value != this._iCReceiptShippingReservedFees1)
                {
                    _iCReceiptShippingReservedFees1 = value;
                    NotifyChanged("ICReceiptShippingReservedFees1");
                }
            }
        }
        public double ICReceiptShippingReservedFees2
        {
            get { return _iCReceiptShippingReservedFees2; }
            set
            {
                if (value != this._iCReceiptShippingReservedFees2)
                {
                    _iCReceiptShippingReservedFees2 = value;
                    NotifyChanged("ICReceiptShippingReservedFees2");
                }
            }
        }
        public double ICReceiptShippingReservedFees3
        {
            get { return _iCReceiptShippingReservedFees3; }
            set
            {
                if (value != this._iCReceiptShippingReservedFees3)
                {
                    _iCReceiptShippingReservedFees3 = value;
                    NotifyChanged("ICReceiptShippingReservedFees3");
                }
            }
        }
        public double ICReceiptShippingReservedFees4
        {
            get { return _iCReceiptShippingReservedFees4; }
            set
            {
                if (value != this._iCReceiptShippingReservedFees4)
                {
                    _iCReceiptShippingReservedFees4 = value;
                    NotifyChanged("ICReceiptShippingReservedFees4");
                }
            }
        }
        public String ICReceiptShippingMethodDesc
        {
            get { return _iCReceiptShippingMethodDesc; }
            set
            {
                if (value != this._iCReceiptShippingMethodDesc)
                {
                    _iCReceiptShippingMethodDesc = value;
                    NotifyChanged("ICReceiptShippingMethodDesc");
                }
            }
        }
        public String ICReceiptShippingMethodName
        {
            get { return _iCReceiptShippingMethodName; }
            set
            {
                if (value != this._iCReceiptShippingMethodName)
                {
                    _iCReceiptShippingMethodName = value;
                    NotifyChanged("ICReceiptShippingMethodName");
                }
            }
        }
        public String ICReceiptInvoiceInNo
        {
            get { return _iCReceiptInvoiceInNo; }
            set
            {
                if (value != this._iCReceiptInvoiceInNo)
                {
                    _iCReceiptInvoiceInNo = value;
                    NotifyChanged("ICReceiptInvoiceInNo");
                }
            }
        }
        public DateTime ICReceiptInvoiceInDate
        {
            get { return _iCReceiptInvoiceInDate; }
            set
            {
                if (value != this._iCReceiptInvoiceInDate)
                {
                    _iCReceiptInvoiceInDate = value;
                    NotifyChanged("ICReceiptInvoiceInDate");
                }
            }
        }
        public double ICReceiptExchangeRate
        {
            get { return _iCReceiptExchangeRate; }
            set
            {
                if (value != this._iCReceiptExchangeRate)
                {
                    _iCReceiptExchangeRate = value;
                    NotifyChanged("ICReceiptExchangeRate");
                }
            }
        }
        public bool IsTransferred
        {
            get { return _isTransferred; }
            set
            {
                if (value != this._isTransferred)
                {
                    _isTransferred = value;
                    NotifyChanged("IsTransferred");
                }
            }
        }
        public DateTime ICReceiptTransferredDate
        {
            get { return _iCReceiptTransferredDate; }
            set
            {
                if (value != this._iCReceiptTransferredDate)
                {
                    _iCReceiptTransferredDate = value;
                    NotifyChanged("ICReceiptTransferredDate");
                }
            }
        }
        public String ICObjectType
        {
            get { return _iCObjectType; }
            set
            {
                if (value != this._iCObjectType)
                {
                    _iCObjectType = value;
                    NotifyChanged("ICObjectType");
                }
            }
        }
        public String ICReceiptFormNo
        {
            get { return _iCReceiptFormNo; }
            set
            {
                if (value != this._iCReceiptFormNo)
                {
                    _iCReceiptFormNo = value;
                    NotifyChanged("ICReceiptFormNo");
                }
            }
        }
        public String ICReceiptSymbol
        {
            get { return _iCReceiptSymbol; }
            set
            {
                if (value != this._iCReceiptSymbol)
                {
                    _iCReceiptSymbol = value;
                    NotifyChanged("ICReceiptSymbol");
                }
            }
        }
        public String ICVATDocumentNo
        {
            get { return _iCVATDocumentNo; }
            set
            {
                if (value != this._iCVATDocumentNo)
                {
                    _iCVATDocumentNo = value;
                    NotifyChanged("ICVATDocumentNo");
                }
            }
        }
        public String ICInputDocumentType
        {
            get { return _iCInputDocumentType; }
            set
            {
                if (value != this._iCInputDocumentType)
                {
                    _iCInputDocumentType = value;
                    NotifyChanged("ICInputDocumentType");
                }
            }
        }
        public int FK_ACSegmentID
        {
            get { return _fK_ACSegmentID; }
            set
            {
                if (value != this._fK_ACSegmentID)
                {
                    _fK_ACSegmentID = value;
                    NotifyChanged("FK_ACSegmentID");
                }
            }
        }
        #endregion


        #region Extra Properties
        public byte[] ICReceiptEmployeePicture {get; set; }
        public string ICPackageSupplierNo { get; set; }

        public string APSupplierName { get; set; }

        /// <summary>
        /// Gets or sets the item list of the receipt
        /// </summary>
        public IBOSList<ICReceiptItemsInfo> ReceiptItems { get; set; }

        public string ACObjectAccessKey { get; set; }

        public DateTime ReceiptDateFrom { get; set; }

        public DateTime ReceiptDateTo { get; set; }

        public string ACObjectNo { get; set; }
        #endregion
    }
    #endregion
}