using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ICTransferProposalItemPackages
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ICTransferProposalItemPackagesInfo
    //Created Date:Thursday, September 12, 2013
    //-----------------------------------------------------------

    public class ICTransferProposalItemPackagesInfo : BusinessObject
    {
        public ICTransferProposalItemPackagesInfo()
        {
        }
        #region Variables
        protected int _iCTransferProposalItemPackageID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ICTransferProposalItemID;
        protected int _fK_ICStockID;
        protected int _fK_ICProductID;
        protected int _fK_ICPackageID;
        protected double _iCTransferProposalItemPackageQty;
        #endregion

        #region Public properties
        public int ICTransferProposalItemPackageID
        {
            get { return _iCTransferProposalItemPackageID; }
            set
            {
                if (value != this._iCTransferProposalItemPackageID)
                {
                    _iCTransferProposalItemPackageID = value;
                    NotifyChanged("ICTransferProposalItemPackageID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ICTransferProposalItemID
        {
            get { return _fK_ICTransferProposalItemID; }
            set
            {
                if (value != this._fK_ICTransferProposalItemID)
                {
                    _fK_ICTransferProposalItemID = value;
                    NotifyChanged("FK_ICTransferProposalItemID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICPackageID
        {
            get { return _fK_ICPackageID; }
            set
            {
                if (value != this._fK_ICPackageID)
                {
                    _fK_ICPackageID = value;
                    NotifyChanged("FK_ICPackageID");
                }
            }
        }
        public double ICTransferProposalItemPackageQty
        {
            get { return _iCTransferProposalItemPackageQty; }
            set
            {
                if (value != this._iCTransferProposalItemPackageQty)
                {
                    _iCTransferProposalItemPackageQty = value;
                    NotifyChanged("ICTransferProposalItemPackageQty");
                }
            }
        }
        #endregion

        #region Extra Properties
        public string ICPackageNo { get; set; }
        #endregion
    }
    #endregion
}