using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region ARDeliveryItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARDeliveryItemsController
    //Created Date:Wednesday, July 24, 2013
    //-----------------------------------------------------------

    public class ARDeliveryItemsController : BaseBusinessController
    {
        public ARDeliveryItemsController()
        {
            dal = new DALBaseProvider("ARDeliveryItems", typeof(ARDeliveryItemsInfo));
        }
    }
    #endregion
}