using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region METemplateChartSeries
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:METemplateChartSeriesController
    //Created Date:Monday, April 2, 2018
    //-----------------------------------------------------------

    public class METemplateChartSeriesController : BaseBusinessController
    {
        public METemplateChartSeriesController()
        {
            dal = new DALBaseProvider("METemplateChartSeries", typeof(METemplateChartSeriesInfo));
        }
    }
    #endregion
}