using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region METemplateCharts
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:METemplateChartsController
    //Created Date:Monday, April 2, 2018
    //-----------------------------------------------------------

    public class METemplateChartsController : BaseBusinessController
    {
        public METemplateChartsController()
        {
            dal = new DALBaseProvider("METemplateCharts", typeof(METemplateChartsInfo));
        }
    }
    #endregion
}