using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region VMVehicleFuelLogs
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:VMVehicleFuelLogsInfo
    //Created Date:Friday, June 21, 2013
    //-----------------------------------------------------------

    public class VMVehicleFuelLogsInfo : BusinessObject
    {
        public VMVehicleFuelLogsInfo()
        {
        }
        #region Variables
        protected int _vMVehicleFuelLogID;
        protected String _aAStatus = DefaultAAStatus;
        protected DateTime _aACreatedDate = DateTime.Now;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected int _fK_VMVehicleID;
        protected DateTime _vMVehicleFuelLogDate = DateTime.Now;
        protected double _vMVehicleFuelLogQty;
        protected double _vMVehicleFuelLogCost;
        protected double _vMVehicleFuelLogTotalCost;
        protected double _vMVehicleFuelLogStartOdometer;
        protected double _vMVehicleFuelLogEndOdometer;
        protected double _vMVehicleFuelLogDistanceCovered;
        protected double _vMVehicleFuelLogConsumption1;
        protected double _vMVehicleFuelLogConsumption2;
        protected String _vMVehicleFuelLogRemark = String.Empty;
        #endregion

        #region Public properties
        public int VMVehicleFuelLogID
        {
            get { return _vMVehicleFuelLogID; }
            set
            {
                if (value != this._vMVehicleFuelLogID)
                {
                    _vMVehicleFuelLogID = value;
                    NotifyChanged("VMVehicleFuelLogID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public int FK_VMVehicleID
        {
            get { return _fK_VMVehicleID; }
            set
            {
                if (value != this._fK_VMVehicleID)
                {
                    _fK_VMVehicleID = value;
                    NotifyChanged("FK_VMVehicleID");
                }
            }
        }
        public DateTime VMVehicleFuelLogDate
        {
            get { return _vMVehicleFuelLogDate; }
            set
            {
                if (value != this._vMVehicleFuelLogDate)
                {
                    _vMVehicleFuelLogDate = value;
                    NotifyChanged("VMVehicleFuelLogDate");
                }
            }
        }
        public double VMVehicleFuelLogQty
        {
            get { return _vMVehicleFuelLogQty; }
            set
            {
                if (value != this._vMVehicleFuelLogQty)
                {
                    _vMVehicleFuelLogQty = value;
                    NotifyChanged("VMVehicleFuelLogQty");
                }
            }
        }
        public double VMVehicleFuelLogCost
        {
            get { return _vMVehicleFuelLogCost; }
            set
            {
                if (value != this._vMVehicleFuelLogCost)
                {
                    _vMVehicleFuelLogCost = value;
                    NotifyChanged("VMVehicleFuelLogCost");
                }
            }
        }
        public double VMVehicleFuelLogTotalCost
        {
            get { return _vMVehicleFuelLogTotalCost; }
            set
            {
                if (value != this._vMVehicleFuelLogTotalCost)
                {
                    _vMVehicleFuelLogTotalCost = value;
                    NotifyChanged("VMVehicleFuelLogTotalCost");
                }
            }
        }
        public double VMVehicleFuelLogStartOdometer
        {
            get { return _vMVehicleFuelLogStartOdometer; }
            set
            {
                if (value != this._vMVehicleFuelLogStartOdometer)
                {
                    _vMVehicleFuelLogStartOdometer = value;
                    NotifyChanged("VMVehicleFuelLogStartOdometer");
                }
            }
        }
        public double VMVehicleFuelLogEndOdometer
        {
            get { return _vMVehicleFuelLogEndOdometer; }
            set
            {
                if (value != this._vMVehicleFuelLogEndOdometer)
                {
                    _vMVehicleFuelLogEndOdometer = value;
                    NotifyChanged("VMVehicleFuelLogEndOdometer");
                }
            }
        }
        public double VMVehicleFuelLogDistanceCovered
        {
            get { return _vMVehicleFuelLogDistanceCovered; }
            set
            {
                if (value != this._vMVehicleFuelLogDistanceCovered)
                {
                    _vMVehicleFuelLogDistanceCovered = value;
                    NotifyChanged("VMVehicleFuelLogDistanceCovered");
                }
            }
        }
        public double VMVehicleFuelLogConsumption1
        {
            get { return _vMVehicleFuelLogConsumption1; }
            set
            {
                if (value != this._vMVehicleFuelLogConsumption1)
                {
                    _vMVehicleFuelLogConsumption1 = value;
                    NotifyChanged("VMVehicleFuelLogConsumption1");
                }
            }
        }
        public double VMVehicleFuelLogConsumption2
        {
            get { return _vMVehicleFuelLogConsumption2; }
            set
            {
                if (value != this._vMVehicleFuelLogConsumption2)
                {
                    _vMVehicleFuelLogConsumption2 = value;
                    NotifyChanged("VMVehicleFuelLogConsumption2");
                }
            }
        }
        public String VMVehicleFuelLogRemark
        {
            get { return _vMVehicleFuelLogRemark; }
            set
            {
                if (value != this._vMVehicleFuelLogRemark)
                {
                    _vMVehicleFuelLogRemark = value;
                    NotifyChanged("VMVehicleFuelLogRemark");
                }
            }
        }
        #endregion
    }
    #endregion
}