using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using BOSCommon;
using BOSLib;

namespace BOSERP
{

    #region HREmployees

    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:HREmployeesController
    //Created Date:Wednesday, October 08, 2008
    //-----------------------------------------------------------

    public class HREmployeesController : BaseBusinessController
    {
        private BRBranchsController _brBranchsController;
        private ADDataViewPermissionsController _dataViewPermissionsController;
        public HREmployeesController()
        {
            dal = new DALBaseProvider("HREmployees", typeof(HREmployeesInfo));
            _brBranchsController = new BRBranchsController();
            _dataViewPermissionsController = new ADDataViewPermissionsController();
        }

        public object GetObject(int iObjectID)
        {
            var o = dal.GetDataObject("dbo.GetExtraSalary", iObjectID, DateTime.Now);
            return 0;
        }

        /// <summary>
        ///     Get the sale summary of an employee
        /// </summary>
        /// <param name="objEmployeesInfo">Employee object is used to retrive data</param>
        /// <param name="from">Date which the result is filtered from</param>
        /// <param name="to">Date which the result is filtered to</param>
        public void GetSaleSummary(HREmployeesInfo objEmployeesInfo, DateTime? from, DateTime? to)
        {
            var cmd = dal.GetStoredProcedureCommand("HREmployees_GetSaleSummary");
            dal.AddParameter(cmd, "HREmployeeID", DbType.Int32, ParameterDirection.Input, objEmployeesInfo.HREmployeeID);
            dal.AddParameter(cmd, "DateFrom", DbType.DateTime, ParameterDirection.Input, from);
            dal.AddParameter(cmd, "DateTo", DbType.DateTime, ParameterDirection.Input, to);
            dal.AddParameter(cmd, "TotalSaleAmount", DbType.Double, ParameterDirection.Output,
                objEmployeesInfo.TotalSaleAmount);
            dal.AddParameter(cmd, "TotalSaleQty", DbType.Double, ParameterDirection.Output,
                objEmployeesInfo.TotalSaleQty);
            dal.GetDataSet(cmd);
            objEmployeesInfo.TotalSaleAmount = Convert.ToDouble(dal.GetParameterValue(cmd, "TotalSaleAmount"));
            objEmployeesInfo.TotalSaleQty = Convert.ToDouble(dal.GetParameterValue(cmd, "TotalSaleQty"));
        }

        public DataSet GetEmployeeByTimeSheet(int timeSheetID)
        {
            return dal.GetDataSet("HREmployees_GetEmployeeByTimeSheet", timeSheetID);
        }

        /// <summary>
        ///     Get the first employee belonging to a specilism
        /// </summary>
        /// <param name="specilismID"></param>
        /// <returns></returns>
        public HREmployeesInfo GetFirstEmployeeBySpecilismID(int specilismID)
        {
            var ds = dal.GetDataSet("HREmployees_GetFirstEmployeeBySpecilism", specilismID);
            if (ds.Tables.Count > 0 && ds.Tables[0].Rows.Count > 0)
            {
                var objEmployessInfo = (HREmployeesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
                return objEmployessInfo;
            }
            return null;
        }

        /// <summary>
        ///     Get all employees
        /// </summary>
        /// <returns>List of employees</returns>
        public List<HREmployeesInfo> GetAllEmployees()
        {
            var ds = dal.GetAllObject();
            var employees = new List<HREmployeesInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objEmployeesInfo = (HREmployeesInfo)GetObjectFromDataRow(row);
                    employees.Add(objEmployeesInfo);
                }
            return employees;
        }

        public List<HREmployeesInfo> GetEmployeeListByPayrollFormulaID(int? payrollFormulaID)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeListByPayrollFormulaID", payrollFormulaID);
            var employees = new List<HREmployeesInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objEmployeesInfo = (HREmployeesInfo)GetObjectFromDataRow(row);
                    employees.Add(objEmployeesInfo);
                }
            return employees;
        }

        /// <summary>
        ///     Get the list of employee based on some criteria
        /// </summary>
        /// <param name="branchID">Branch id</param>
        /// <param name="departmentID">The department ID</param>
        /// <param name="departmentRoomID">The department room ID</param>
        /// <param name="levelID">Level id</param>
        /// <param name="status">Working status</param>
        /// <returns>List of employees</returns>
        public List<HREmployeesInfo> GetEmployeeList(int? branchID, int? departmentID, int? departmentRoomID,
            int? levelID, string status)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeList", branchID, departmentID, departmentRoomID, levelID,
                status);
            var employees = new List<HREmployeesInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var objEmployeesInfo = (HREmployeesInfo)GetObjectFromDataRow(row);
                    employees.Add(objEmployeesInfo);
                }
            return employees;
        }

        /// <summary>
        ///     Get the list of employee based on some criteria
        /// </summary>
        /// <param name="branchID">Branch id</param>
        /// <param name="departmentID">The department ID</param>
        /// <param name="departmentRoomID">The department room ID</param>
        /// <param name="levelID">Level id</param>
        /// <param name="status">Working status</param>
        /// <returns>List of employees</returns>
        public List<HREmployeesInfo> GetEmployeeList(int? branchID, int? departmentID, int? departmentRoomID,
            string status)
        {
            return GetEmployeeList(branchID, departmentID, departmentRoomID, null, status);
        }

        /// <summary>
        ///     Get the list of employee based on some criteria
        /// </summary>
        /// <param name="branchID">Branch id</param>
        /// <param name="departmentID">The department ID</param>
        /// <param name="departmentRoomID">The department room ID</param>
        /// <returns>List of employees</returns>
        public List<HREmployeesInfo> GetEmployeeList(int? branchID, int? departmentID, int? departmentRoomID)
        {
            return GetEmployeeList(branchID, departmentID, departmentRoomID, null, null);
        }


        /// <summary>
        ///     Get the list of employees based on some criteria
        /// </summary>
        /// <param name="employeeNo">Employee no</param>
        /// <param name="employeeName">Employee name</param>
        /// <param name="contactAddress">Contact address</param>
        /// <param name="gender">Gender</param>
        /// <param name="idNumber">Id number</param>
        /// <param name="roomId">Room id</param>
        /// <param name="levelId">Level id</param>
        /// <param name="branchId">Branch id</param>
        /// <returns>Employee list</returns>
        public DataSet GetEmployeeList(
            string employeeNo,
            string employeeName,
            string contactAddress,
            string gender,
            string idNumber,
            int? roomId,
            int? levelId,
            int? branchId)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeSet",
                employeeNo,
                employeeName,
                contactAddress,
                gender,
                idNumber,
                roomId,
                levelId,
                branchId);
            return ds;
        }

        public DataSet GetEmployeeList(
            string employeeNo,
            string employeeName,
            string contactAddress,
            string gender,
            string idNumber,
            int? roomID,
            string status,
            int? levelID,
            int? branchID)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeSet2",
                employeeNo,
                employeeName,
                contactAddress,
                gender,
                idNumber,
                roomID,
                status,
                levelID,
                branchID);
            return ds;
        }

        /// <summary>
        ///     Get employees for transferring to the centre
        /// </summary>
        /// <returns>List of transferred employees</returns>
        public List<HREmployeesInfo> GetEmployeesForTransferring()
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeesForTransferring");
            return (List<HREmployeesInfo>)GetListFromDataSet(ds);
        }

        public override IList GetListFromDataSet(DataSet ds)
        {
            var employees = new List<HREmployeesInfo>();
            if (ds.Tables.Count > 0)
                foreach (DataRow row in ds.Tables[0].Rows)
                {
                    var employee = (HREmployeesInfo)GetObjectFromDataRow(row);
                    employees.Add(employee);
                }
            return employees;
        }

        public HREmployeesInfo GetEmployeeByCardNumber(string cardNumber)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeByCardNumber", cardNumber);
            var employees = (List<HREmployeesInfo>)GetListFromDataSet(ds);
            if (employees != null && employees.Count > 0)
                return employees[0];
            return null;
        }

        public HREmployeesInfo GetEmployeeByID(int employeeID)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeByID", employeeID);
            var employees = (List<HREmployeesInfo>)GetListFromDataSet(ds);
            if (employees != null && employees.Count > 0)
                return employees[0];
            return null;
        }

        /// <summary>
        ///     uthv 17032017
        ///     Create Employee
        ///     Create User
        /// </summary>
        /// <param name="bRBranchId">this branch must from bs24x7 before</param>
        /// <param name="idGroup"></param>
        /// <param name="username"></param>
        /// <param name="pw"></param>
        /// <returns></returns>
        public int CreateEmployeeAndUserFromBs24X7(string employeeNo, int bRBranchId, int idGroup, string username, string pw,
            string fullName, string bacsi24x7Id = null, int specialId = 0, bool createUser = true)
        {
            // get branch, this branch must from bs24x7 before
            var branchCtrl = new BRBranchsController();
            var branch = branchCtrl.GetObjectByID(bRBranchId) as BRBranchsInfo;
            // get room, this room auto create before from bs24x7
            var roomCtrl = new HRDepartmentRoomsController();
            var room = roomCtrl.GetObjectByBs24x7ID(branch.BRBranchBacSi24x7Id) as HRDepartmentRoomsInfo;
            // create employee
            var empCtrl = new HREmployeesController();
            var emp = GetEmployeesInfoByBs24x7(bacsi24x7Id, bRBranchId);
            if (emp == null)
            {
                emp = new HREmployeesInfo
                {
                    FK_BRBranchID = bRBranchId,
                    FK_HRDepartmentID = room.FK_HRDepartmentID,
                    FK_HRDepartmentRoomID = room.HRDepartmentRoomID,
                    HREmployeeNo = employeeNo,
                    HREmployeeName = fullName,
                    FK_MESpecialismID = specialId,
                    HREmployeeBacSi24x7Id = bacsi24x7Id,
                    HREmployeeStartWorkingTime = new DateTime(1970, 1, 1, 7, 0, 0),
                    HREmployeeEndWorkingTime = new DateTime(1970, 1, 1, 17, 0, 0)
            };
                empCtrl.CreateObject(emp);
            }

            if (!createUser) return emp.HREmployeeID;
            var userCtrl = new ADUsersController();
            var objUsersInfo = new ADUsersInfo
            {
                FK_HREmployeeID = emp.HREmployeeID,
                ADUserGroupID = idGroup,
                ADUserName = username,
                ADPassword = pw,
                ADUserStyle = "Skin",
                ADUserStyleSkin = "Black",
                ADUserEndTimeDefault = 1,
                ADUserBranchId = bRBranchId
            };
            var userId = userCtrl.CreateUser(objUsersInfo);
            var listBranch = _brBranchsController.GetListBusinessObjects().Cast<BRBranchsInfo>();
            var listModule = Constant.ListModuleFree;
            var moduleList = new List<int>();
            for (var i = 0; i < listModule.GetLength(0); i++)
            {
                var modules = listModule[i, 1];
                moduleList.AddRange(modules.Split(',').Select(int.Parse));
            }
            foreach (var brBranchsInfo in listBranch)
            {
                if(brBranchsInfo.BRBranchID==0)
                    continue;
                _dataViewPermissionsController.PermissionViewData(userId,brBranchsInfo.BRBranchID, moduleList);
            }
            return userId;
        }

        //NUThao [ADD] [23/11/2013] [DB centre] [Permission configuration], START
        /// <summary>
        ///     Get employee by userid
        /// </summary>
        /// <returns></returns>
        public HREmployeesInfo GetEmployeeByUserID(int userID)
        {
            HREmployeesInfo employee = null;
            var ds = dal.GetDataSet("HREmployees_GetEmployeeByUserID", userID);
            if (ds != null && ds.Tables.Count != 0)
                if (ds.Tables[0].Rows.Count != 0)
                    employee = (HREmployeesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return employee;
        }

        //NUThao [ADD] [23/11/2013] [DB centre] [Permission configuration], END

        public List<HREmployeesInfo> GetEmployeeByIDWithUserNameForReport(int employeeID)
        {
            var ds = dal.GetDataSet("HREmployees_GetEmployeeByIDWithUserNameForReport", employeeID);
            var employees = (List<HREmployeesInfo>)GetListFromDataSet(ds);
            return employees;
        }

        public DataSet GetEmployeesForLookupEdit()
        {
            return dal.GetDataSet("HREmployees_GetEmployeesForLookupEdit");
        }

        public HREmployeesInfo GetEmployeesInfoByBs24x7(string bacsi24x7Id, int brachId)
        {
            var ds =
                dal.GetDataSet(
                    $"SELECT HREmployeeID FROM HREmployees WHERE HREmployeeBacSi24x7Id = '{bacsi24x7Id}' AND FK_BRBranchID='{brachId}'");
            HREmployeesInfo employee = null;
            if (ds == null || ds.Tables.Count == 0) return null;
            if (ds.Tables[0].Rows.Count != 0)
                employee = (HREmployeesInfo)GetObjectFromDataRow(ds.Tables[0].Rows[0]);
            return employee;
        }
    }

    #endregion
}