ALTER TABLE MEParams DROP CONSTRAINT DF_MEParams_MEParamReportXML
GO
ALTER TABLE MEParams DROP COLUMN MEParamReportXML
GO
ALTER TABLE MEParams DROP CONSTRAINT DF_MEParams_MEParamReportXMLLevel
GO
ALTER TABLE MEParams DROP COLUMN MEParamReportXMLLevel
GO
ALTER TABLE MEParams DROP CONSTRAINT DF_MEParams_MEParamReportXMLGroup
GO
ALTER TABLE MEParams DROP COLUMN MEParamReportXMLGroup
GO
ALTER TABLE MEParams DROP CONSTRAINT DF_MEParams_MEParamReportXMLOrder
GO
ALTER TABLE MEParams DROP COLUMN MEParamReportXMLOrder
GO
ALTER TABLE MEParams DROP COLUMN MEParamReportMap
GO
IF NOT EXISTS (SELECT * FROM sys.columns WHERE  object_id = OBJECT_ID(N'[dbo].[MEParams]') AND name = 'MEParamXMLTag')
BEGIN
	ALTER TABLE [dbo].[MEParams] ADD MEParamXMLTag nvarchar(100) NULL
END
GO
UPDATE [dbo].[MEParams] SET MEParamXMLTag=''