BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.MEEmrDocuments_Identity
	(
	ID int NOT NULL IDENTITY (1, 1),
	AT DATETIME NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.MEEmrDocuments_Identity ADD CONSTRAINT
	PK_MEEmrDocuments_Identity PRIMARY KEY CLUSTERED 
	(
	ID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.MEEmrDocuments_Identity SET (LOCK_ESCALATION = TABLE)
GO
COMMIT