using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
    #region BRPostingHistorys
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:BRPostingHistorysController
    //Created Date:Saturday, August 16, 2008
    //-----------------------------------------------------------

    public class BRPostingHistorysController : BaseBusinessController
    {
        public BRPostingHistorysController()
        {
            dal = new DALBaseProvider("BRPostingHistorys", typeof(BRPostingHistorysInfo));
        }

        public BRPostingHistorysInfo GetPostingHistoryByStatusAndType(String strPostingHistoryStatus, String strPostingHistoryType)
        {
            return (BRPostingHistorysInfo)dal.GetDataObject("BRPostingHistorys_SelectByStatusAndType", strPostingHistoryStatus, strPostingHistoryType);
        }
        
        public DataSet GetPostingHistoriesByDate(DateTime dtDate)
        {
            return dal.GetDataSet("BRPostingHistorys_SelectByDate", dtDate);
        }
    }
    #endregion
}