
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER TRIGGER trg_MEEmrHasNote_insert
   ON  MEEmrDocumentNotes
   AFTER INSERT
AS 
BEGIN
	UPDATE MEEmrs
	SET MEEmrHasNote = (SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM inserted WHERE FK_MEEmrID = MEEmrs.MEEmrID)
	FROM MEEmrs
	INNER JOIN inserted ON MEEmrs.MEEmrID = inserted.FK_MEEmrID
END
GO
