using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ARCreditNotes
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARCreditNotesInfo
    //Created Date:Monday, March 29, 2010
    //-----------------------------------------------------------

    public class ARCreditNotesInfo : BusinessObject
    {
        public ARCreditNotesInfo()
        {
            IsTransferred = false;
        }

        #region Variables
        protected int _aRCreditNoteID;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_GECurrencyID;
        protected int _fK_ARCustomerID;
        protected int _fK_BRBranchID;
        protected int _fK_HREmployeeID;
        protected String _aRCreditNoteNo = String.Empty;
        protected String _aRCreditNoteName = String.Empty;
        protected String _aRCreditNoteDesc = String.Empty;
        protected DateTime _aRCreditNoteDate = DateTime.MaxValue;
        protected DateTime _aRCreditNoteExpiryDate = DateTime.MaxValue;
        protected String _aRCreditNoteType = String.Empty;
        protected String _aRCreditNoteStatus = DefaultStatus;
        protected double _aRCreditNoteTotalAmount;
        protected double _aRCreditNoteDueAmount;
        protected double _aRCreditNoteExchangeRate;
        protected bool _isTransferred = true;
        protected DateTime _aRCreditNoteTransferredDate = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int ARCreditNoteID
        {
            get { return _aRCreditNoteID; }
            set
            {
                if (value != this._aRCreditNoteID)
                {
                    _aRCreditNoteID = value;
                    NotifyChanged("ARCreditNoteID");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                    NotifyChanged("FK_GECurrencyID");
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                    NotifyChanged("FK_ARCustomerID");
                }
            }
        }
        public int FK_BRBranchID
        {
            get { return _fK_BRBranchID; }
            set
            {
                if (value != this._fK_BRBranchID)
                {
                    _fK_BRBranchID = value;
                    NotifyChanged("FK_BRBranchID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public String ARCreditNoteNo
        {
            get { return _aRCreditNoteNo; }
            set
            {
                if (value != this._aRCreditNoteNo)
                {
                    _aRCreditNoteNo = value;
                    NotifyChanged("ARCreditNoteNo");
                }
            }
        }
        public String ARCreditNoteName
        {
            get { return _aRCreditNoteName; }
            set
            {
                if (value != this._aRCreditNoteName)
                {
                    _aRCreditNoteName = value;
                    NotifyChanged("ARCreditNoteName");
                }
            }
        }
        public String ARCreditNoteDesc
        {
            get { return _aRCreditNoteDesc; }
            set
            {
                if (value != this._aRCreditNoteDesc)
                {
                    _aRCreditNoteDesc = value;
                    NotifyChanged("ARCreditNoteDesc");
                }
            }
        }
        public DateTime ARCreditNoteDate
        {
            get { return _aRCreditNoteDate; }
            set
            {
                if (value != this._aRCreditNoteDate)
                {
                    _aRCreditNoteDate = value;
                    NotifyChanged("ARCreditNoteDate");
                }
            }
        }
        public DateTime ARCreditNoteExpiryDate
        {
            get { return _aRCreditNoteExpiryDate; }
            set
            {
                if (value != this._aRCreditNoteExpiryDate)
                {
                    _aRCreditNoteExpiryDate = value;
                    NotifyChanged("ARCreditNoteExpiryDate");
                }
            }
        }
        public String ARCreditNoteType
        {
            get { return _aRCreditNoteType; }
            set
            {
                if (value != this._aRCreditNoteType)
                {
                    _aRCreditNoteType = value;
                    NotifyChanged("ARCreditNoteType");
                }
            }
        }
        public String ARCreditNoteStatus
        {
            get { return _aRCreditNoteStatus; }
            set
            {
                if (value != this._aRCreditNoteStatus)
                {
                    _aRCreditNoteStatus = value;
                    NotifyChanged("ARCreditNoteStatus");
                }
            }
        }
        public double ARCreditNoteTotalAmount
        {
            get { return _aRCreditNoteTotalAmount; }
            set
            {
                if (value != this._aRCreditNoteTotalAmount)
                {
                    _aRCreditNoteTotalAmount = value;
                    NotifyChanged("ARCreditNoteTotalAmount");
                }
            }
        }
        public double ARCreditNoteDueAmount
        {
            get { return _aRCreditNoteDueAmount; }
            set
            {
                if (value != this._aRCreditNoteDueAmount)
                {
                    _aRCreditNoteDueAmount = value;
                    NotifyChanged("ARCreditNoteDueAmount");
                }
            }
        }
        public double ARCreditNoteExchangeRate
        {
            get { return _aRCreditNoteExchangeRate; }
            set
            {
                if (value != this._aRCreditNoteExchangeRate)
                {
                    _aRCreditNoteExchangeRate = value;
                    NotifyChanged("ARCreditNoteExchangeRate");
                }
            }
        }
        public bool IsTransferred
        {
            get { return _isTransferred; }
            set
            {
                if (value != this._isTransferred)
                {
                    _isTransferred = value;
                    NotifyChanged("IsTransferred");
                }
            }
        }
        public DateTime ARCreditNoteTransferredDate
        {
            get { return _aRCreditNoteTransferredDate; }
            set
            {
                if (value != this._aRCreditNoteTransferredDate)
                {
                    _aRCreditNoteTransferredDate = value;
                    NotifyChanged("ARCreditNoteTransferredDate");
                }
            }
        }
        #endregion

        #region Extra Properties
        public byte[] ARCreditNoteEmployeePicture { get; set; }

        [FormatGroup(FormatGroupAttribute.cstFormatGroupPrice)]
        public double ARCreditNoteRemainedAmount { get; set; }

        public string ARCustomerNo { get; set; }
        #endregion
    }
    #endregion
}