using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ARProposals
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARProposalsInfo
    //Created Date:Friday, August 20, 2010
    //-----------------------------------------------------------

    public class ARProposalsInfo : BusinessObject
    {
        public ARProposalsInfo()
        {
        }
        #region Variables
        protected int _aRProposalID;
        protected String _aAStatus = DefaultAAStatus;
        protected String _aACreatedUser = String.Empty;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        protected int _fK_ARCustomerID;
        protected int _fK_HREmployeeID;
        protected int _fK_GECurrencyID;
        protected int _fK_ARPriceLevelID;
        protected int _fK_GEShippingMethodID;
        protected int _fK_ICStockID;
        protected int _fK_ICStockSlotID;
        protected String _aRProposalNo = String.Empty;
        protected String _aRProposalName = String.Empty;
        protected String _aRProposalDesc = String.Empty;
        protected DateTime _aRProposalDate = DateTime.MaxValue;
        protected DateTime _aRProposalValidateDate = DateTime.MaxValue;
        protected DateTime _aRProposalDeliveryDate = DateTime.MaxValue;
        protected String _aRProposalStatus = DefaultStatus;
        protected String _aRProposalTypeCombo = String.Empty;
        protected String _aRProposalPaymentTerm = String.Empty;
        protected String _aRPaymentMethodCombo = String.Empty;
        protected String _aRProposalMatchCode01Combo = String.Empty;
        protected String _aRProposalMatchCode02Combo = String.Empty;
        protected String _aRProposalMatchCode03Combo = String.Empty;
        protected String _aRProposalMatchCode04Combo = String.Empty;
        protected String _aRProposalMatchCode05Combo = String.Empty;
        protected String _aRProposalMatchCode06Combo = String.Empty;
        protected String _aRProposalMatchCode07Combo = String.Empty;
        protected String _aRProposalMatchCode08Combo = String.Empty;
        protected String _aRProposalMatchCode09Combo = String.Empty;
        protected String _aRProposalMatchCode10Combo = String.Empty;
        protected String _aRProposalMatchCode11Combo = String.Empty;
        protected String _aRProposalMatchCode12Combo = String.Empty;
        protected double _aRProposalDiscountPerCent;
        protected double _aRProposalDiscountFix;
        protected double _aRProposalNetAmount;
        protected double _aRProposalTaxAmount;
        protected double _aRProposalSubTotalAmount;
        protected double _aRProposalTotalAmount;
        #endregion

        #region Public properties
        public int ARProposalID
        {
            get { return _aRProposalID; }
            set
            {
                if (value != this._aRProposalID)
                {
                    _aRProposalID = value;
                    NotifyChanged("ARProposalID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        public int FK_ARCustomerID
        {
            get { return _fK_ARCustomerID; }
            set
            {
                if (value != this._fK_ARCustomerID)
                {
                    _fK_ARCustomerID = value;
                    NotifyChanged("FK_ARCustomerID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int FK_GECurrencyID
        {
            get { return _fK_GECurrencyID; }
            set
            {
                if (value != this._fK_GECurrencyID)
                {
                    _fK_GECurrencyID = value;
                    NotifyChanged("FK_GECurrencyID");
                }
            }
        }
        public int FK_ARPriceLevelID
        {
            get { return _fK_ARPriceLevelID; }
            set
            {
                if (value != this._fK_ARPriceLevelID)
                {
                    _fK_ARPriceLevelID = value;
                    NotifyChanged("FK_ARPriceLevelID");
                }
            }
        }
        public int FK_GEShippingMethodID
        {
            get { return _fK_GEShippingMethodID; }
            set
            {
                if (value != this._fK_GEShippingMethodID)
                {
                    _fK_GEShippingMethodID = value;
                    NotifyChanged("FK_GEShippingMethodID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ICStockSlotID
        {
            get { return _fK_ICStockSlotID; }
            set
            {
                if (value != this._fK_ICStockSlotID)
                {
                    _fK_ICStockSlotID = value;
                    NotifyChanged("FK_ICStockSlotID");
                }
            }
        }
        public String ARProposalNo
        {
            get { return _aRProposalNo; }
            set
            {
                if (value != this._aRProposalNo)
                {
                    _aRProposalNo = value;
                    NotifyChanged("ARProposalNo");
                }
            }
        }
        public String ARProposalName
        {
            get { return _aRProposalName; }
            set
            {
                if (value != this._aRProposalName)
                {
                    _aRProposalName = value;
                    NotifyChanged("ARProposalName");
                }
            }
        }
        public String ARProposalDesc
        {
            get { return _aRProposalDesc; }
            set
            {
                if (value != this._aRProposalDesc)
                {
                    _aRProposalDesc = value;
                    NotifyChanged("ARProposalDesc");
                }
            }
        }
        public DateTime ARProposalDate
        {
            get { return _aRProposalDate; }
            set
            {
                if (value != this._aRProposalDate)
                {
                    _aRProposalDate = value;
                    NotifyChanged("ARProposalDate");
                }
            }
        }
        public DateTime ARProposalValidateDate
        {
            get { return _aRProposalValidateDate; }
            set
            {
                if (value != this._aRProposalValidateDate)
                {
                    _aRProposalValidateDate = value;
                    NotifyChanged("ARProposalValidateDate");
                }
            }
        }
        public DateTime ARProposalDeliveryDate
        {
            get { return _aRProposalDeliveryDate; }
            set
            {
                if (value != this._aRProposalDeliveryDate)
                {
                    _aRProposalDeliveryDate = value;
                    NotifyChanged("ARProposalDeliveryDate");
                }
            }
        }
        public String ARProposalStatus
        {
            get { return _aRProposalStatus; }
            set
            {
                if (value != this._aRProposalStatus)
                {
                    _aRProposalStatus = value;
                    NotifyChanged("ARProposalStatus");
                }
            }
        }
        public String ARProposalTypeCombo
        {
            get { return _aRProposalTypeCombo; }
            set
            {
                if (value != this._aRProposalTypeCombo)
                {
                    _aRProposalTypeCombo = value;
                    NotifyChanged("ARProposalTypeCombo");
                }
            }
        }
        public String ARProposalPaymentTerm
        {
            get { return _aRProposalPaymentTerm; }
            set
            {
                if (value != this._aRProposalPaymentTerm)
                {
                    _aRProposalPaymentTerm = value;
                    NotifyChanged("ARProposalPaymentTerm");
                }
            }
        }
        public String ARPaymentMethodCombo
        {
            get { return _aRPaymentMethodCombo; }
            set
            {
                if (value != this._aRPaymentMethodCombo)
                {
                    _aRPaymentMethodCombo = value;
                    NotifyChanged("ARPaymentMethodCombo");
                }
            }
        }
        public String ARProposalMatchCode01Combo
        {
            get { return _aRProposalMatchCode01Combo; }
            set
            {
                if (value != this._aRProposalMatchCode01Combo)
                {
                    _aRProposalMatchCode01Combo = value;
                    NotifyChanged("ARProposalMatchCode01Combo");
                }
            }
        }
        public String ARProposalMatchCode02Combo
        {
            get { return _aRProposalMatchCode02Combo; }
            set
            {
                if (value != this._aRProposalMatchCode02Combo)
                {
                    _aRProposalMatchCode02Combo = value;
                    NotifyChanged("ARProposalMatchCode02Combo");
                }
            }
        }
        public String ARProposalMatchCode03Combo
        {
            get { return _aRProposalMatchCode03Combo; }
            set
            {
                if (value != this._aRProposalMatchCode03Combo)
                {
                    _aRProposalMatchCode03Combo = value;
                    NotifyChanged("ARProposalMatchCode03Combo");
                }
            }
        }
        public String ARProposalMatchCode04Combo
        {
            get { return _aRProposalMatchCode04Combo; }
            set
            {
                if (value != this._aRProposalMatchCode04Combo)
                {
                    _aRProposalMatchCode04Combo = value;
                    NotifyChanged("ARProposalMatchCode04Combo");
                }
            }
        }
        public String ARProposalMatchCode05Combo
        {
            get { return _aRProposalMatchCode05Combo; }
            set
            {
                if (value != this._aRProposalMatchCode05Combo)
                {
                    _aRProposalMatchCode05Combo = value;
                    NotifyChanged("ARProposalMatchCode05Combo");
                }
            }
        }
        public String ARProposalMatchCode06Combo
        {
            get { return _aRProposalMatchCode06Combo; }
            set
            {
                if (value != this._aRProposalMatchCode06Combo)
                {
                    _aRProposalMatchCode06Combo = value;
                    NotifyChanged("ARProposalMatchCode06Combo");
                }
            }
        }
        public String ARProposalMatchCode07Combo
        {
            get { return _aRProposalMatchCode07Combo; }
            set
            {
                if (value != this._aRProposalMatchCode07Combo)
                {
                    _aRProposalMatchCode07Combo = value;
                    NotifyChanged("ARProposalMatchCode07Combo");
                }
            }
        }
        public String ARProposalMatchCode08Combo
        {
            get { return _aRProposalMatchCode08Combo; }
            set
            {
                if (value != this._aRProposalMatchCode08Combo)
                {
                    _aRProposalMatchCode08Combo = value;
                    NotifyChanged("ARProposalMatchCode08Combo");
                }
            }
        }
        public String ARProposalMatchCode09Combo
        {
            get { return _aRProposalMatchCode09Combo; }
            set
            {
                if (value != this._aRProposalMatchCode09Combo)
                {
                    _aRProposalMatchCode09Combo = value;
                    NotifyChanged("ARProposalMatchCode09Combo");
                }
            }
        }
        public String ARProposalMatchCode10Combo
        {
            get { return _aRProposalMatchCode10Combo; }
            set
            {
                if (value != this._aRProposalMatchCode10Combo)
                {
                    _aRProposalMatchCode10Combo = value;
                    NotifyChanged("ARProposalMatchCode10Combo");
                }
            }
        }
        public String ARProposalMatchCode11Combo
        {
            get { return _aRProposalMatchCode11Combo; }
            set
            {
                if (value != this._aRProposalMatchCode11Combo)
                {
                    _aRProposalMatchCode11Combo = value;
                    NotifyChanged("ARProposalMatchCode11Combo");
                }
            }
        }
        public String ARProposalMatchCode12Combo
        {
            get { return _aRProposalMatchCode12Combo; }
            set
            {
                if (value != this._aRProposalMatchCode12Combo)
                {
                    _aRProposalMatchCode12Combo = value;
                    NotifyChanged("ARProposalMatchCode12Combo");
                }
            }
        }
        public double ARProposalDiscountPerCent
        {
            get { return _aRProposalDiscountPerCent; }
            set
            {
                if (value != this._aRProposalDiscountPerCent)
                {
                    _aRProposalDiscountPerCent = value;
                    NotifyChanged("ARProposalDiscountPerCent");
                }
            }
        }
        public double ARProposalDiscountFix
        {
            get { return _aRProposalDiscountFix; }
            set
            {
                if (value != this._aRProposalDiscountFix)
                {
                    _aRProposalDiscountFix = value;
                    NotifyChanged("ARProposalDiscountFix");
                }
            }
        }
        public double ARProposalNetAmount
        {
            get { return _aRProposalNetAmount; }
            set
            {
                if (value != this._aRProposalNetAmount)
                {
                    _aRProposalNetAmount = value;
                    NotifyChanged("ARProposalNetAmount");
                }
            }
        }
        public double ARProposalTaxAmount
        {
            get { return _aRProposalTaxAmount; }
            set
            {
                if (value != this._aRProposalTaxAmount)
                {
                    _aRProposalTaxAmount = value;
                    NotifyChanged("ARProposalTaxAmount");
                }
            }
        }
        public double ARProposalSubTotalAmount
        {
            get { return _aRProposalSubTotalAmount; }
            set
            {
                if (value != this._aRProposalSubTotalAmount)
                {
                    _aRProposalSubTotalAmount = value;
                    NotifyChanged("ARProposalSubTotalAmount");
                }
            }
        }
        public double ARProposalTotalAmount
        {
            get { return _aRProposalTotalAmount; }
            set
            {
                if (value != this._aRProposalTotalAmount)
                {
                    _aRProposalTotalAmount = value;
                    NotifyChanged("ARProposalTotalAmount");
                }
            }
        }
        #endregion

        #region Extra Properties
        public byte[] ARProposalEmployeePicture { get; set; }
        public string ARCustomerName { get; set; }
        public string ARPaymentMethod { get; set; }
        #endregion
    }
    #endregion
}