using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
	#region ARPriceListDetails
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:ARPriceListDetailsInfo
	//Created Date:Friday, March 28, 2008
	//-----------------------------------------------------------
	
	public class ARPriceListDetailsInfo:BusinessObject
	{
		public ARPriceListDetailsInfo()
		{
		}
		#region Variables
		protected int _aRPriceListDetailID;
		protected String _aAStatus=DefaultAAStatus;
		protected int _fK_ARPriceListID;
		protected int _fK_ICProductID;
		protected int _fK_GECurrencyID;
		protected String _aRPriceListDetailName=String.Empty;
		protected double _aRPriceListDetailProductSalePrice;
		protected double _aRPriceListDetailProductDiscountPercent;
		protected DateTime _aRPriceListDetailFromDate=DateTime.MaxValue;
		protected DateTime _aRPriceListDetailToDate=DateTime.MaxValue;
		protected double _aRPriceListDetailFromQuantity;
		protected double _aRPriceListDetailToQuantity;
		#endregion

		#region Public properties
		public int ARPriceListDetailID
		{
			get{return _aRPriceListDetailID;}
			set
			{
				if (value != this._aRPriceListDetailID)
				{
				_aRPriceListDetailID=value;
				NotifyChanged("ARPriceListDetailID");
				}
			}
		}
		public String AAStatus
		{
			get{return _aAStatus;}
			set
			{
				if (value != this._aAStatus)
				{
				_aAStatus=value;
				NotifyChanged("AAStatus");
				}
			}
		}
		public int FK_ARPriceListID
		{
			get{return _fK_ARPriceListID;}
			set
			{
				if (value != this._fK_ARPriceListID)
				{
				_fK_ARPriceListID=value;
				NotifyChanged("FK_ARPriceListID");
				}
			}
		}
		public int FK_ICProductID
		{
			get{return _fK_ICProductID;}
			set
			{
				if (value != this._fK_ICProductID)
				{
				_fK_ICProductID=value;
				NotifyChanged("FK_ICProductID");
				}
			}
		}
		public int FK_GECurrencyID
		{
			get{return _fK_GECurrencyID;}
			set
			{
				if (value != this._fK_GECurrencyID)
				{
				_fK_GECurrencyID=value;
				NotifyChanged("FK_GECurrencyID");
				}
			}
		}
		public String ARPriceListDetailName
		{
			get{return _aRPriceListDetailName;}
			set
			{
				if (value != this._aRPriceListDetailName)
				{
				_aRPriceListDetailName=value;
				NotifyChanged("ARPriceListDetailName");
				}
			}
		}
		public double ARPriceListDetailProductSalePrice
		{
			get{return _aRPriceListDetailProductSalePrice;}
			set
			{
				if (value != this._aRPriceListDetailProductSalePrice)
				{
				_aRPriceListDetailProductSalePrice=value;
				NotifyChanged("ARPriceListDetailProductSalePrice");
				}
			}
		}
		public double ARPriceListDetailProductDiscountPercent
		{
			get{return _aRPriceListDetailProductDiscountPercent;}
			set
			{
				if (value != this._aRPriceListDetailProductDiscountPercent)
				{
				_aRPriceListDetailProductDiscountPercent=value;
				NotifyChanged("ARPriceListDetailProductDiscountPercent");
				}
			}
		}
		public DateTime ARPriceListDetailFromDate
		{
			get{return _aRPriceListDetailFromDate;}
			set
			{
				if (value != this._aRPriceListDetailFromDate)
				{
				_aRPriceListDetailFromDate=value;
				NotifyChanged("ARPriceListDetailFromDate");
				}
			}
		}
		public DateTime ARPriceListDetailToDate
		{
			get{return _aRPriceListDetailToDate;}
			set
			{
				if (value != this._aRPriceListDetailToDate)
				{
				_aRPriceListDetailToDate=value;
				NotifyChanged("ARPriceListDetailToDate");
				}
			}
		}
		public double ARPriceListDetailFromQuantity
		{
			get{return _aRPriceListDetailFromQuantity;}
			set
			{
				if (value != this._aRPriceListDetailFromQuantity)
				{
				_aRPriceListDetailFromQuantity=value;
				NotifyChanged("ARPriceListDetailFromQuantity");
				}
			}
		}
		public double ARPriceListDetailToQuantity
		{
			get{return _aRPriceListDetailToQuantity;}
			set
			{
				if (value != this._aRPriceListDetailToQuantity)
				{
				_aRPriceListDetailToQuantity=value;
				NotifyChanged("ARPriceListDetailToQuantity");
				}
			}
		}
		#endregion
	}
	#endregion
}