using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ARSaleReturnItems
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ARSaleReturnItemsInfo
    //Created Date:Sunday, April 11, 2010
    //-----------------------------------------------------------

    public class ARSaleReturnItemsInfo : ERPModuleItemsEntity
    {
        public ARSaleReturnItemsInfo()
        {
        }

        #region Variables
        protected int _aRSaleReturnItemID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ARSaleReturnID;
        protected int _fK_ICDepartmentID;
        protected int _fK_ICProductGroupID;
        protected int _fK_ICProductID;
        protected int _fK_ICProductSerieID;
        protected int _fK_ICMeasureUnitID;
        protected int _fK_ICStockID;
        protected int _fK_ARInvoiceID;
        protected int _fK_ARInvoiceItemID;
        protected String _aRSaleReturnItemProductSerialNo = String.Empty;
        protected String _aRSaleReturnItemProductAttribute = String.Empty;
        protected String _aRSaleReturnItemProductType = String.Empty;
        protected int _aRSaleReturnItemSortOrder;
        protected String _aRSaleReturnItemProductName = String.Empty;
        protected String _aRSaleReturnItemProductDesc = String.Empty;
        protected double _aRSaleReturnItemProductUnitPrice;
        protected double _aRSaleReturnItemProductUnitCost;
        protected double _aRSaleReturnItemProductDiscount;
        protected double _aRSaleReturnItemProductTaxPercent;
        protected double _aRSaleReturnItemProductQty;
        protected String _aRSaleReturnItemComment = String.Empty;
        protected double _aRSaleReturnItemPrice;
        protected double _aRSaleReturnItemTaxAmount;
        protected double _aRSaleReturnItemDiscountAmount;
        protected double _aRSaleReturnItemNetAmount;
        protected double _aRSaleReturnItemTotalAmount;
        protected double _aRSaleReturnItemTotalCost;
        protected String _aRSaleReturnItemProductSupplierNo = String.Empty;
        #endregion

        #region Public properties
        public int ARSaleReturnItemID
        {
            get { return _aRSaleReturnItemID; }
            set
            {
                if (value != this._aRSaleReturnItemID)
                {
                    _aRSaleReturnItemID = value;
                    NotifyChanged("ARSaleReturnItemID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ARSaleReturnID
        {
            get { return _fK_ARSaleReturnID; }
            set
            {
                if (value != this._fK_ARSaleReturnID)
                {
                    _fK_ARSaleReturnID = value;
                    NotifyChanged("FK_ARSaleReturnID");
                }
            }
        }
        public int FK_ICDepartmentID
        {
            get { return _fK_ICDepartmentID; }
            set
            {
                if (value != this._fK_ICDepartmentID)
                {
                    _fK_ICDepartmentID = value;
                    NotifyChanged("FK_ICDepartmentID");
                }
            }
        }
        public int FK_ICProductGroupID
        {
            get { return _fK_ICProductGroupID; }
            set
            {
                if (value != this._fK_ICProductGroupID)
                {
                    _fK_ICProductGroupID = value;
                    NotifyChanged("FK_ICProductGroupID");
                }
            }
        }
        public int FK_ICProductID
        {
            get { return _fK_ICProductID; }
            set
            {
                if (value != this._fK_ICProductID)
                {
                    _fK_ICProductID = value;
                    NotifyChanged("FK_ICProductID");
                }
            }
        }
        public int FK_ICProductSerieID
        {
            get { return _fK_ICProductSerieID; }
            set
            {
                if (value != this._fK_ICProductSerieID)
                {
                    _fK_ICProductSerieID = value;
                    NotifyChanged("FK_ICProductSerieID");
                }
            }
        }
        public int FK_ICMeasureUnitID
        {
            get { return _fK_ICMeasureUnitID; }
            set
            {
                if (value != this._fK_ICMeasureUnitID)
                {
                    _fK_ICMeasureUnitID = value;
                    NotifyChanged("FK_ICMeasureUnitID");
                }
            }
        }
        public int FK_ICStockID
        {
            get { return _fK_ICStockID; }
            set
            {
                if (value != this._fK_ICStockID)
                {
                    _fK_ICStockID = value;
                    NotifyChanged("FK_ICStockID");
                }
            }
        }
        public int FK_ARInvoiceID
        {
            get { return _fK_ARInvoiceID; }
            set
            {
                if (value != this._fK_ARInvoiceID)
                {
                    _fK_ARInvoiceID = value;
                    NotifyChanged("FK_ARInvoiceID");
                }
            }
        }
        public int FK_ARInvoiceItemID
        {
            get { return _fK_ARInvoiceItemID; }
            set
            {
                if (value != this._fK_ARInvoiceItemID)
                {
                    _fK_ARInvoiceItemID = value;
                    NotifyChanged("FK_ARInvoiceItemID");
                }
            }
        }
        public String ARSaleReturnItemProductSerialNo
        {
            get { return _aRSaleReturnItemProductSerialNo; }
            set
            {
                if (value != this._aRSaleReturnItemProductSerialNo)
                {
                    _aRSaleReturnItemProductSerialNo = value;
                    NotifyChanged("ARSaleReturnItemProductSerialNo");
                }
            }
        }
        public String ARSaleReturnItemProductAttribute
        {
            get { return _aRSaleReturnItemProductAttribute; }
            set
            {
                if (value != this._aRSaleReturnItemProductAttribute)
                {
                    _aRSaleReturnItemProductAttribute = value;
                    NotifyChanged("ARSaleReturnItemProductAttribute");
                }
            }
        }
        public String ARSaleReturnItemProductType
        {
            get { return _aRSaleReturnItemProductType; }
            set
            {
                if (value != this._aRSaleReturnItemProductType)
                {
                    _aRSaleReturnItemProductType = value;
                    NotifyChanged("ARSaleReturnItemProductType");
                }
            }
        }
        public int ARSaleReturnItemSortOrder
        {
            get { return _aRSaleReturnItemSortOrder; }
            set
            {
                if (value != this._aRSaleReturnItemSortOrder)
                {
                    _aRSaleReturnItemSortOrder = value;
                    NotifyChanged("ARSaleReturnItemSortOrder");
                }
            }
        }
        public String ARSaleReturnItemProductName
        {
            get { return _aRSaleReturnItemProductName; }
            set
            {
                if (value != this._aRSaleReturnItemProductName)
                {
                    _aRSaleReturnItemProductName = value;
                    NotifyChanged("ARSaleReturnItemProductName");
                }
            }
        }
        public String ARSaleReturnItemProductDesc
        {
            get { return _aRSaleReturnItemProductDesc; }
            set
            {
                if (value != this._aRSaleReturnItemProductDesc)
                {
                    _aRSaleReturnItemProductDesc = value;
                    NotifyChanged("ARSaleReturnItemProductDesc");
                }
            }
        }
        public double ARSaleReturnItemProductUnitPrice
        {
            get { return _aRSaleReturnItemProductUnitPrice; }
            set
            {
                if (value != this._aRSaleReturnItemProductUnitPrice)
                {
                    _aRSaleReturnItemProductUnitPrice = value;
                    NotifyChanged("ARSaleReturnItemProductUnitPrice");
                }
            }
        }
        public double ARSaleReturnItemProductUnitCost
        {
            get { return _aRSaleReturnItemProductUnitCost; }
            set
            {
                if (value != this._aRSaleReturnItemProductUnitCost)
                {
                    _aRSaleReturnItemProductUnitCost = value;
                    NotifyChanged("ARSaleReturnItemProductUnitCost");
                }
            }
        }
        public double ARSaleReturnItemProductDiscount
        {
            get { return _aRSaleReturnItemProductDiscount; }
            set
            {
                if (value != this._aRSaleReturnItemProductDiscount)
                {
                    _aRSaleReturnItemProductDiscount = value;
                    NotifyChanged("ARSaleReturnItemProductDiscount");
                }
            }
        }
        public double ARSaleReturnItemProductTaxPercent
        {
            get { return _aRSaleReturnItemProductTaxPercent; }
            set
            {
                if (value != this._aRSaleReturnItemProductTaxPercent)
                {
                    _aRSaleReturnItemProductTaxPercent = value;
                    NotifyChanged("ARSaleReturnItemProductTaxPercent");
                }
            }
        }
        public double ARSaleReturnItemProductQty
        {
            get { return _aRSaleReturnItemProductQty; }
            set
            {
                if (value != this._aRSaleReturnItemProductQty)
                {
                    _aRSaleReturnItemProductQty = value;
                    NotifyChanged("ARSaleReturnItemProductQty");
                }
            }
        }
        public String ARSaleReturnItemComment
        {
            get { return _aRSaleReturnItemComment; }
            set
            {
                if (value != this._aRSaleReturnItemComment)
                {
                    _aRSaleReturnItemComment = value;
                    NotifyChanged("ARSaleReturnItemComment");
                }
            }
        }
        public double ARSaleReturnItemPrice
        {
            get { return _aRSaleReturnItemPrice; }
            set
            {
                if (value != this._aRSaleReturnItemPrice)
                {
                    _aRSaleReturnItemPrice = value;
                    NotifyChanged("ARSaleReturnItemPrice");
                }
            }
        }
        public double ARSaleReturnItemTaxAmount
        {
            get { return _aRSaleReturnItemTaxAmount; }
            set
            {
                if (value != this._aRSaleReturnItemTaxAmount)
                {
                    _aRSaleReturnItemTaxAmount = value;
                    NotifyChanged("ARSaleReturnItemTaxAmount");
                }
            }
        }
        public double ARSaleReturnItemDiscountAmount
        {
            get { return _aRSaleReturnItemDiscountAmount; }
            set
            {
                if (value != this._aRSaleReturnItemDiscountAmount)
                {
                    _aRSaleReturnItemDiscountAmount = value;
                    NotifyChanged("ARSaleReturnItemDiscountAmount");
                }
            }
        }
        public double ARSaleReturnItemNetAmount
        {
            get { return _aRSaleReturnItemNetAmount; }
            set
            {
                if (value != this._aRSaleReturnItemNetAmount)
                {
                    _aRSaleReturnItemNetAmount = value;
                    NotifyChanged("ARSaleReturnItemNetAmount");
                }
            }
        }
        public double ARSaleReturnItemTotalAmount
        {
            get { return _aRSaleReturnItemTotalAmount; }
            set
            {
                if (value != this._aRSaleReturnItemTotalAmount)
                {
                    _aRSaleReturnItemTotalAmount = value;
                    NotifyChanged("ARSaleReturnItemTotalAmount");
                }
            }
        }
        public double ARSaleReturnItemTotalCost
        {
            get { return _aRSaleReturnItemTotalCost; }
            set
            {
                if (value != this._aRSaleReturnItemTotalCost)
                {
                    _aRSaleReturnItemTotalCost = value;
                    NotifyChanged("ARSaleReturnItemTotalCost");
                }
            }
        }
        public String ARSaleReturnItemProductSupplierNo
        {
            get { return _aRSaleReturnItemProductSupplierNo; }
            set
            {
                if (value != this._aRSaleReturnItemProductSupplierNo)
                {
                    _aRSaleReturnItemProductSupplierNo = value;
                    NotifyChanged("ARSaleReturnItemProductSupplierNo");
                }
            }
        }
        #endregion

        #region Extra Properties

        
        public byte[] ARSaleReturnItemProductPicture { get; set; }


        public string ARSaleReturnNo { get; set; }
        public DateTime ARSaleReturnDate { get; set; }

        public string ARInvoiceNo { get; set; }
        public DateTime ARInvoiceDate { get; set; }

        public string ARSellerName { get; set; }
        public string ARCustomerName { get; set; }
        public string HREmployeeName { get; set; }
        public string ARSaleOrderNo { get; set; }
        public DateTime ARSaleOrderDate { get; set; }
                

        /// <summary>
        /// Gets or sets the list of invoice item component
        /// </summary>
        public IBOSList<ARSaleReturnItemComponentsInfo> SaleReturnItemComponentList { get; set; }

        public string ICProductSerieNo { get; set; }

        public DateTime ICProductSerieReceiptDate { get; set; }

        public bool HasComponent { get; set; }

        public bool IsSubItem { get; set; }        
        #endregion
    }
    #endregion
}