using System;
using System.Data;
using System.Text;
using System.Collections.Generic;
using BOSLib;


namespace BOSERP
{
	#region MEReportBHYT917Xml2s
	//-----------------------------------------------------------
	//Generated By: BOS Studio
	//Class:MEReportBHYT917Xml2sController
	//Created Date:Thursday, July 20, 2017
	//-----------------------------------------------------------
	
	public class MEReportBHYT917Xml2sController:BaseBusinessController
	{
		public MEReportBHYT917Xml2sController()
		{
			dal= new DALBaseProvider("MEReportBHYT917Xml2s",typeof(MEReportBHYT917Xml2sInfo));
		}
	}
	#endregion
}