using System;
using System.Text;
using System.Collections.Generic;
using BOSLib;
namespace BOSERP
{
    #region ADUserGroupExtras
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ADUserGroupExtrasInfo
    //Created Date:Wednesday, July 22, 2020
    //-----------------------------------------------------------

    public class ADUserGroupExtrasInfo : BusinessObject
    {
        public ADUserGroupExtrasInfo()
        {
        }
        #region Variables
        protected int _aDUserGroupExtraID;
        protected String _aAStatus = DefaultAAStatus;
        protected int _fK_ADUserGroupID;
        protected int _fK_ADUserID;
        protected DateTime _aDUserGroupExtraDateAdd = DateTime.MaxValue;
        protected String _aACreatedUser = String.Empty;
        protected DateTime _aACreatedDate = DateTime.MaxValue;
        protected String _aAUpdatedUser = String.Empty;
        protected DateTime _aAUpdatedDate = DateTime.MaxValue;
        #endregion

        #region Public properties
        public int ADUserGroupExtraID
        {
            get { return _aDUserGroupExtraID; }
            set
            {
                if (value != this._aDUserGroupExtraID)
                {
                    _aDUserGroupExtraID = value;
                    NotifyChanged("ADUserGroupExtraID");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int FK_ADUserGroupID
        {
            get { return _fK_ADUserGroupID; }
            set
            {
                if (value != this._fK_ADUserGroupID)
                {
                    _fK_ADUserGroupID = value;
                    NotifyChanged("FK_ADUserGroupID");
                }
            }
        }
        public int FK_ADUserID
        {
            get { return _fK_ADUserID; }
            set
            {
                if (value != this._fK_ADUserID)
                {
                    _fK_ADUserID = value;
                    NotifyChanged("FK_ADUserID");
                }
            }
        }
        public DateTime ADUserGroupExtraDateAdd
        {
            get { return _aDUserGroupExtraDateAdd; }
            set
            {
                if (value != this._aDUserGroupExtraDateAdd)
                {
                    _aDUserGroupExtraDateAdd = value;
                    NotifyChanged("ADUserGroupExtraDateAdd");
                }
            }
        }
        public String AACreatedUser
        {
            get { return _aACreatedUser; }
            set
            {
                if (value != this._aACreatedUser)
                {
                    _aACreatedUser = value;
                    NotifyChanged("AACreatedUser");
                }
            }
        }
        public DateTime AACreatedDate
        {
            get { return _aACreatedDate; }
            set
            {
                if (value != this._aACreatedDate)
                {
                    _aACreatedDate = value;
                    NotifyChanged("AACreatedDate");
                }
            }
        }
        public String AAUpdatedUser
        {
            get { return _aAUpdatedUser; }
            set
            {
                if (value != this._aAUpdatedUser)
                {
                    _aAUpdatedUser = value;
                    NotifyChanged("AAUpdatedUser");
                }
            }
        }
        public DateTime AAUpdatedDate
        {
            get { return _aAUpdatedDate; }
            set
            {
                if (value != this._aAUpdatedDate)
                {
                    _aAUpdatedDate = value;
                    NotifyChanged("AAUpdatedDate");
                }
            }
        }
        #endregion
    }
    #endregion
}