using System;
using System.Text;
using System.Collections.Generic;

namespace BOSLib
{
    #region ADUsers
    //-----------------------------------------------------------
    //Generated By: BOS Studio
    //Class:ADUsersInfo
    //Created Date:Saturday, March 13, 2010
    //-----------------------------------------------------------

    public class ADUsersInfo : BusinessObject
    {
        public ADUsersInfo()
        {
        }
        #region Variables
        protected int _aDUserID;
        protected String _aANumberString = String.Empty;
        protected int _aANumberInt;
        protected String _aAStatus = DefaultAAStatus;
        protected int _aDUserGroupID;
        protected int _fK_HREmployeeID;
        protected int _aDContactID;
        protected String _aDUserName = String.Empty;
        protected String _aDPassword = String.Empty;
        protected String _aDProfileDirectory = String.Empty;
        protected String _aDUserStyle = String.Empty;
        protected String _aDUserStyleSkin = String.Empty;
        protected bool _aDUserActiveCheck = true;
        protected int _aDUserEndTimeDefault;
        protected int _adUserBranchId;
        protected String _aDUserHISID = String.Empty;
        protected String _aDUserEmrView = String.Empty;
        protected String _aDUserOnComputerName = String.Empty;
        protected String _aDUserOnIpAddress = String.Empty;
        protected String _aDUserOnComputerMAC = String.Empty;

        protected String _aDUserCaIdentity = String.Empty;
        protected String _aDUserCaPasscode = String.Empty;
        #endregion

        #region Public properties
        public int ADUserID
        {
            get { return _aDUserID; }
            set
            {
                if (value != this._aDUserID)
                {
                    _aDUserID = value;
                    NotifyChanged("ADUserID");
                }
            }
        }
        public String AANumberString
        {
            get { return _aANumberString; }
            set
            {
                if (value != this._aANumberString)
                {
                    _aANumberString = value;
                    NotifyChanged("AANumberString");
                }
            }
        }
        public int AANumberInt
        {
            get { return _aANumberInt; }
            set
            {
                if (value != this._aANumberInt)
                {
                    _aANumberInt = value;
                    NotifyChanged("AANumberInt");
                }
            }
        }
        public String AAStatus
        {
            get { return _aAStatus; }
            set
            {
                if (value != this._aAStatus)
                {
                    _aAStatus = value;
                    NotifyChanged("AAStatus");
                }
            }
        }
        public int ADUserGroupID
        {
            get { return _aDUserGroupID; }
            set
            {
                if (value != this._aDUserGroupID)
                {
                    _aDUserGroupID = value;
                    NotifyChanged("ADUserGroupID");
                }
            }
        }
        public int FK_HREmployeeID
        {
            get { return _fK_HREmployeeID; }
            set
            {
                if (value != this._fK_HREmployeeID)
                {
                    _fK_HREmployeeID = value;
                    NotifyChanged("FK_HREmployeeID");
                }
            }
        }
        public int ADContactID
        {
            get { return _aDContactID; }
            set
            {
                if (value != this._aDContactID)
                {
                    _aDContactID = value;
                    NotifyChanged("ADContactID");
                }
            }
        }
        public String ADUserName
        {
            get { return _aDUserName; }
            set
            {
                if (value != this._aDUserName)
                {
                    _aDUserName = value;
                    NotifyChanged("ADUserName");
                }
            }
        }
        public String ADPassword
        {
            get { return _aDPassword; }
            set
            {
                if (value != this._aDPassword)
                {
                    _aDPassword = value;
                    NotifyChanged("ADPassword");
                }
            }
        }
        public String ADProfileDirectory
        {
            get { return _aDProfileDirectory; }
            set
            {
                if (value != this._aDProfileDirectory)
                {
                    _aDProfileDirectory = value;
                    NotifyChanged("ADProfileDirectory");
                }
            }
        }
        public String ADUserStyle
        {
            get { return _aDUserStyle; }
            set
            {
                if (value != this._aDUserStyle)
                {
                    _aDUserStyle = value;
                    NotifyChanged("ADUserStyle");
                }
            }
        }
        public String ADUserStyleSkin
        {
            get { return _aDUserStyleSkin; }
            set
            {
                if (value != this._aDUserStyleSkin)
                {
                    _aDUserStyleSkin = value;
                    NotifyChanged("ADUserStyleSkin");
                }
            }
        }
        public bool ADUserActiveCheck
        {
            get { return _aDUserActiveCheck; }
            set
            {
                if (value != this._aDUserActiveCheck)
                {
                    _aDUserActiveCheck = value;
                    NotifyChanged("ADUserActiveCheck");
                }
            }
        }

        public int ADUserEndTimeDefault
        {
            get { return _aDUserEndTimeDefault; }
            set
            {
                if (value != this._aDUserEndTimeDefault)
                {
                    _aDUserEndTimeDefault = value;
                    NotifyChanged("ADUserEndTimeDefault");
                }
            }
        }
        public int ADUserBranchId
        {
            get { return _adUserBranchId; }
            set
            {
                if (value != this._adUserBranchId)
                {
                    _adUserBranchId = value;
                    NotifyChanged("ADUserBranchId");
                }
            }
        }
        public String ADUserHISID
        {
            get { return _aDUserHISID; }
            set
            {
                if (value != this._aDUserHISID)
                {
                    _aDUserHISID = value;
                    NotifyChanged("ADUserHISID");
                }
            }
        }
        public String ADUserEmrView
        {
            get { return _aDUserEmrView; }
            set
            {
                if (value != this._aDUserEmrView)
                {
                    _aDUserEmrView = value;
                    NotifyChanged("ADUserEmrView");
                }
            }
        }
        public String ADUserOnComputerName
        {
            get { return _aDUserOnComputerName; }
            set
            {
                if (value != this._aDUserOnComputerName)
                {
                    _aDUserOnComputerName = value;
                    NotifyChanged("ADUserOnComputerName");
                }
            }
        }
        public String ADUserOnIpAddress
        {
            get { return _aDUserOnIpAddress; }
            set
            {
                if (value != this._aDUserOnIpAddress)
                {
                    _aDUserOnIpAddress = value;
                    NotifyChanged("ADUserOnIpAddress");
                }
            }
        }
        public String ADUserOnComputerMAC
        {
            get { return _aDUserOnComputerMAC; }
            set
            {
                if (value != this._aDUserOnComputerMAC)
                {
                    _aDUserOnComputerMAC = value;
                    NotifyChanged("ADUserOnComputerMAC");
                }
            }
        }
        public String ADUserCaIdentity
        {
            get { return _aDUserCaIdentity; }
            set
            {
                if (value != this._aDUserCaIdentity)
                {
                    _aDUserCaIdentity = value;
                    NotifyChanged("ADUserCaIdentity");
                }
            }
        }
        public String ADUserCaPasscode
        {
            get { return _aDUserCaPasscode; }
            set
            {
                if (value != this._aDUserCaPasscode)
                {
                    _aDUserCaPasscode = value;
                    NotifyChanged("ADUserCaPasscode");
                }
            }
        }
        #endregion

        #region Extra properties
        public string MEEndTimeFrameValue { get; set; }
        #endregion Extra properties
    }
    #endregion
}